import { useEffect, useState } from 'react';
import { Badge, Button, Card, Input, Textarea } from '../../components/ui';
import { Field } from '../../components/closegraph/Field';
import { DownloadLink } from '../../components/closegraph/DocumentPreview';
import type { CollectionsApi } from './api';
import type { Collection, ComparisonPage } from './model';
import { documentName, documentsFor, statusLabel } from './presentation';
function location(value:unknown){if(!value||typeof value!=='object')return 'Document';const l=value as Record<string,unknown>;if(l.original_page)return 'Page '+l.original_page;if(l.sheet&&l.cell)return l.sheet+' · '+l.cell;if(l.row)return 'Row '+l.row+(l.column?' · column '+l.column:'');return typeof l.sheet==='string'?l.sheet:'Document';}
function readable(value:unknown):string{if(value===null||value===undefined)return 'Not present';if(typeof value!=='object')return String(value);if(Array.isArray(value))return value.map(readable).join(', ');const v=value as Record<string,unknown>;if('value' in v){const formula=v.formula as {text?:string}|null;const style=v.style as {number_format?:string}|null;return [v.value==null?'Empty value':String(v.value),formula?.text?'Formula: '+formula.text:'',v.cached_value!=null?'Saved result: '+v.cached_value:'',style?.number_format?'Number format: '+style.number_format:''].filter(Boolean).join('\n');}return Object.entries(v).filter(([key])=>!['fingerprint','hash','id'].includes(key)).map(([key,item])=>statusLabel(key)+': '+readable(item)).join('\n');}
interface Props {collection:Collection;api:CollectionsApi;pending:boolean;canManage:boolean;onChange:(action:()=>Promise<Collection>)=>Promise<void>;onError:(error:unknown)=>void}
export function ChangesPanel({collection,api,pending,canManage,onChange,onError}:Props){
 const comparisons=collection.comparisons??[],[selected,setSelected]=useState(''),[offset,setOffset]=useState(0),[page,setPage]=useState<ComparisonPage|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[keyDocument,setKeyDocument]=useState(''),[sheet,setSheet]=useState(''),[keyColumns,setKeyColumns]=useState(''),[headerRow,setHeaderRow]=useState('1'),[reviewReason,setReviewReason]=useState(''),[attested,setAttested]=useState(false);
 useEffect(()=>{setReviewReason('');setAttested(false);},[selected,collection.version]);
 const comparison=comparisons.find(c=>c.id===selected)??comparisons[comparisons.length-1],docs=documentsFor(collection);
 useEffect(()=>{if(!comparison){setPage(null);return;}const controller=new AbortController();setLoading(true);setPage(null);setError('');api.comparison(collection.id,comparison.id,offset,50,controller.signal).then(result=>{if(!controller.signal.aborted)setPage(result);}).catch(e=>{if(!controller.signal.aborted){setError((e as Error).message);onError(e);}}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[api,collection.id,collection.version,comparison?.id,offset,onError]);
 async function saveKeys(event:React.FormEvent){event.preventDefault();try{const columns=keyColumns.split(',').map(value=>value.trim().toUpperCase()).filter(Boolean);if(!keyDocument||!sheet.trim()||!columns.length||columns.some(value=>!/^[A-Z]+$/.test(value))||!Number.isInteger(Number(headerRow))||Number(headerRow)<1)throw new Error('Choose a document, enter its worksheet name, column letters and header row.');await onChange(()=>api.documentKeys(collection.id,collection.version,keyDocument,{[sheet.trim()]:{columns,header_row:Number(headerRow)}}));setError('');}catch(e){setError((e as Error).message);}}
 return <div className="stack"><Card><div className="section-head"><div><h2>Review changes</h2><p className="caption">Compare a document with its earlier version before accepting revised evidence.</p></div></div>{comparisons.length?<Field id="evidence-comparison" label="Document version comparison"><select id="evidence-comparison" className="input" value={comparison?.id??''} onChange={e=>{setSelected(e.target.value);setOffset(0);}}>{comparisons.map((c,index)=><option key={c.id} value={c.id}>{documentName(collection,c.document_id)} · comparison {index+1} · {statusLabel(c.status)}</option>)}</select></Field>:<p className="empty muted">No revised documents yet. In Documents, select an existing document and choose “Upload new version”.</p>}{comparison&&<div className="evidence-comparison-links"><DownloadLink url={api.sourceUrl(collection.id,comparison.before_revision_id)} label="Open previous original"/><span aria-hidden>→</span><DownloadLink url={api.sourceUrl(collection.id,comparison.after_revision_id)} label="Open new original"/></div>}</Card>
 {error&&<p role="alert">{error}</p>}{loading&&<p role="status">Comparing document versions…</p>}
 {page&&<><Card><div className="section-head"><h2>{page.total.toLocaleString()} recorded change{page.total===1?'':'s'}</h2><Badge tone={page.coverage.complete?'success':'warning'}>{page.coverage.complete?'Comparison complete':'Review comparison limits'}</Badge></div>{!page.coverage.complete&&<p className="collection-callout">This comparison could not establish complete coverage. Inspect both originals before relying on an unchanged value.</p>}{page.ambiguities.length>0&&<div role="status" className="collection-callout"><strong>Some rows could not be matched confidently</strong><ul>{page.ambiguities.map((a,index)=><li key={String(a.id??index)}>{String(a.message??'Inspect the originals to resolve the match.')}</li>)}</ul></div>}
 {page.changes.length?<div className="collection-table-scroll"><table className="collection-table evidence-comparison-table"><caption className="sr-only">Previous and new document values</caption><thead><tr><th>Location and change</th><th>Previous version</th><th>New version</th></tr></thead><tbody>{page.changes.map((change,index)=><tr key={String(change.id??index)}><th scope="row">{location(change.after_locator??change.before_locator)}<small>{statusLabel(String(change.kind??'Changed'))}</small>{Array.isArray(change.fields)&&<small>{change.fields.map(x=>statusLabel(String(x))).join(', ')}</small>}</th><td><div className="evidence-change-value">{readable(change.before)}</div></td><td><div className="evidence-change-value">{readable(change.after)}</div></td></tr>)}</tbody></table></div>:<p className="empty muted">{page.summary.identical_bytes?'The uploaded bytes are identical to the previous version.':'No changes were recorded in the compared data. Read the coverage note before treating this as confirmation.'}</p>}
 <div className="collection-pagination"><span className="caption">{page.total?(page.offset+1)+'–'+Math.min(page.offset+page.changes.length,page.total):'0'} of {page.total.toLocaleString()} changes</span><div><Button variant="outline" size="sm" disabled={loading||page.offset===0} onClick={()=>setOffset(Math.max(0,page.offset-page.limit))}>Previous changes</Button> <Button variant="outline" size="sm" disabled={loading||page.offset+page.limit>=page.total} onClick={()=>setOffset(page.offset+page.limit)}>Next changes</Button></div></div><details><summary>How this comparison matched rows</summary><p className="caption">{readable(page.summary.alignment??'Rows were compared at their original positions.')}</p><p className="caption">{String(page.coverage.interpretation??'Structural differences are observations. They do not approve the financial meaning of a change.')}</p></details></Card></>}
 {canManage&&comparison&&['NEEDS_REVIEW','FAILED'].includes(comparison.status)&&<Card><h2>Review unresolved differences</h2><p className="caption">Open both original versions above and inspect the changes the comparison could not establish. This records an independent review of these exact files; the coverage limits remain visible.</p>{comparison.review&&<p className="caption">A comparison review has been recorded for these versions.</p>}<label className="attestation"><input type="checkbox" checked={attested} disabled={pending} onChange={e=>setAttested(e.target.checked)}/><span>I compared the original versions and reviewed the unresolved differences</span></label><Field id="comparison-review-reason" label="Comparison review notes"><Textarea id="comparison-review-reason" value={reviewReason} disabled={pending} onChange={e=>setReviewReason(e.target.value)}/></Field><Button disabled={pending||!attested||!reviewReason.trim()} onClick={()=>void onChange(()=>api.reviewComparison(collection.id,collection.version,comparison.id,reviewReason.trim())).catch(()=>{})}>Record comparison review</Button></Card>}
 {canManage&&<details className="collection-details"><summary>Identify rows by business keys</summary><Card><p className="caption">For files whose rows move, choose the source columns that uniquely identify a row. Duplicates are flagged for review. These settings apply to version comparisons for that document.</p><form className="collection-form" onSubmit={saveKeys}><Field id="keys-document" label="Document to match"><select id="keys-document" className="input" value={keyDocument} onChange={e=>{setKeyDocument(e.target.value);const doc=docs.find(d=>d.id===e.target.value),source=collection.sources.find(s=>s.id===doc?.current_revision_id);setSheet(source?.media_type==='text/csv'?'csv':'');}}><option value="">Choose a spreadsheet or CSV</option>{docs.filter(d=>collection.sources.find(s=>s.id===d.current_revision_id)?.media_type!=='application/pdf').map(d=><option value={d.id} key={d.id}>{d.title}</option>)}</select></Field><Field id="keys-sheet" label="Worksheet name" help="For a CSV file, use csv."><Input id="keys-sheet" value={sheet} onChange={e=>setSheet(e.target.value)} required/></Field><Field id="keys-columns" label="Columns that identify each row" help="Use source column letters, separated by commas, for example A, C."><Input id="keys-columns" value={keyColumns} onChange={e=>setKeyColumns(e.target.value)} required/></Field><Field id="keys-header" label="Header row"><Input id="keys-header" type="number" min={1} value={headerRow} onChange={e=>setHeaderRow(e.target.value)} required/></Field><Button type="submit" disabled={pending}>Save row matching</Button></form></Card></details>}
 </div>;
}

