import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Alert, Badge, Button, Card, Input, Textarea } from '../../components/ui';
import { Field } from '../../components/closegraph/Field';
import { DownloadLink } from '../../components/closegraph/DocumentPreview';
import { ApiError } from '../../lib/api';
import { canPrepare, canReview, humanize, safeDownloadURL, type Session } from '../../lib/model';
import { CollectionsApi, collectionFile } from './api';
import { DatasetReview } from './DatasetReview';
import { RecipeEditor } from './RecipeEditor';
import { processing, type Collection, type Issue, type Recipe } from './model';
import './collections.css';
type Tab = 'sources'|'recipe'|'output'|'history';
export function CollectionsWorkspace({session,onReports,onLogout,onUnauthorized}:{session:Session;onReports:()=>void;onLogout:()=>void;onUnauthorized:()=>void}){
 const api=useMemo(()=>new CollectionsApi(session.csrf_token),[session.csrf_token]);
 const [list,setList]=useState<Collection[]>([]),[collection,setCollection]=useState<Collection|null>(null),[loading,setLoading]=useState(true),[pending,setPending]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [tab,setTab]=useState<Tab>('sources'),[datasetId,setDatasetId]=useState(''),[issue,setIssue]=useState<Issue|null>(null),[issueFilter,setIssueFilter]=useState('all');
 const [title,setTitle]=useState(''),[fund,setFund]=useState(''),[creating,setCreating]=useState(false),[files,setFiles]=useState<File[]>([]),[reason,setReason]=useState(''),[attested,setAttested]=useState(false),[history,setHistory]=useState<Record<string,unknown>[]>([]),[download,setDownload]=useState<{url:string;filename:string;version:number;manifest_url?:string}|null>(null);
 const currentId=useRef<string|null>(null),busy=useRef(false),live=useRef(true),fileInput=useRef<HTMLInputElement>(null);
 const allowedFunds=(session as Session&{collection_funds?:{fund_id:string}[]}).collection_funds??session.scopes??[],funds=Array.from(new Set(allowedFunds.map(s=>s.fund_id)));
 const prepare=canPrepare(session),reviewer=canReview(session);
 useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 const handleError=useCallback((err:unknown)=>{if(!live.current)return;setError((err as Error).message);if(err instanceof ApiError&&err.status===401)onUnauthorized();},[onUnauthorized]);
 const adopt=useCallback((value:Collection)=>{if(!live.current)return;currentId.current=value.id;setCollection(current=>current?.id===value.id&&current.version>value.version?current:value);setList(items=>items.some(c=>c.id===value.id)?items.map(c=>c.id===value.id?(c.version>value.version?c:value):c):[value,...items]);},[]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);api.list(controller.signal).then(async items=>{if(controller.signal.aborted)return;setList(items);if(items[0]){const detail=await api.get(items[0].id,controller.signal);if(!controller.signal.aborted&&(!currentId.current||currentId.current===items[0].id))adopt(detail);}}).catch(err=>{if(!controller.signal.aborted)handleError(err);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[api,adopt,handleError]);
 useEffect(()=>{if(!collection||!processing(collection))return;const controller=new AbortController(),id=collection.id;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const next=await api.get(id,controller.signal);if(controller.signal.aborted||currentId.current!==id)return;adopt(next);if(processing(next))timer=setTimeout(()=>void poll(),1200);else setNotice('Processing finished. '+humanize(next.status)+'.');}catch(err){if(!controller.signal.aborted)handleError(err);}};timer=setTimeout(()=>void poll(),1200);return()=>{controller.abort();clearTimeout(timer);};},[api,collection?.id,collection?.status,collection?.version,adopt,handleError]);
 useEffect(()=>{if(!collection||tab!=='history')return;const controller=new AbortController();api.history(collection.id,controller.signal).then(events=>{if(!controller.signal.aborted)setHistory(events);}).catch(err=>{if(!controller.signal.aborted)handleError(err);});return()=>controller.abort();},[api,collection?.id,collection?.version,tab,handleError]);
 useEffect(()=>{setAttested(false);setReason("");},[collection?.id,collection?.version]);
 async function select(id:string){if(busy.current)return;setError('');setNotice('');setIssue(null);setDatasetId('');setTab('sources');setLoading(true);currentId.current=id;try{const next=await api.get(id);if(live.current&&currentId.current===id)adopt(next);}catch(err){handleError(err);}finally{if(live.current)setLoading(false);}}
 const mutate=useCallback(async(action:()=>Promise<Collection>)=>{if(busy.current)throw new Error('Wait for the current action to finish.');busy.current=true;setPending(true);setError('');setNotice('');const id=currentId.current;try{const next=await action();if(!live.current||currentId.current!==id)return;adopt(next);setNotice('Revision '+next.version+' saved. '+humanize(next.status)+'.');}catch(err){handleError(err);if(err instanceof ApiError&&err.status===409&&id){try{const next=await api.get(id);if(live.current&&currentId.current===id){adopt(next);setError('This collection changed while you were working. The latest revision is loaded; check it before applying your change again.');}}catch{}}throw err;}finally{busy.current=false;if(live.current)setPending(false);}},[api,adopt,handleError]);
 async function create(event:React.FormEvent){event.preventDefault();const selectedFund=fund||funds[0];if(!title.trim()||!selectedFund){setError('Enter a collection name and choose an authorised fund.');return;}setCreating(true);setError('');try{const next=await api.create(title.trim(),selectedFund);if(live.current){adopt(next);setTitle('');setTab('sources');setDatasetId('');setIssue(null);}}catch(err){handleError(err);}finally{if(live.current)setCreating(false);}}
 async function upload(){if(!collection||!files.length)return;const id=collection.id,batch=[...files];await mutate(async()=>{let next=collection;let uploaded=0;try{for(const file of batch){if(!live.current)break;setNotice('Uploading '+file.name+' ('+(uploaded+1)+' of '+batch.length+')…');const payload=await collectionFile(file);next=await api.get(id);try{next=await api.upload(id,next.version,payload);}catch(err){if(!(err instanceof ApiError&&err.status===409))throw err;next=await api.get(id);next=await api.upload(id,next.version,payload);}uploaded++;if(live.current){adopt(next);setFiles(batch.slice(uploaded));}}if(uploaded===batch.length&&fileInput.current)fileInput.current.value='';return next;}catch(err){throw new Error(uploaded+' of '+batch.length+' files uploaded. '+(err as Error).message);}}).catch(()=>{});}
 async function exportOutput(format:'csv'|'xlsx'){if(!collection||!activeDataset)return;setError('');setPending(true);try{const result=await api.export(collection.id,collection.version,activeDataset.id,format);const safe=safeDownloadURL(result.url);if(!safe)throw new Error('The server returned an unsupported download URL.');const latest=await api.get(collection.id);if(live.current&&currentId.current===collection.id){adopt(latest);setDownload({url:safe,filename:result.filename,version:latest.version,manifest_url:safeDownloadURL(result.manifest_url)??undefined});setNotice('Export verified by reading it back. Download is ready.');}}catch(err){handleError(err);}finally{if(live.current)setPending(false);}}
 function navigateIssue(item:Issue){if(!collection)return;const dataset=collection.datasets.find(d=>d.table_id===item.table_id||d.id===item.table_id)??collection.datasets.find(d=>d.source_id===item.source_id);setIssue(item);if(dataset){setDatasetId(dataset.id);setTab(dataset.kind==='output'?'output':'sources');}else setTab('sources');}
 const datasets=collection?.datasets.filter(d=>d.kind===(tab==='output'?'output':'extraction'))??[],activeDataset=datasets.find(d=>d.id===datasetId)??datasets[0];
 const issues=(collection?.issues??[]).filter(i=>!i.resolved),errors=issues.filter(i=>i.severity==='error'),warnings=issues.filter(i=>i.severity==='warning'),unaccepted=collection?.datasets.filter(d=>d.kind==='extraction'&&!d.accepted).length??0;
 const locked=pending||loading||Boolean(collection&&processing(collection)),visibleIssues=issues.filter(i=>issueFilter==='all'||i.severity===issueFilter);
 const saveRecipe=(recipe:Recipe)=>mutate(()=>api.recipe(collection!.id,collection!.version,recipe));
 const runRecipe=(recipe:Recipe)=>mutate(async()=>{const saved=await api.recipe(collection!.id,collection!.version,recipe);return api.process(saved.id,saved.version);});
 return <div className="collection-workspace"><a className="skip-link" href="#collection-main">Skip to collection</a><header className="topbar"><div className="brand"><span className="brand-mark" aria-hidden/>CloseGraph</div><nav className="collection-product-nav" aria-label="Workspace"><button aria-current="page">Collections</button><button onClick={onReports} disabled={pending}>Reports</button></nav><div className="topbar-actions"><span className="user">{session.username} · {humanize(session.role)}</span><Button variant="outline" disabled={pending} onClick={onLogout}>Sign out</Button></div></header>
 <div className="collection-shell"><aside className="collection-sidebar" aria-label="Collections"><div className="section-head"><h2>Collections</h2><span className="caption">{list.length}</span></div><p className="caption">Source documents → reviewed data → explicit transformations.</p><div className="collection-list">{list.map(item=><button key={item.id} className="collection-list-item" aria-current={collection?.id===item.id?'page':undefined} disabled={pending} onClick={()=>void select(item.id)}><strong>{item.title}</strong><span>{item.fund_id}</span><small>{humanize(item.status)}</small></button>)}{!loading&&!list.length&&<p className="muted">No collections yet.</p>}</div>{prepare&&<form className="collection-create" onSubmit={create}><h3>New collection</h3><Field id="collection-title" label="Name"><Input id="collection-title" value={title} placeholder="Monthly reconciliation" onChange={e=>setTitle(e.target.value)} required disabled={creating||pending}/></Field><Field id="collection-fund" label="Fund"><select className="input" id="collection-fund" value={fund||funds[0]||''} onChange={e=>setFund(e.target.value)} disabled={creating||pending}>{funds.length?funds.map(id=><option value={id} key={id}>{id}</option>):<option value="">No authorised collection fund</option>}</select></Field><Button type="submit" disabled={creating||pending||!funds.length}>{creating?'Creating…':'Create collection'}</Button></form>}</aside>
 <main className="collection-main" id="collection-main"><div className="sr-only" role="status" aria-live="polite">{notice}</div>{error&&<div role="alert"><Alert title="Action needs attention" tone="danger">{error}</Alert></div>}{loading&&!collection&&<p role="status">Loading collections…</p>}{!collection&&!loading&&<Card className="collection-welcome"><div className="collection-eyebrow">Evidence before output</div><h1>Review the data.<br/>Keep the decisions explicit.</h1><p className="muted">Bring together PDFs, spreadsheets and CSV files. Check their extracted tables against the originals, apply reusable rules and release an independently reviewed result.</p><div className="collection-empty-steps"><div><span>01</span><strong>Inspect extraction</strong><p>Original values and source locations stay visible.</p></div><div><span>02</span><strong>Apply your rules</strong><p>Joins, calculations and checks use explicit configuration.</p></div><div><span>03</span><strong>Review & export</strong><p>Release the exact output an independent reviewer approved.</p></div></div>{!prepare&&<p className="caption">A preparer can create a collection in your authorised fund.</p>}</Card>}
 {collection&&<><div className="page-head"><div><div className="collection-eyebrow">{collection.fund_id} · Collection</div><h1>{collection.title}</h1><p>Draft extraction, accepted inputs and reviewed output are separate stages.</p></div><div className="collection-head-status"><Badge tone={collection.status==='APPROVED'?'success':errors.length?'danger':'warning'}>{humanize(collection.status)}</Badge><span className="caption">Revision {collection.version}</span><Button size="sm" variant="outline" disabled={pending} onClick={()=>{const id=collection.id;void api.get(id).then(next=>{if(currentId.current===id)adopt(next);}).catch(handleError);}}>Refresh</Button></div></div>
 <dl className="collection-metrics"><div><dt>Source files</dt><dd>{collection.sources.length}</dd></div><div><dt>Extracted rows</dt><dd>{collection.datasets.filter(d=>d.kind==='extraction').reduce((n,d)=>n+d.row_count,0).toLocaleString()}</dd></div><div><dt>Tables to accept</dt><dd>{unaccepted}</dd></div><div data-alert={errors.length>0}><dt>Blocking issues</dt><dd>{errors.length}</dd></div><div><dt>Review warnings</dt><dd>{warnings.length}</dd></div></dl>
 {processing(collection)&&<p className="collection-callout" role="status">Processing this revision. Results update automatically; review starts when the run finishes.</p>}
 <nav className="collection-tabs" aria-label="Collection stages">{(['sources','recipe','output','history'] as Tab[]).map((value,i)=><button key={value} aria-current={tab===value?'page':undefined} onClick={()=>{setTab(value);setDatasetId('');setIssue(null);}}><span>{String(i+1).padStart(2,'0')}</span>{({sources:'Source review',recipe:'Transformation',output:'Output & release',history:'History'})[value]}</button>)}</nav>
 {tab==='sources'&&<Card className="collection-upload"><div><h2>Source files</h2><p className="caption">PDF, CSV and XLSX. Native spreadsheet readers preserve source cells; PDF extraction is a draft for review.</p></div>{prepare&&<div className="collection-upload-controls"><label className="sr-only" htmlFor="collection-files">Source files to upload</label><Input ref={fileInput} id="collection-files" type="file" multiple accept=".pdf,.csv,.xlsx" disabled={locked} onChange={e=>setFiles(Array.from(e.target.files??[]))}/><Button disabled={locked||!files.length} onClick={()=>void upload()}>Upload {files.length?files.length+' file'+(files.length===1?'':'s'):'files'}</Button></div>}<ul className="collection-source-list">{collection.sources.map(source=><li key={source.id}><div><a href={api.sourceUrl(collection.id,source.id)} target="_blank" rel="noreferrer">{source.filename}</a><span className="caption">{humanize(source.status)}{source.parser?.mode?' · '+String(source.parser.mode):''}</span></div>{source.issues?.map(item=><p className="caption" key={item.id}>{item.message}</p>)}{prepare&&<details className="collection-details"><summary>Re-extract source</summary><p className="caption">A new extraction replaces this source’s current extracted tables and corrections. Original bytes and past revisions remain in history.</p><Button variant="link" disabled={locked} onClick={()=>void mutate(()=>api.process(collection.id,collection.version,{stage:'extract',source_id:source.id})).catch(()=>{})}>Retry extraction of {source.filename}</Button></details>}</li>)}</ul>{!collection.sources.length&&<p className="muted">Add the source files and any reference tables for this workflow.</p>}{prepare&&collection.sources.length>0&&<Button variant="link" disabled={locked} onClick={()=>void mutate(()=>api.process(collection.id,collection.version)).catch(()=>{})}>Process pending sources / rerun recipe</Button>}</Card>}
 {['sources','output'].includes(tab)&&<>{issues.length>0&&<Card className="collection-issues"><div className="section-head"><h2>Issues to investigate</h2><label className="caption">Show <select aria-label="Issue severity" className="collection-inline-select" value={issueFilter} onChange={e=>setIssueFilter(e.target.value)}><option value="all">All issues</option><option value="error">Blocking issues</option><option value="warning">Warnings</option><option value="info">Information</option></select></label></div><ul>{visibleIssues.map(item=><li key={item.id}><button onClick={()=>navigateIssue(item)} aria-pressed={issue?.id===item.id}><Badge tone={item.severity==='error'?'danger':item.severity==='warning'?'warning':'info'}>{humanize(item.severity)}</Badge><span>{item.message}<small>{humanize(item.code)}</small></span><span aria-hidden>↗</span></button></li>)}</ul><p className="caption">Findings come from extraction and checks. Review unflagged rows too: a parser can make errors without flagging them.</p></Card>}
 {datasets.length>0&&<div className="collection-dataset-picker"><label className="label" htmlFor="collection-dataset">{tab==='output'?'Output table':'Extracted table'}</label><select className="input" id="collection-dataset" value={activeDataset?.id??''} onChange={e=>{setDatasetId(e.target.value);setIssue(null);}}>{datasets.map(d=><option key={d.id} value={d.id}>{d.title} · {d.row_count} rows{d.accepted?' · accepted':''}</option>)}</select></div>}
 {activeDataset?<DatasetReview key={activeDataset.id} collection={collection} dataset={activeDataset} api={api} pending={locked} canEdit={prepare} issue={issue} onChange={mutate} onError={handleError}/>:<Card><h2>{tab==='output'?'No output yet':'No extracted tables yet'}</h2><p className="muted">{tab==='output'?'Accept the source tables, configure a recipe and run the transformation to preview its result.':'Processing issues remain visible. A blocked file does not mean its missing values are zero.'}</p>{tab==='output'&&<Button variant="link" onClick={()=>setTab('recipe')}>Open transformation recipe</Button>}</Card>}
 </>}
 {tab==='recipe'&&<RecipeEditor collection={collection} pending={locked} canEdit={prepare} onSave={saveRecipe} onRun={runRecipe}/>}
 {tab==='output'&&activeDataset&&<Card className="collection-release"><h2>Independent review & release</h2><p className="muted">Approval covers this exact output revision. Changed inputs or recipes require fresh processing and review.</p><div className="topbar-actions collection-details">{collection.candidates?.filter(c=>c.dataset_id===activeDataset.id).map(candidate=>{const url=safeDownloadURL(candidate.url);return url?<DownloadLink key={candidate.candidate_id} url={url} label={'Inspect draft '+candidate.format.toUpperCase()}/>:null;})}</div>{collection.review&&<details className="collection-details"><summary>Recorded output decision</summary><pre className="collection-json">{JSON.stringify(collection.review,null,2)}</pre></details>}{reviewer&&<form className="collection-form" onSubmit={e=>{e.preventDefault();if(!reason.trim()||!attested){setError('Enter a review reason and confirm your inspection of this revision.');return;}void mutate(()=>api.review(collection.id,collection.version,'APPROVE',reason.trim())).catch(()=>{});}}><Field id="collection-review-reason" label="Independent review reason"><Textarea id="collection-review-reason" required value={reason} onChange={e=>setReason(e.target.value)} disabled={locked}/></Field><label className="attestation"><input type="checkbox" checked={attested} disabled={locked} onChange={e=>setAttested(e.target.checked)}/><span>I inspected the source evidence, validation findings and exact output for this revision.</span></label><div className="topbar-actions"><Button type="submit" disabled={locked||!attested||collection.status!=='READY_FOR_REVIEW'||errors.length>0}>Approve exact output</Button><Button variant="outline" disabled={locked||!reason.trim()} onClick={()=>void mutate(()=>api.review(collection.id,collection.version,'REJECT',reason.trim())).catch(()=>{})}>Reject output</Button></div></form>}{!reviewer&&collection.status!=='APPROVED'&&<p className="collection-callout">An independent reviewer must sign in and review the output before export becomes available.</p>}
 <details className="collection-details"><summary>Reviewed export configuration</summary><pre className="collection-json">{JSON.stringify(collection.recipe?.export??{formats:['csv','xlsx']},null,2)}</pre><p className="caption">Change output layout in the transformation recipe, then rerun and obtain a new review.</p></details>
 <div className="topbar-actions collection-details"><Button disabled={locked||collection.status!=='APPROVED'||Boolean(activeDataset.stale)||!(collection.recipe?.export?.formats??['csv','xlsx']).includes('csv')} onClick={()=>void exportOutput('csv')}>Export CSV</Button><Button variant="outline" disabled={locked||collection.status!=='APPROVED'||Boolean(activeDataset.stale)||!(collection.recipe?.export?.formats??['csv','xlsx']).includes('xlsx')} onClick={()=>void exportOutput('xlsx')}>Export XLSX</Button>{download&&download.version===collection.version&&<><DownloadLink url={download.url} label={'Download '+download.filename}/>{download.manifest_url&&<DownloadLink url={download.manifest_url} label="Download source-to-output manifest"/>}</>}</div></Card>}
 {tab==='history'&&<Card><h2>Revision and decision history</h2><p className="caption">Original observations, corrections, acceptance and output decisions remain recorded. Earlier approvals do not carry across changed data.</p>{history.length?history.map((event,index)=><div className="record" key={String(event.id??index)}><strong>{humanize(String(event.action??event.event??event.type??'Recorded event'))}</strong><p className="caption">{String(event.actor??event.actor_id??'')} {event.version?'· revision '+String(event.version):''} {String(event.timestamp??event.created_at??event.at??'')}</p>{Boolean(event.reason)&&<p>{String(event.reason)}</p>}<details><summary>Event details</summary><pre className="collection-json">{JSON.stringify(event,null,2)}</pre></details></div>):<p className="empty muted">No history events were returned.</p>}<details className="collection-details"><summary>Recorded collection metrics</summary><pre className="collection-json">{JSON.stringify(collection.summary,null,2)}</pre></details></Card>}
 </>}
 </main></div><footer className="footer"><span>Source evidence and explicit rules. Every revision is reviewable.</span><span>Draft extraction ≠ financial approval</span></footer></div>;
}
