import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Alert, Badge, Button, Card, Input, Textarea } from '../../components/ui';
import { Field } from '../../components/closegraph/Field';
import { DownloadLink } from '../../components/closegraph/DocumentPreview';
import { ApiError } from '../../lib/api';
import { canPrepare, canReview, humanize, safeDownloadURL, type Session } from '../../lib/model';
import { CollectionsApi, collectionFile } from './api';
import { DatasetReview } from './DatasetReview';
import { RecipeEditor } from './RecipeEditor';
import { DocumentsPanel, type UploadOptions } from './DocumentsPanel';
import { TasksPanel } from './TasksPanel';
import { ChangesPanel } from './ChangesPanel';
import { RequirementsPanel } from './RequirementsPanel';
import { MembersPanel } from './MembersPanel';
import { SimpleMapping } from './SimpleMapping';
import { documentsFor, statusLabel } from './presentation';
import { processing, type Collection, type Issue, type Recipe } from './model';
import './collections.css';
type Tab='overview'|'documents'|'tasks'|'changes'|'outputs';
const tabLabels:Record<Tab,string>={overview:'Overview',documents:'Documents',tasks:'Tasks',changes:'Review changes',outputs:'Outputs'};
export function CollectionsWorkspace({session,onReports,onLogout,onUnauthorized}:{session:Session;onReports:()=>void;onLogout:()=>void;onUnauthorized:()=>void}){
 const api=useMemo(()=>new CollectionsApi(session.csrf_token),[session.csrf_token]);
 const [list,setList]=useState<Collection[]>([]),[collection,setCollection]=useState<Collection|null>(null),[loading,setLoading]=useState(true),[pending,setPending]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [tab,setTab]=useState<Tab>(session.role.toLowerCase()==='investor'?'tasks':'overview'),[datasetId,setDatasetId]=useState(''),[issue,setIssue]=useState<Issue|null>(null),[focusDocument,setFocusDocument]=useState('');
 const [title,setTitle]=useState(''),[fund,setFund]=useState(''),[creating,setCreating]=useState(false),[reason,setReason]=useState(''),[attested,setAttested]=useState(false),[history,setHistory]=useState<Record<string,unknown>[]>([]),[download,setDownload]=useState<{url:string;filename:string;version:number;manifest_url?:string}|null>(null);
 const currentId=useRef<string|null>(null),busy=useRef(false),live=useRef(true),uploadKeys=useRef(new WeakMap<File,string>()),uploadedFiles=useRef(new WeakSet<File>());
 const allowedFunds=session.collection_funds??session.scopes??[],funds=Array.from(new Set(allowedFunds.map(s=>s.fund_id)));
 const restricted=collection?.access?.restricted??session.role.toLowerCase()==='investor',prepare=collection?.access?.can_prepare??canPrepare(session),reviewer=collection?.access?.can_review??canReview(session),manage=collection?.access?.can_manage??['administrator','account_manager','fund_manager'].includes(session.role.toLowerCase()),canCreate=canPrepare(session)||['account_manager','fund_manager'].includes(session.role.toLowerCase());
 useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 const handleError=useCallback((err:unknown)=>{if(!live.current)return;setError((err as Error).message);if(err instanceof ApiError&&err.status===401)onUnauthorized();},[onUnauthorized]);
 const adopt=useCallback((value:Collection)=>{if(!live.current)return;currentId.current=value.id;setCollection(current=>current?.id===value.id&&current.version>value.version?current:value);setList(items=>items.some(c=>c.id===value.id)?items.map(c=>c.id===value.id?(c.version>value.version?c:value):c):[value,...items]);},[]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);api.list(controller.signal).then(async items=>{if(controller.signal.aborted)return;setList(items);if(items[0]){const detail=await api.get(items[0].id,controller.signal);if(!controller.signal.aborted&&(!currentId.current||currentId.current===items[0].id))adopt(detail);}}).catch(err=>{if(!controller.signal.aborted)handleError(err);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[api,adopt,handleError]);
 useEffect(()=>{if(restricted&&!['tasks','documents'].includes(tab))setTab('tasks');},[restricted,tab]);
 useEffect(()=>{if(!collection||!processing(collection))return;const controller=new AbortController(),id=collection.id;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const next=await api.get(id,controller.signal);if(controller.signal.aborted||currentId.current!==id)return;adopt(next);if(processing(next))timer=setTimeout(()=>void poll(),1200);else setNotice('Document processing finished. '+statusLabel(next.status)+'.');}catch(err){if(!controller.signal.aborted)handleError(err);}};timer=setTimeout(()=>void poll(),1200);return()=>{controller.abort();clearTimeout(timer);};},[api,collection?.id,collection?.status,collection?.version,adopt,handleError]);
 useEffect(()=>{if(!collection||tab!=='overview'||restricted)return;const controller=new AbortController();api.history(collection.id,controller.signal).then(events=>{if(!controller.signal.aborted)setHistory(events);}).catch(err=>{if(!controller.signal.aborted)handleError(err);});return()=>controller.abort();},[api,collection?.id,collection?.version,tab,restricted,handleError]);
 useEffect(()=>{setAttested(false);setReason('');},[collection?.id,collection?.version]);
 async function select(id:string){if(busy.current)return;setError('');setNotice('');setIssue(null);setDatasetId('');setFocusDocument('');setTab(restricted?'tasks':'overview');setLoading(true);currentId.current=id;try{const next=await api.get(id);if(live.current&&currentId.current===id)adopt(next);}catch(err){handleError(err);}finally{if(live.current)setLoading(false);}}
 const mutate=useCallback(async(action:()=>Promise<Collection>)=>{if(busy.current)throw new Error('Wait for the current action to finish.');busy.current=true;setPending(true);setError('');setNotice('');const id=currentId.current;try{const next=await action();if(!live.current||currentId.current!==id)return;adopt(next);setNotice('Changes saved. '+statusLabel(next.status)+'.');}catch(err){handleError(err);if(err instanceof ApiError&&err.status===409&&id){try{const next=await api.get(id);if(live.current&&currentId.current===id){adopt(next);setError('This collection changed while you were working. The latest revision is loaded; check it before applying your change again.');}}catch{}}throw err;}finally{busy.current=false;if(live.current)setPending(false);}},[api,adopt,handleError]);
 async function create(event:React.FormEvent){event.preventDefault();const selectedFund=fund||funds[0];if(!title.trim()||!selectedFund){setError('Enter a collection name and choose an authorised fund.');return;}setCreating(true);setError('');try{const next=await api.create(title.trim(),selectedFund);if(live.current){adopt(next);setTitle('');setTab('documents');setDatasetId('');setIssue(null);}}catch(err){handleError(err);}finally{if(live.current)setCreating(false);}}
 async function upload(files:File[],options:UploadOptions){if(!collection||!files.length)return;const id=collection.id,batch=[...files];await mutate(async()=>{let next=collection,uploaded=0;try{for(const file of batch){if(!live.current)break;if(uploadedFiles.current.has(file)){uploaded++;continue;}setNotice('Uploading '+file.name+' ('+(uploaded+1)+' of '+batch.length+')…');const payload=await collectionFile(file),idempotency_key=uploadKeys.current.get(file)??crypto.randomUUID();uploadKeys.current.set(file,idempotency_key);next=await api.get(id);next=await api.upload(id,next.version,payload,{...options,idempotency_key});uploaded++;uploadedFiles.current.add(file);if(live.current)adopt(next);}return next;}catch(err){throw new Error(uploaded+' of '+batch.length+' files uploaded. '+(err as Error).message);}});}
 async function exportOutput(format:'csv'|'xlsx'){if(!collection||!activeDataset)return;setError('');setPending(true);try{const result=await api.export(collection.id,collection.version,activeDataset.id,format);const safe=safeDownloadURL(result.url);if(!safe)throw new Error('The server returned an unsupported download URL.');const latest=await api.get(collection.id);if(live.current&&currentId.current===collection.id){adopt(latest);setDownload({url:safe,filename:result.filename,version:latest.version,manifest_url:safeDownloadURL(result.manifest_url)??undefined});setNotice('Approved download is ready.');}}catch(err){handleError(err);}finally{if(live.current)setPending(false);}}
 function openDocument(id:string){setFocusDocument(id);setIssue(null);setTab('documents');}
 function navigateIssue(item:Issue){if(!collection)return;setIssue(item);const dataset=collection.datasets.find(d=>d.table_id===item.table_id||d.id===item.table_id),document=documentsFor(collection).find(d=>d.revisions.some(r=>(typeof r==='string'?r:r.source_id)===(dataset?.source_id??item.source_id)));if(document)setFocusDocument(document.id);if(dataset?.kind==='output'){setDatasetId(dataset.id);setTab('outputs');}else setTab('documents');}
 const outputs=collection?.datasets.filter(d=>d.kind==='output')??[],activeDataset=outputs.find(d=>d.id===datasetId)??outputs[0],issues=(collection?.issues??[]).filter(i=>!i.resolved),errors=issues.filter(i=>i.severity==='error'),tasks=(collection?.tasks??[]).filter(t=>t.active!==false&&t.status!=='resolved'),checks=collection?.check_results??[];
 const locked=pending||loading||Boolean(collection&&processing(collection));
 const saveRecipe=(recipe:Recipe)=>mutate(()=>api.recipe(collection!.id,collection!.version,recipe));
 const runRecipe=(recipe:Recipe)=>mutate(async()=>{const saved=await api.recipe(collection!.id,collection!.version,recipe);return api.process(saved.id,saved.version);});
 const visibleTabs:Tab[]=restricted?['tasks','documents']:['overview','documents','tasks','changes','outputs'];
 return <div className="collection-workspace"><a className="skip-link" href="#collection-main">Skip to collection</a><header className="topbar"><div className="brand"><span className="brand-mark" aria-hidden/>CloseGraph</div><nav className="collection-product-nav" aria-label="Workspace"><button aria-current="page">{restricted?'Your requests':'Collections'}</button>{!restricted&&<button onClick={onReports} disabled={pending}>Reports</button>}</nav><div className="topbar-actions"><span className="user">{session.username} · {humanize(session.role)}</span><Button variant="outline" disabled={pending} onClick={onLogout}>Sign out</Button></div></header>
 <div className="collection-shell"><aside className="collection-sidebar" aria-label="Collections"><div className="section-head"><h2>{restricted?'Shared work':'Collections'}</h2><span className="caption">{list.length}</span></div><p className="caption">{restricted?'Your requests and shared evidence.':'Documents, responsibilities and reviewed outputs.'}</p><div className="collection-list">{list.map(item=><button key={item.id} className="collection-list-item" aria-current={collection?.id===item.id?'page':undefined} disabled={pending} onClick={()=>void select(item.id)}><strong>{item.title}</strong><small>{statusLabel(item.status)}</small></button>)}{!loading&&!list.length&&<p className="muted">{restricted?'No requests have been shared yet.':'No collections yet.'}</p>}</div>{canCreate&&!restricted&&<form className="collection-create" onSubmit={create}><h3>New collection</h3><Field id="collection-title" label="Name"><Input id="collection-title" value={title} placeholder="Monthly reconciliation" onChange={e=>setTitle(e.target.value)} required disabled={creating||pending}/></Field><Field id="collection-fund" label="Fund"><select className="input" id="collection-fund" value={fund||funds[0]||''} onChange={e=>setFund(e.target.value)} disabled={creating||pending}>{funds.length?funds.map(id=><option value={id} key={id}>{id}</option>):<option value="">No authorised collection fund</option>}</select></Field><Button type="submit" disabled={creating||pending||!funds.length}>{creating?'Creating…':'Create collection'}</Button></form>}</aside>
 <main className="collection-main" id="collection-main">{notice&&<p className="caption evidence-notice" role="status" aria-live="polite">{notice}</p>}{error&&<div role="alert"><Alert title="Action needs attention" tone="danger">{error}</Alert></div>}{loading&&!collection&&<p role="status">Loading collections…</p>}{!collection&&!loading&&<Card className="collection-welcome"><div className="collection-eyebrow">{restricted?'Shared requests':'Evidence before output'}</div><h1>{restricted?'Your requests will appear here.':'Review the data. Keep the decisions clear.'}</h1><p className="muted">{restricted?'A manager will share a request when your response is needed.':'Bring together documents, agree the required checks, and give each unresolved item an owner. Review changes before releasing the final output.'}</p></Card>}
 {collection&&<><div className="page-head"><div><div className="collection-eyebrow">{restricted?'Your shared workspace':'Collection'}</div><h1>{collection.title}</h1><p>{restricted?'Respond to your requests and inspect the evidence shared with you.':'See what is ready, what changed and who needs to act next.'}</p></div><div className="collection-head-status"><Badge tone={collection.status==='APPROVED'?'success':errors.length?'danger':'warning'}>{statusLabel(collection.status)}</Badge><Button size="sm" variant="outline" disabled={pending} onClick={()=>{const id=collection.id;void api.get(id).then(next=>{if(currentId.current===id)adopt(next);}).catch(handleError);}}>Refresh</Button></div></div>
 {!restricted&&<dl className="collection-metrics"><div><dt>Documents</dt><dd>{documentsFor(collection).length}</dd></div><div><dt>Open tasks</dt><dd>{tasks.length}</dd></div><div><dt>Checks passed</dt><dd>{checks.filter(c=>c.status==='PASS').length} <small>/ {collection.requirements?.length??0}</small></dd></div><div data-alert={errors.length>0}><dt>Needs attention</dt><dd>{errors.length}</dd></div><div><dt>Document updates</dt><dd>{collection.comparisons?.length??0}</dd></div></dl>}
 {processing(collection)&&<p className="collection-callout" role="status">Reading this version. Results will update automatically.</p>}<nav className="collection-tabs" aria-label="Collection navigation">{visibleTabs.map(value=><button key={value} aria-current={tab===value?'page':undefined} onClick={()=>{setTab(value);setIssue(null);}}>{tabLabels[value]}{value==='tasks'&&tasks.length>0?<span className="evidence-task-count">{tasks.length}</span>:null}</button>)}</nav>
 {tab==='overview'&&!restricted&&<div className="stack"><div className="evidence-overview-grid"><Card><h2>What needs to happen next?</h2>{!collection.sources.length?<><p>Add the documents needed for this collection, then define the checks your team must complete.</p><Button onClick={()=>setTab('documents')}>Add documents</Button></>:tasks.length?<><p>{tasks.length} task{tasks.length===1?' needs':'s need'} attention. Review the requests and make sure each has an owner.</p><Button onClick={()=>setTab('tasks')}>View open tasks</Button></>:<><p>{collection.status==='APPROVED'?'The reviewed output is ready to download.':'Review the document data and run the required checks before preparing output.'}</p><Button onClick={()=>setTab(collection.status==='APPROVED'?'outputs':'documents')}>{collection.status==='APPROVED'?'Open approved outputs':'Review document data'}</Button></>}</Card><Card><h2>Recent updates</h2>{collection.notifications?.length?collection.notifications.slice(-5).reverse().map((n,i)=><div className="record" key={String(n.id??i)}><strong>{String(n.title??'Request update')}</strong>{Boolean(n.message)&&<p>{String(n.message)}</p>}<Button variant="link" onClick={()=>setTab('tasks')}>View tasks</Button></div>):<p className="muted">New requests and verification updates will appear here.</p>}</Card></div>
 <RequirementsPanel key={collection.id} collection={collection} api={api} pending={locked} canManage={manage} onChange={mutate} onDocument={openDocument}/>
 {issues.length>0&&<Card className="collection-issues"><h2>Document findings</h2><ul>{issues.map(item=><li key={item.id}><button onClick={()=>navigateIssue(item)}><Badge tone={item.severity==='error'?'danger':item.severity==='warning'?'warning':'info'}>{item.severity==='error'?'Action needed':item.severity==='warning'?'Check this':'For review'}</Badge><span>{item.message}</span><span aria-hidden>↗</span></button></li>)}</ul><p className="caption">A finding helps direct review. Unflagged values can still need correction.</p></Card>}
 {manage&&<details className="collection-details"><summary>Manage people and sharing</summary><MembersPanel key={collection.id} collection={collection} api={api} pending={locked} onChange={mutate}/></details>}
 <details className="collection-details"><summary>Activity and decisions</summary><Card>{history.length?history.map((event,index)=><div className="record" key={String(event.id??index)}><strong>{statusLabel(String(event.action??event.event??event.type??'Recorded event'))}</strong>{Boolean(event.reason)&&<p>{String(event.reason)}</p>}<p className="caption">{String(event.timestamp??event.created_at??event.at??'')}</p></div>):<p className="muted">No activity has been recorded yet.</p>}</Card></details></div>}
 {tab==='documents'&&<DocumentsPanel key={collection.id} collection={collection} api={api} pending={locked} canEdit={prepare} restricted={restricted} issue={issue} focusDocument={focusDocument} onChange={mutate} onError={handleError} onUpload={upload}/>}
 {tab==='tasks'&&<TasksPanel key={collection.id} collection={collection} api={api} pending={locked} actor={collection.access?.actor_id??session.username} canFlag={prepare||manage} restricted={restricted} onChange={mutate} onUpload={upload} onDocument={openDocument}/>}
 {tab==='changes'&&!restricted&&<ChangesPanel key={collection.id} collection={collection} api={api} pending={locked} canManage={manage} onChange={mutate} onError={handleError}/>}
 {tab==='outputs'&&!restricted&&<div className="stack"><SimpleMapping key={collection.id} collection={collection} pending={locked} canEdit={prepare} onSave={saveRecipe} onRun={runRecipe}/><details className="collection-details"><summary>Advanced transformation settings</summary><RecipeEditor collection={collection} pending={locked} canEdit={prepare} onSave={saveRecipe} onRun={runRecipe}/></details>{outputs.length>0&&<Field id="collection-output" label="Output to inspect"><select id="collection-output" className="input" value={activeDataset?.id??''} onChange={e=>setDatasetId(e.target.value)}>{outputs.map(d=><option key={d.id} value={d.id}>{d.title} · {d.row_count} rows</option>)}</select></Field>}{activeDataset?<DatasetReview key={activeDataset.id} collection={collection} dataset={activeDataset} api={api} pending={locked} canEdit={false} issue={issue} onChange={mutate} onError={handleError}/>:<Card><h2>No output yet</h2><p className="muted">Check the source data, choose the output fields and create an output to inspect here.</p></Card>}
 {activeDataset&&<Card className="collection-release"><h2>Independent review & release</h2><p className="muted">Approval covers this exact output revision. Changed inputs or recipes require fresh processing and review.</p><div className="topbar-actions collection-details">{collection.candidates?.filter(c=>c.dataset_id===activeDataset.id).map(candidate=>{const url=safeDownloadURL(candidate.url);return url?<DownloadLink key={candidate.candidate_id} url={url} label={'Inspect draft '+candidate.format.toUpperCase()}/>:null;})}</div>{collection.review&&<details className="collection-details"><summary>Recorded output decision</summary><pre className="collection-json">{JSON.stringify(collection.review,null,2)}</pre></details>}{reviewer&&<form className="collection-form" onSubmit={e=>{e.preventDefault();if(!reason.trim()||!attested){setError('Enter a review reason and confirm your inspection of this revision.');return;}void mutate(()=>api.review(collection.id,collection.version,'APPROVE',reason.trim())).catch(()=>{});}}><Field id="collection-review-reason" label="Independent review reason"><Textarea id="collection-review-reason" required value={reason} onChange={e=>setReason(e.target.value)} disabled={locked}/></Field><label className="attestation"><input type="checkbox" checked={attested} disabled={locked} onChange={e=>setAttested(e.target.checked)}/><span>I inspected the source evidence, validation findings and exact output for this revision.</span></label><div className="topbar-actions"><Button type="submit" disabled={locked||!attested||collection.status!=='READY_FOR_REVIEW'||errors.length>0}>Approve exact output</Button><Button variant="outline" disabled={locked||!reason.trim()} onClick={()=>void mutate(()=>api.review(collection.id,collection.version,'REJECT',reason.trim())).catch(()=>{})}>Reject output</Button></div></form>}{!reviewer&&collection.status!=='APPROVED'&&<p className="collection-callout">An independent account manager must sign in and review the output before export becomes available.</p>}
 <details className="collection-details"><summary>Reviewed export configuration</summary><pre className="collection-json">{JSON.stringify(collection.recipe?.export??{formats:['csv','xlsx']},null,2)}</pre><p className="caption">Change output layout in the transformation recipe, then rerun and obtain a new review.</p></details>
 <div className="topbar-actions collection-details"><Button disabled={locked||collection.status!=='APPROVED'||Boolean(activeDataset.stale)||!(collection.recipe?.export?.formats??['csv','xlsx']).includes('csv')} onClick={()=>void exportOutput('csv')}>Export CSV</Button><Button variant="outline" disabled={locked||collection.status!=='APPROVED'||Boolean(activeDataset.stale)||!(collection.recipe?.export?.formats??['csv','xlsx']).includes('xlsx')} onClick={()=>void exportOutput('xlsx')}>Export XLSX</Button>{download&&download.version===collection.version&&<><DownloadLink url={download.url} label={'Download '+download.filename}/>{download.manifest_url&&<DownloadLink url={download.manifest_url} label="Download source-to-output manifest"/>}</>}</div></Card>}
 </div>}
 </>}
 </main></div><footer className="footer"><span>Source evidence and clear decisions. Every version is reviewable.</span><span>Document review before output approval</span></footer></div>;
}
