import { useEffect, useState } from 'react';
import { Alert, Badge, Button, Card, Textarea } from '../../components/ui';
import { Field } from '../../components/closegraph/Field';
import { PdfEvidence } from '../../components/closegraph/PdfEvidence';
function evidenceLocation(locator:Record<string,unknown>|undefined){if(!locator)return 'Location unavailable';if(locator.original_page??locator.page)return 'Page '+String(locator.original_page??locator.page)+(locator.bbox?' · Highlighted source region':'');if(locator.sheet??locator.sheet_name)return String(locator.sheet??locator.sheet_name)+(locator.cell??locator.coordinate?' · '+String(locator.cell??locator.coordinate):'');if(locator.row)return 'Row '+String(locator.row)+(locator.column?' · Column '+String(locator.column):'');return 'Inspect the original document';}
import type { CollectionsApi } from './api';
import type { Collection, DataRow, Dataset, Edit, Issue, RowPage } from './model';
interface Props { collection:Collection;dataset:Dataset;api:CollectionsApi;pending:boolean;canEdit:boolean;issue:Issue|null;onChange:(action:()=>Promise<Collection>)=>Promise<void>;onError:(error:unknown)=>void }
export function DatasetReview({collection,dataset,api,pending,canEdit,issue,onChange,onError}:Props){
 const [page,setPage]=useState<RowPage|null>(null),[offset,setOffset]=useState(0),[loading,setLoading]=useState(false),[loadError,setLoadError]=useState('');
 const [selected,setSelected]=useState<{row:string;column:string}|null>(null),[checked,setChecked]=useState<string[]>([]),[op,setOp]=useState<Edit['op']>('set_cell'),[value,setValue]=useState(''),[reason,setReason]=useState(''),[localError,setLocalError]=useState('');
 const [split,setSplit]=useState('[]'),[jump,setJump]=useState<string|undefined>(undefined),[citation,setCitation]=useState('');
 const row=page?.rows.find(r=>r.row_id===selected?.row),column=page?.columns.find(c=>c.key===selected?.column);
 const locator=row?.locators?.[selected?.column??''],source=collection.sources.find(s=>s.id===dataset.source_id),download=source?api.sourceUrl(collection.id,source.id):null;
 const editable=canEdit&&dataset.kind==='extraction'&&!pending;
 const relevantIssue=issue?.table_id===dataset.table_id||issue?.table_id===dataset.id?issue:null;
 useEffect(()=>{setOffset(0);setSelected(null);setChecked([]);setReason('');setLocalError('');},[dataset.id]);
 useEffect(()=>{setJump(relevantIssue?.row_id);setOffset(0);},[relevantIssue?.id]);
 useEffect(()=>{
  const controller=new AbortController();setLoading(true);setLoadError('');
  api.rows(collection.id,dataset.id,offset,50,controller.signal,jump).then(result=>{if(controller.signal.aborted)return;setPage(result);if(jump&&relevantIssue?.row_id){const match=result.rows.find(r=>r.row_id===relevantIssue.row_id);if(match){const key=relevantIssue.column_key??result.columns[0]?.key;if(key){setSelected({row:match.row_id,column:key});setValue(match.values[key]??'');}}}}).catch(error=>{if(!controller.signal.aborted){setLoadError((error as Error).message);onError(error);}}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
  return()=>controller.abort();
 },[api,collection.id,collection.version,dataset.id,offset,jump,relevantIssue?.id,onError]);
 function selectCell(item:DataRow,key:string){setSelected({row:item.row_id,column:key});setValue(item.values[key]??'');setOp('set_cell');setLocalError('');setCitation(JSON.stringify({original_page:item.locators?.[key]?.original_page??null,processed_page:item.locators?.[key]?.processed_page??null,bbox:item.locators?.[key]?.bbox??null,coordinate_system:'normalised-0-1',apply_to:'cell'},null,2));setSplit(JSON.stringify([item.values,Object.fromEntries((page?.columns??[]).map(c=>[c.key,null]))],null,2));}
 async function save(event:React.FormEvent){event.preventDefault();setLocalError('');if(!reason.trim()){setLocalError('Explain the source evidence for this correction.');return;}let edit:Edit;
  try{
   if(op==='mark_unresolved')edit={op,message:value.trim()||reason.trim()};
   else if(op==='resolve_issue'){if(!relevantIssue)throw new Error('Select an issue to resolve.');edit={op,issue_id:relevantIssue.id,reason:reason.trim()};}
   else if(op==='merge_rows'){if(checked.length<2)throw new Error('Select at least two rows to merge.');edit={op,row_ids:checked};}
   else {if(!row||!column)throw new Error('Select a source cell first.');
    if(op==='set_pdf_citation'){const data=JSON.parse(citation);if(!Number.isInteger(data.original_page)||data.original_page<1||(data.processed_page!=null&&(!Number.isInteger(data.processed_page)||data.processed_page<1))||!Array.isArray(data.bbox)||data.bbox.length!==4||data.bbox.some((n:unknown)=>typeof n!=='number'||!Number.isFinite(n)||n<0||n>1)||data.bbox[0]>=data.bbox[2]||data.bbox[1]>=data.bbox[3]||data.coordinate_system!=='normalised-0-1'||!['cell','block'].includes(data.apply_to))throw new Error('Enter actual page numbers and a normalised [left, top, right, bottom] box from the source.');edit={op,row_id:row.row_id,column_key:column.key,original_page:data.original_page,...(data.processed_page==null?{}:{processed_page:data.processed_page}),bbox:data.bbox,coordinate_system:'normalised-0-1',apply_to:data.apply_to};}
    else if(op==='set_cell')edit={op,row_id:row.row_id,column_key:column.key,value};
    else if(op==='rename_column'){if(!value.trim())throw new Error('Enter a header label.');edit={op,column_key:column.key,label:value.trim()};}
    else if(op==='exclude_row')edit={op,row_id:row.row_id,reason:reason.trim()};
    else if(op==='set_header')edit={op,row_id:row.row_id};
    else if(op==='split_row'){const values:unknown=JSON.parse(split);if(!Array.isArray(values)||values.length<2||values.some(v=>!v||typeof v!=='object'||Array.isArray(v)||Object.values(v).some(x=>x!==null&&typeof x!=='string')))throw new Error('Provide at least two objects with column keys and text or null values.');edit={op,row_id:row.row_id,values};}
    else throw new Error('Choose a correction.');
   }
   await onChange(()=>api.edit(collection.id,collection.version,dataset.id,[edit],reason.trim()));setReason('');setChecked([]);
  }catch(error){setLocalError((error as Error).message);}
 }
 return <div className="collection-review-grid"><Card className="collection-dataset"><div className="section-head"><div><h2>{dataset.title}</h2><p className="caption">{dataset.kind==='output'?'Transformed output':'Extracted table'} · {dataset.row_count.toLocaleString()} rows · revision {dataset.version}</p></div><Badge tone={dataset.accepted?'success':'warning'}>{dataset.kind==='output'?'Output preview':dataset.accepted?'Extraction accepted':'Review extraction'}</Badge></div>
 {Boolean(dataset.metadata?.suggested_header_row_id)&&<p className="collection-callout">A possible header row was detected. Review it against the source, then select a cell in that row and choose “Use selected row as headers”. The original row remains in history.</p>}
 {dataset.stale&&<Alert title="This output is stale" tone="warning">An input or rule changed. Recompute and obtain a new review before exporting.</Alert>}
 {loadError&&<p role="alert">{loadError}</p>}{loading&&<p role="status">Loading table rows…</p>}
 {page&&<><div className="collection-table-scroll" aria-busy={loading}><table className="collection-table"><caption className="sr-only">{dataset.title}. Select a cell to inspect its source and correct its value.</caption><thead><tr>{editable&&<th scope="col"><span className="sr-only">Select row for merge</span></th>}<th scope="col">Row</th>{page.columns.map(c=><th key={c.key} scope="col">{c.label}</th>)}</tr></thead><tbody>{page.rows.map((item,index)=><tr key={item.row_id} data-selected={item.row_id===selected?.row} data-excluded={item.excluded}>{editable&&<td><input type="checkbox" aria-label={'Select row '+(page.offset+index+1)} checked={checked.includes(item.row_id)} onChange={e=>setChecked(values=>e.target.checked?[...values,item.row_id]:values.filter(id=>id!==item.row_id))}/></td>}<th scope="row">{page.offset+index+1}{item.excluded&&<small>Excluded</small>}</th>{page.columns.map(c=><td key={c.key}><button type="button" className="collection-cell" aria-label={c.label+', row '+(page.offset+index+1)+': '+(item.values[c.key]??'empty')} aria-pressed={selected?.row===item.row_id&&selected.column===c.key} onClick={()=>selectCell(item,c.key)}>{item.values[c.key]===null||item.values[c.key]===undefined?<span className="muted">Empty</span>:item.values[c.key]===''?<span className="muted">Empty text</span>:item.values[c.key]}{relevantIssue?.row_id===item.row_id&&(!relevantIssue.column_key||relevantIssue.column_key===c.key)&&<span className="collection-cell-flag" aria-label="Selected issue">!</span>}</button></td>)}</tr>)}</tbody></table>{page.rows.length===0&&<p className="empty muted">This table contains no rows. Inspect the original and extraction issues.</p>}</div><div className="collection-pagination"><span className="caption">{page.total?`${page.offset+1}–${Math.min(page.offset+page.rows.length,page.total)}`:'0'} of {page.total.toLocaleString()} rows</span><div><Button variant="outline" size="sm" disabled={loading||page.offset===0} onClick={()=>{setJump(undefined);setOffset(Math.max(0,page.offset-page.limit));}}>Previous rows</Button> <Button variant="outline" size="sm" disabled={loading||page.offset+page.limit>=page.total} onClick={()=>{setJump(undefined);setOffset(page.offset+page.limit);}}>Next rows</Button></div></div></>}
 {dataset.kind==='extraction'&&<div className="collection-accept"><p className="caption">Acceptance records that you checked this extraction revision. Financial checks and independent output review happen later.</p><Button disabled={!editable||dataset.accepted} onClick={()=>void onChange(()=>api.accept(collection.id,collection.version,dataset.id)).catch(()=>{})}>{dataset.accepted?'Extraction accepted':'Accept this extraction'}</Button></div>}
 </Card><div className="stack collection-inspector"><Card><div className="section-head"><h2>Source & value</h2>{download&&<a href={download} target="_blank" rel="noreferrer">Open original ↗</a>}</div>{selected&&row&&column?<><dl className="metadata"><div><dt>Current value · {column.label}</dt><dd className="collection-value">{row.values[column.key]??'Empty / null'}</dd></div><div><dt>Original extracted value</dt><dd>{row.raw_values&&column.key in row.raw_values?String(row.raw_values[column.key]??'Empty / null'):'No separate raw value recorded; inspect the source.'}</dd></div><div><dt>Source location</dt><dd>{evidenceLocation(locator)}</dd>{row.source_locations?.[column.key]?.map((location,index)=><dd key={index}>{evidenceLocation(location)}</dd>)}</div>{Boolean(row.formulas?.[column.key])&&<div><dt>Original formula (not recalculated)</dt><dd>{String(row.formulas?.[column.key])}</dd></div>}</dl>{source?.media_type==='application/pdf'&&download&&locator&&<><p className="caption collection-region-note">The highlight uses the parser’s cited region. It may cover a table or block rather than this individual cell.</p><PdfEvidence url={download} source={{source_id:source.id,document_name:source.filename,locator}}/></>}{Boolean(row.lineage)&&<details><summary>Transformation lineage</summary><pre className="collection-json">{JSON.stringify(row.lineage,null,2)}</pre></details>}</>:<p className="muted">Select any table cell to inspect its original value and source location. Unflagged rows are available for review too.</p>}{source&&<details className="collection-details"><summary>Extraction coverage & parser</summary><pre className="collection-json">{JSON.stringify({parser:source.parser??{},coverage:source.coverage??{}},null,2)}</pre><p className="caption">Coverage and provider confidence describe extraction; they do not establish accuracy.</p></details>}</Card>
 {dataset.kind==='extraction'&&canEdit&&<Card><h2>Correct or flag extraction</h2><form onSubmit={save} className="collection-form"><Field id="collection-edit-operation" label="Action"><select id="collection-edit-operation" className="input" value={op} disabled={pending} onChange={e=>{const action=e.target.value as Edit['op'];setOp(action);if(action==='rename_column')setValue(column?.label??'');else if(action==='set_cell')setValue(row?.values[column?.key??'']??'');else if(action==='mark_unresolved')setValue('');}}><option value="set_cell">Correct selected value</option>{source?.media_type==='application/pdf'&&<option value="set_pdf_citation">Correct selected PDF citation</option>}<option value="rename_column">Rename selected column</option><option value="set_header">Use selected row as headers</option><option value="exclude_row">Exclude selected row</option><option value="split_row">Split selected row</option><option value="merge_rows">Merge checked rows</option><option value="mark_unresolved">Mark table unresolved</option>{relevantIssue&&<option value="resolve_issue">Resolve selected review issue</option>}</select></Field>
 {['set_cell','rename_column','mark_unresolved'].includes(op)&&<Field id="collection-edit-value" label={op==='rename_column'?'Header label':op==='mark_unresolved'?'Unresolved concern':'Corrected value'}><Textarea id="collection-edit-value" value={value} onChange={e=>setValue(e.target.value)} disabled={pending}/></Field>}
 {op==='set_pdf_citation'&&<Field id="collection-pdf-citation" label="Original PDF citation" help="Use the observed original page and normalised [left, top, right, bottom] box measured from the upper left. apply_to is cell or block; leave processed_page null when unknown. Never estimate a source location."><Textarea id="collection-pdf-citation" className="collection-code" rows={8} value={citation} onChange={e=>setCitation(e.target.value)} disabled={pending}/></Field>}
 {op==='split_row'&&<Field id="collection-split" label="New rows" help="Explicit JSON objects using the column keys shown above. Preserve source values unless you have evidence for a correction."><Textarea id="collection-split" className="collection-code" value={split} onChange={e=>setSplit(e.target.value)} disabled={pending} rows={8}/></Field>}
 {op==='merge_rows'&&<p className="caption">{checked.length} selected rows. Conflicting values are reported by the server; none are silently chosen.</p>}
 {op==='exclude_row'&&<p className="caption">The original row remains in history. Its exclusion is recorded and invalidates dependent output approval.</p>}
 <Field id="collection-edit-reason" label="Reason and source evidence"><Textarea id="collection-edit-reason" value={reason} onChange={e=>setReason(e.target.value)} disabled={pending} required/></Field>{localError&&<p role="alert" className="field-error">{localError}</p>}<Button type="submit" disabled={pending}>{pending?'Saving…':'Save extraction decision'}</Button><p className="caption collection-details">Every correction creates a new revision. Existing acceptance and dependent output approval become historical.</p></form></Card>}
 </div></div>;
}
