import { useEffect, useRef, useState } from 'react';
import { Button, Card, Input, Textarea, Badge } from '../../components/ui';
import { Field } from '../../components/closegraph/Field';
import { DownloadLink } from '../../components/closegraph/DocumentPreview';
import type { CollectionsApi } from './api';
import { DatasetReview } from './DatasetReview';
import { datasetLabel, documentsFor, revisionId, statusLabel } from './presentation';
import type { Collection, Issue } from './model';
export interface UploadOptions {document_id?:string;parent_revision_id?:string;reason?:string;period?:string;as_of?:string;task_id?:string}
interface Props {collection:Collection;api:CollectionsApi;pending:boolean;canEdit:boolean;restricted:boolean;issue:Issue|null;onChange:(action:()=>Promise<Collection>)=>Promise<void>;onError:(error:unknown)=>void;onUpload:(files:File[],options:UploadOptions)=>Promise<void>;focusDocument?:string}
export function DocumentsPanel({collection,api,pending,canEdit,restricted,issue,onChange,onError,onUpload,focusDocument}:Props){
 const documents=documentsFor(collection),[selected,setSelected]=useState(focusDocument??documents[0]?.id??''),[sourceId,setSourceId]=useState(''),[datasetId,setDatasetId]=useState(''),[mode,setMode]=useState<'new'|'revision'>('new'),[files,setFiles]=useState<File[]>([]),[reason,setReason]=useState(''),[period,setPeriod]=useState(''),[asOf,setAsOf]=useState(''),[error,setError]=useState(''),[coverageReason,setCoverageReason]=useState(''),[coverageConfirmed,setCoverageConfirmed]=useState(false);
 const fileInput=useRef<HTMLInputElement>(null),document=documents.find(d=>d.id===selected)??documents[0],source=collection.sources.find(s=>s.id===(sourceId||document?.current_revision_id));
 const tables=collection.datasets.filter(d=>d.kind==='extraction'&&d.source_id===source?.id),dataset=tables.find(d=>d.id===datasetId)??tables[0];
 useEffect(()=>{if(focusDocument){setSelected(focusDocument);setSourceId('');setDatasetId('');}},[focusDocument]);
 useEffect(()=>{if(!issue)return;const table=collection.datasets.find(d=>d.table_id===issue.table_id||d.id===issue.table_id);const match=documents.find(d=>d.revisions.some(r=>revisionId(r)===(table?.source_id??issue.source_id)));if(match){setSelected(match.id);setSourceId(table?.source_id??issue.source_id??'');setDatasetId(table?.id??'');}},[issue?.id]);
 useEffect(()=>{setCoverageConfirmed(false);setCoverageReason('');},[source?.id,collection.version]);
 async function upload(event:React.FormEvent){event.preventDefault();setError('');if(mode==='revision'&&(!document||files.length!==1||!reason.trim())){setError('Choose one replacement file and explain what changed.');return;}try{await onUpload(files,{...(mode==='revision'?{document_id:document!.id,parent_revision_id:document!.current_revision_id,reason:reason.trim()}:{}),...(period.trim()?{period:period.trim()}:{}),...(asOf?{as_of:asOf}:{})});setFiles([]);setReason('');if(fileInput.current)fileInput.current.value='';}catch(e){setError((e as Error).message);}}
 function choose(id:string){setSelected(id);setSourceId('');setDatasetId('');setMode('new');}
 return <div className="stack"><div className="evidence-document-layout"><Card><h2>{restricted?'Documents shared with you':'Documents'}</h2><p className="caption">Open a document to see its data and original file. Older versions remain available.</p><div className="evidence-document-list">{documents.map(doc=><button className="collection-list-item" key={doc.id} aria-current={doc.id===document?.id?'page':undefined} onClick={()=>choose(doc.id)}><strong>{doc.title}</strong><small>{doc.period||'No reporting period set'} · {doc.revisions.length} version{doc.revisions.length===1?'':'s'}</small></button>)}</div>{!documents.length&&<p className="empty muted">{restricted?'No documents have been shared with you. Your requests are in Tasks.':'Add documents to start reading and reviewing their data.'}</p>}</Card>
 {canEdit&&!restricted&&<Card><div className="section-head"><h2>{mode==='new'?'Add documents':'Upload a new version'}</h2><Badge tone="info">PDF · CSV · XLSX</Badge></div><div className="evidence-mode-switch" role="group" aria-label="Upload purpose"><Button variant={mode==='new'?'primary':'outline'} disabled={pending} onClick={()=>{setMode('new');setError('');}}>Add new documents</Button><Button variant={mode==='revision'?'primary':'outline'} disabled={pending||!document} onClick={()=>{setMode('revision');setFiles([]);setPeriod(document?.period??'');if(fileInput.current)fileInput.current.value='';}}>Upload new version</Button></div><p className="caption">{mode==='revision'?'Replaces the current version of '+document?.title+'. The earlier file and review history are kept.':'Each file starts a separate document. Use “Upload new version” when a document has been revised.'}</p><form onSubmit={upload} className="collection-form"><Field id="evidence-files" label={mode==='revision'?'Replacement file':'Files to add'} help="Up to 32 MB per file."><Input id="evidence-files" ref={fileInput} type="file" accept=".pdf,.csv,.xlsx" multiple={mode==='new'} disabled={pending} onChange={e=>setFiles(Array.from(e.target.files??[]))}/></Field><Field id="evidence-period" label="Reporting period" help="Use the period your team agrees on, for example March 2026."><Input id="evidence-period" value={period} onChange={e=>setPeriod(e.target.value)} disabled={pending}/></Field><Field id="evidence-as-of" label="Evidence date" help="The date this document describes, used when a check requires recent evidence."><Input id="evidence-as-of" type="date" value={asOf} onChange={e=>setAsOf(e.target.value)} disabled={pending}/></Field>{mode==='revision'&&<Field id="evidence-revision-reason" label="What changed?"><Textarea id="evidence-revision-reason" value={reason} onChange={e=>setReason(e.target.value)} disabled={pending} required/></Field>}{error&&<p role="alert">{error}</p>}<Button type="submit" disabled={pending||!files.length}>{pending?'Uploading…':mode==='revision'?'Save new version':'Add '+(files.length||'')+' document'+(files.length===1?'':'s')}</Button></form></Card>}</div>
 {source&&<Card><div className="section-head"><div><h2>{document?.title??source.filename}</h2><p className="caption">{statusLabel(source.status)} · {document?.period||'Reporting period not set'}{source.id!==document?.current_revision_id?' · Earlier version':''}</p></div><DownloadLink url={api.sourceUrl(collection.id,source.id)} label="Download original"/></div><div className="evidence-document-actions"><Field id="evidence-revision" label="Document version"><select id="evidence-revision" className="input" value={source.id} onChange={e=>{setSourceId(e.target.value);setDatasetId('');}}>{document?.revisions.map((revision,index)=>{const id=revisionId(revision),file=collection.sources.find(s=>s.id===id);return <option value={id} key={id}>Version {index+1}{id===document.current_revision_id?' · current':''}{file?' · '+file.filename:''}</option>;})}</select></Field>{canEdit&&!restricted&&<Button variant="outline" disabled={pending} onClick={()=>void onChange(()=>api.process(collection.id,collection.version,{stage:'extract',source_id:source.id})).catch(()=>{})}>{tables.length?'Read this file again':'Read document'}</Button>}</div>{tables.length>1&&<Field id="evidence-document-table" label="Part of this document"><select id="evidence-document-table" className="input" value={dataset?.id??''} onChange={e=>setDatasetId(e.target.value)}>{tables.map((table,index)=><option key={table.id} value={table.id}>{datasetLabel(table,index)} · {table.row_count} rows{table.accepted?' · checked':''}</option>)}</select></Field>}{source.media_type==='application/pdf'&&canEdit&&!restricted&&<details className="collection-details"><summary>Confirm all expected rows are present</summary><p className="caption">Compare every relevant page with the extracted data. This confirmation records your inspection; it does not prove the financial figures are correct.</p><label className="attestation"><input type="checkbox" checked={coverageConfirmed} disabled={pending} onChange={e=>setCoverageConfirmed(e.target.checked)}/><span>I checked every relevant page and the expected rows are present.</span></label><Field id="coverage-reason" label="Completeness review notes"><Textarea id="coverage-reason" value={coverageReason} disabled={pending} onChange={e=>setCoverageReason(e.target.value)}/></Field><Button disabled={pending||!coverageConfirmed||!coverageReason.trim()} onClick={()=>void onChange(()=>api.verifyCoverage(collection.id,collection.version,source.id,coverageReason.trim())).catch(()=>{})}>Record completeness review</Button></details>}</Card>}
 {dataset?<DatasetReview key={dataset.id} collection={collection} dataset={{...dataset,title:datasetLabel(dataset,tables.indexOf(dataset))}} api={api} pending={pending} canEdit={canEdit&&!restricted&&source?.id===document?.current_revision_id} issue={issue} onChange={onChange} onError={onError}/>:source&&<Card><h2>Document data is not available yet</h2><p className="muted">{source.id!==document?.current_revision_id?'Download this earlier original to inspect it.':'Read the document to view the extracted values. Any reading failures will appear in Tasks and Overview.'}</p></Card>}
 </div>;
}

