import { useEffect, useState } from 'react';
import { Button, Card } from '../../components/ui';
import { Field } from '../../components/closegraph/Field';
import type { Collection, CollectionMember, Party } from './model';
import type { CollectionsApi } from './api';
import { documentsFor, statusLabel } from './presentation';
interface Props {collection:Collection;api:CollectionsApi;pending:boolean;onChange:(action:()=>Promise<Collection>)=>Promise<void>}
export function MembersPanel({collection,api,pending,onChange}:Props){
 const [participants,setParticipants]=useState<CollectionMember[]>([]),[members,setMembers]=useState<CollectionMember[]>(collection.members??[]),[actor,setActor]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{setMembers(collection.members??[]);},[collection.id,JSON.stringify(collection.members)]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);api.participants(collection.id,controller.signal).then(values=>{if(!controller.signal.aborted)setParticipants(values);}).catch(e=>{if(!controller.signal.aborted)setError((e as Error).message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[api,collection.id]);
 function add(){const person=participants.find(p=>p.actor_id===actor);if(!person||members.some(m=>m.actor_id===actor))return;setMembers(all=>[...all,{...person,document_ids:[],request_ids:[]}]);setActor('');}
 function update(id:string,patch:Partial<CollectionMember>){setMembers(all=>all.map(m=>m.actor_id===id?{...m,...patch}:m));}
 async function save(){try{setError('');await onChange(()=>api.members(collection.id,collection.version,members.map(({actor_id,party,document_ids,request_ids})=>({actor_id,party,document_ids,request_ids}))));}catch(e){setError((e as Error).message);}}
 return <Card><h2>People and document sharing</h2><p className="caption">Assign responsibility by name. Investors see only released requests and documents explicitly shared with them.</p>{loading&&<p role="status">Loading available people…</p>}<div className="evidence-member-add"><Field id="member-actor" label="Add a person"><select id="member-actor" className="input" value={actor} onChange={e=>setActor(e.target.value)} disabled={pending||loading}><option value="">Choose a person</option>{participants.filter(p=>!members.some(m=>m.actor_id===p.actor_id)).map((p,index)=><option value={p.actor_id} key={p.actor_id}>{p.display_name??statusLabel(p.party)+' '+(index+1)}</option>)}</select></Field><Button variant="outline" disabled={pending||!actor} onClick={add}>Add to team</Button></div>
 {members.map((member,index)=><div className="record" key={member.actor_id}><div className="section-head"><strong>{member.display_name??participants.find(p=>p.actor_id===member.actor_id)?.display_name??'Team member '+(index+1)}</strong><Button variant="link" disabled={pending} onClick={()=>setMembers(all=>all.filter(m=>m.actor_id!==member.actor_id))}>Remove from team</Button></div><Field id={'member-role-'+index} label="Responsibility"><select id={'member-role-'+index} className="input" value={member.party} disabled={pending} onChange={e=>update(member.actor_id,{party:e.target.value as Party})}>{['account_manager','accountant','fund_manager','investor'].map(value=><option value={value} key={value}>{statusLabel(value)}</option>)}</select></Field><fieldset className="evidence-fieldset"><legend>Documents shared with this person</legend>{documentsFor(collection).map(doc=><label className="attestation" key={doc.id}><input type="checkbox" checked={member.document_ids.includes(doc.id)} disabled={pending} onChange={e=>update(member.actor_id,{document_ids:e.target.checked?[...member.document_ids,doc.id]:member.document_ids.filter(id=>id!==doc.id)})}/><span>{doc.title}</span></label>)}{!collection.documents?.length&&!collection.sources.length&&<p className="caption">Add documents before sharing them.</p>}</fieldset></div>)}
 {error&&<p role="alert">{error}</p>}<Button disabled={pending||loading} onClick={()=>void save()}>Save people and sharing</Button></Card>;
}

