export interface Column { key: string; label: string }
export interface Issue { id: string; severity: 'error'|'warning'|'info'; code: string; message: string; table_id?: string; row_id?: string; column_key?: string; source_id?: string; details?: unknown; resolved?: boolean }
export interface DataRow { row_id: string; values: Record<string,string|null>; locators?: Record<string,Record<string,unknown>>; raw_values?: Record<string,unknown>; formulas?: Record<string,unknown>; excluded?: boolean; source_locations?:Record<string,Record<string,unknown>[]>; lineage?: unknown }
export interface Dataset { id: string; table_id: string; source_id: string; title: string; columns: Column[]; row_count: number; accepted: boolean; kind: 'extraction'|'output'; version: number; stale?: boolean; metadata?: Record<string,unknown> }
export interface SourceFile { id: string; filename: string; media_type: string; status: string; parser?: Record<string,unknown>; coverage?: Record<string,unknown>; issues?: Issue[]; document_id?:string; parent_revision_id?:string; revision_number?:number; period?:string; as_of?:string; uploaded_at?:string; created_at?:string }
export interface Recipe { version: 1; steps: Record<string,unknown>[]; output: string; checks: Record<string,unknown>[]; export?:{formats:('csv'|'xlsx')[];template_source_id?:string;bindings?:Record<string,unknown>} }
export interface Candidate {candidate_id:string;dataset_id:string;format:string;filename:string;media_type:string;byte_size:number;verification:unknown;url:string}
export interface EvidenceDocument {id:string;title:string;period?:string;current_revision_id:string;revisions:(string|{source_id:string;revision_number?:number})[]}
export type Party='account_manager'|'accountant'|'fund_manager'|'investor';
export interface CollectionMember {actor_id:string;party:Party;document_ids:string[];request_ids?:string[];display_name?:string}
export interface Requirement {id:string;title:string;kind:'evidence'|'required_fields'|'unique'|'total'|'bank_balance'|'fee';blocking:boolean;owner_party:Party;owner_actor_id?:string;document_ids:string[];dataset_selector?:{document_id:string;table_title:string};period?:string;freshness_days?:number;due_at?:string;escalate_after_days?:number;parameters:Record<string,unknown>}
export interface EvidenceCheck {id?:string;requirement_id:string;title?:string;status:string;outcome?:string;message?:string;reason?:string;details?:unknown;blocking?:boolean;source_ids?:string[];document_ids?:string[];task_id?:string}
export interface EvidenceTask {updated_at?:string;id:string;title:string;status:string;kind?:'requirement'|'manual';active?:boolean;blocking?:boolean;description?:string;message?:string;reason?:string;owner_party?:Party;owner_actor_id?:string;document_ids?:string[];source_ids?:string[];requirement_id?:string;allowed_actions?:string[];due_at?:string;responses?:Record<string,unknown>[];history?:Record<string,unknown>[]}
export interface Comparison {id:string;document_id:string;before_revision_id:string;after_revision_id:string;status:string;summary:Record<string,unknown>;review?:Record<string,unknown>}
export interface ComparisonPage {summary:Record<string,unknown>;changes:Record<string,unknown>[];ambiguities:Record<string,unknown>[];coverage:Record<string,unknown>;total:number;offset:number;limit:number}
export interface Collection { id: string; title: string; fund_id: string; version: number; status: 'EMPTY'|'QUEUED'|'PROCESSING'|'NEEDS_REVIEW'|'ACCEPTED'|'READY_FOR_REVIEW'|'APPROVED'|'BLOCKED'; sources: SourceFile[]; datasets: Dataset[]; issues: Issue[]; recipe: Recipe|null; steps: Record<string,unknown>[]; history: Record<string,unknown>[]; review: Record<string,unknown>|null; artifacts: Record<string,unknown>[]; summary: Record<string,unknown>; candidates?:Candidate[];documents?:EvidenceDocument[];requirements?:Requirement[];requirements_version?:number;check_results?:EvidenceCheck[];tasks?:EvidenceTask[];notifications?:Record<string,unknown>[];members?:CollectionMember[];flag_recipients?:Pick<CollectionMember,'actor_id'|'party'|'display_name'>[];comparisons?:Comparison[];access?:{party:Party;can_prepare:boolean;can_manage:boolean;can_review:boolean;restricted:boolean;can_flag?:boolean;actor_id?:string} }
export interface RowPage { dataset_id: string; columns: Column[]; rows: DataRow[]; total: number; offset: number; limit: number; offset_of_row?: number }
export type Edit = {op:'set_pdf_citation';row_id:string;column_key:string;original_page:number;processed_page?:number;bbox:number[];coordinate_system:'normalised-0-1';apply_to:'cell'|'block'}|{op:'set_cell';row_id:string;column_key:string;value:string|null}|{op:'rename_column';column_key:string;label:string}|{op:'exclude_row';row_id:string;reason:string}|{op:'set_header';row_id:string}|{op:'split_row';row_id:string;values:Record<string,string|null>[]}|{op:'merge_rows';row_ids:string[]}|{op:'mark_unresolved';message:string}|{op:'resolve_issue';issue_id:string;reason:string};
export const processing = (collection:Collection) => ['QUEUED','PROCESSING'].includes(collection.status);
