export interface Column { key: string; label: string }
export interface Issue { id: string; severity: 'error'|'warning'|'info'; code: string; message: string; table_id?: string; row_id?: string; column_key?: string; source_id?: string; details?: unknown; resolved?: boolean }
export interface DataRow { row_id: string; values: Record<string,string|null>; locators?: Record<string,Record<string,unknown>>; raw_values?: Record<string,unknown>; formulas?: Record<string,unknown>; excluded?: boolean; source_locations?:Record<string,Record<string,unknown>[]>; lineage?: unknown }
export interface Dataset { id: string; table_id: string; source_id: string; title: string; columns: Column[]; row_count: number; accepted: boolean; kind: 'extraction'|'output'; version: number; stale?: boolean; metadata?: Record<string,unknown> }
export interface SourceFile { id: string; filename: string; media_type: string; status: string; parser?: Record<string,unknown>; coverage?: Record<string,unknown>; issues?: Issue[] }
export interface Recipe { version: 1; steps: Record<string,unknown>[]; output: string; checks: Record<string,unknown>[]; export?:{formats:('csv'|'xlsx')[];template_source_id?:string;bindings?:Record<string,unknown>} }
export interface Candidate {candidate_id:string;dataset_id:string;format:string;filename:string;media_type:string;byte_size:number;verification:unknown;url:string}
export interface Collection { id: string; title: string; fund_id: string; version: number; status: 'EMPTY'|'QUEUED'|'PROCESSING'|'NEEDS_REVIEW'|'ACCEPTED'|'READY_FOR_REVIEW'|'APPROVED'|'BLOCKED'; sources: SourceFile[]; datasets: Dataset[]; issues: Issue[]; recipe: Recipe|null; steps: Record<string,unknown>[]; history: Record<string,unknown>[]; review: Record<string,unknown>|null; artifacts: Record<string,unknown>[]; summary: Record<string,unknown>; candidates?:Candidate[] }
export interface RowPage { dataset_id: string; columns: Column[]; rows: DataRow[]; total: number; offset: number; limit: number; offset_of_row?: number }
export type Edit = {op:'set_pdf_citation';row_id:string;column_key:string;original_page:number;processed_page?:number;bbox:number[];coordinate_system:'normalised-0-1';apply_to:'cell'|'block'}|{op:'set_cell';row_id:string;column_key:string;value:string|null}|{op:'rename_column';column_key:string;label:string}|{op:'exclude_row';row_id:string;reason:string}|{op:'set_header';row_id:string}|{op:'split_row';row_id:string;values:Record<string,string|null>[]}|{op:'merge_rows';row_ids:string[]}|{op:'mark_unresolved';message:string}|{op:'resolve_issue';issue_id:string;reason:string};
export const processing = (collection:Collection) => ['QUEUED','PROCESSING'].includes(collection.status);
