import { useEffect, useState } from 'react';
import { Alert, Button, Card, Textarea } from '../../components/ui';
import { Field } from '../../components/closegraph/Field';
import type { Collection, Recipe } from './model';
export function emptyRecipe(table:string):Recipe{return {version:1,steps:[],output:table,checks:[]};}
export function parseRecipe(text:string):Recipe{const value:unknown=JSON.parse(text);if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('A recipe must be a JSON object.');const recipe=value as Recipe;if(recipe.version!==1||!Array.isArray(recipe.steps)||!Array.isArray(recipe.checks)||typeof recipe.output!=='string'||!recipe.output)throw new Error('Use recipe version 1 with steps, checks and an output table or step ID.');return recipe;}
export function stepExample(op:string,input:string,key:string,keys:string[],right:string,id:string):Record<string,unknown>{
 const common={id,op,input};
 switch(op){
  case 'select':return {...common,columns:keys};
  case 'rename':return {...common,columns:{[key]:'renamed_column'}};
  case 'filter':return {...common,where:{column:key,operator:'eq',value:'ENTER_VALUE',type:'text'}};
  case 'derive':return {...common,columns:{new_column:{op:'trim',args:[{column:key}]}}};
  case 'sort':return {...common,by:[{column:key,direction:'asc',type:'text'}]};
  case 'join':case 'lookup':return {...common,right,on:[{left:key,right:key}],columns:{[key]:'reference_value'},how:'left',cardinality:'many_to_one'};
  case 'aggregate':return {...common,by:[key],metrics:{row_count:{op:'count'}}};
  case 'classify':return {...common,column:'classification',rules:[{when:{column:key,operator:'eq',value:'ENTER_VALUE',type:'text'},value:'ENTER_LABEL'}],default:null};
  case 'allocate':return {...common,by:[],weight:key,total:{literal:'ENTER_TOTAL'},column:'allocated_amount',scale:2};
  case 'reshape':return {...common,mode:'melt',id_columns:[key],value_columns:keys.filter(k=>k!==key),variable_column:'field',value_column:'value'};
  default:return common;
 }
}
const help:Record<string,string>={select:'Keep explicit columns in the specified order.',rename:'Rename column keys. Update subsequent steps to use the new keys.',filter:'Keep rows matching your explicit condition. Decimal comparison must be selected explicitly.',derive:'Compute a column using bounded operations and Decimal arithmetic. No code execution.',sort:'Order rows by explicit text or decimal columns.',join:'Match tables on explicit keys. Unmatched and ambiguous matches become issues.',lookup:'Add reference values using explicit keys. Multiple reference matches require resolution.',aggregate:'Group rows and calculate sum, count, minimum or maximum.',classify:'Assign labels using explicit conditions. Ambiguous matches are reported.',allocate:'Allocate using explicit weights and rounding.',reshape:'Reshape columns and rows using explicit bindings.'};
export function RecipeEditor({collection,pending,canEdit,onSave,onRun}:{collection:Collection;pending:boolean;canEdit:boolean;onSave:(recipe:Recipe)=>Promise<void>;onRun:(recipe:Recipe)=>Promise<void>}){
 const inputs=collection.datasets.filter(d=>d.kind==='extraction'),first=inputs[0];
 const [text,setText]=useState(JSON.stringify(collection.recipe??emptyRecipe(first?.table_id??''),null,2)),[operation,setOperation]=useState('select'),[input,setInput]=useState(first?.table_id??''),[step,setStep]=useState(''),[error,setError]=useState(''),[dirty,setDirty]=useState(false),[formats,setFormats]=useState('csv,xlsx'),[template,setTemplate]=useState(''),[bindings,setBindings]=useState(JSON.stringify({sheet:'Export',start_row:2,header_row:1,columns:{},types:{},labels:{}},null,2));
 const saved=JSON.stringify(collection.recipe),accepted=inputs.length>0&&inputs.every(d=>d.accepted);
 useEffect(()=>{setText(JSON.stringify(collection.recipe??emptyRecipe(first?.table_id??''),null,2));setDirty(false);setError('');setFormats((collection.recipe?.export?.formats??['csv','xlsx']).join(','));setTemplate(collection.recipe?.export?.template_source_id??'');setBindings(JSON.stringify(collection.recipe?.export?.bindings??{sheet:'Export',start_row:2,header_row:1,columns:{},types:{},labels:{}},null,2));},[collection.id,saved,first?.table_id]);
 function starter(op=operation){try{const recipe=parseRecipe(text),table=inputs.find(d=>d.table_id===input)??first;const keys=table?.columns.map(c=>c.key)??[];let n=recipe.steps.length+1;while(recipe.steps.some(s=>s.id==='step_'+n))n++;setStep(JSON.stringify(stepExample(op,input||first?.table_id||'',keys[0]??'c1',keys,inputs.find(d=>d.table_id!==input)?.table_id??'ENTER_REFERENCE_TABLE','step_'+n),null,2));setError('');}catch(err){setError((err as Error).message);}}
 function append(){try{const recipe=parseRecipe(text),candidate=JSON.parse(step);if(!candidate||typeof candidate!=='object'||Array.isArray(candidate)||!candidate.id||!candidate.op||!candidate.input)throw new Error('The step needs id, op and input.');if(recipe.steps.some(s=>s.id===candidate.id))throw new Error('Choose a unique step ID.');setText(JSON.stringify({...recipe,steps:[...recipe.steps,candidate],output:candidate.id},null,2));setDirty(true);setStep('');setError('');}catch(err){setError((err as Error).message);}}
 function applyExport(){try{const recipe=parseRecipe(text),options:NonNullable<Recipe['export']>={formats:formats.split(',') as ('csv'|'xlsx')[]};if(template&&options.formats.includes('xlsx')){const parsed=JSON.parse(bindings);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('Template bindings must be a JSON object.');options.template_source_id=template;options.bindings=parsed;}setText(JSON.stringify({...recipe,export:options},null,2));setDirty(true);setError('');}catch(err){setError((err as Error).message);}}
 async function save(run:boolean){try{setError('');const recipe=parseRecipe(text);await (run?onRun(recipe):onSave(recipe));setDirty(false);}catch(err){setError((err as Error).message);}}
 let draft:Recipe|null=null;try{draft=parseRecipe(text);}catch{}
 return <div className="collection-recipe-grid"><Card><div className="section-head"><h2>Transformation recipe</h2><span className="caption">{dirty?'Unsaved draft':'Saved configuration'}</span></div><p className="muted">Define the result explicitly. These rules run deterministically; no model selects mappings, fills missing values or writes execution code.</p>{!accepted&&<p className="collection-callout">Accept every extraction table before running a transformation. You can prepare and save the recipe now.</p>}
 <Field id="collection-recipe" label="Complete recipe" help="Output references an extracted table ID or a preceding step ID. Checks apply to that output unless their table is specified."><Textarea id="collection-recipe" className="collection-code" rows={21} value={text} onChange={e=>{setText(e.target.value);setDirty(true);}} disabled={!canEdit||pending} spellCheck={false}/></Field>
 {error&&<div role="alert"><Alert title="Recipe needs attention" tone="danger">{error}</Alert></div>}<div className="topbar-actions"><Button variant="outline" disabled={!canEdit||pending||!first} onClick={()=>void save(false)}>Save recipe</Button><Button disabled={!canEdit||pending||!accepted} onClick={()=>void save(true)}>Save and transform</Button></div>
 <details className="collection-details"><summary>Validation check examples</summary><p className="caption">Replace column keys and expected values with your authorised rules. A successful job does not establish financial correctness.</p><pre className="collection-json">{JSON.stringify([{type:'required',columns:['column_key']},{type:'unique',columns:['identifier_key']},{type:'total',column:'amount_key',expected:'ENTER_EXPECTED_TOTAL',tolerance:'0'},{type:'balance',debit:'debit_key',credit:'credit_key',tolerance:'0'}],null,2)}</pre></details></Card>
 <div className="stack"><Card><h2>Add a step</h2><p className="caption">Start from a supported operation, edit its explicit configuration, then add it to the recipe. Adding a step makes it the output.</p><div className="collection-form"><Field id="collection-step-input" label="Input table or preceding step"><select className="input" id="collection-step-input" value={input} onChange={e=>setInput(e.target.value)} disabled={!canEdit||pending}>{inputs.map(d=><option key={d.table_id} value={d.table_id}>{d.title} · {d.table_id}</option>)}{draft?.steps.map(s=><option key={String(s.id)} value={String(s.id)}>Step · {String(s.id)}</option>)}</select></Field><Field id="collection-step-operation" label="Operation"><select className="input" id="collection-step-operation" value={operation} onChange={e=>{setOperation(e.target.value);setStep('');}} disabled={!canEdit||pending}>{Object.keys(help).map(op=><option key={op}>{op}</option>)}</select></Field><p className="caption">{help[operation]}</p><Button variant="outline" disabled={!canEdit||pending||!first} onClick={()=>starter()}>Configure {operation} step</Button>{step&&<><Field id="collection-step-json" label="Step configuration"><Textarea id="collection-step-json" className="collection-code" rows={13} value={step} onChange={e=>setStep(e.target.value)} disabled={!canEdit||pending} spellCheck={false}/></Field><Button disabled={!canEdit||pending} onClick={append}>Add configured step</Button></>}</div></Card>
 <Card><h2>Configure output layout</h2><p className="caption">Add these settings to the recipe before running. The resulting draft files are inspected and approved before export.</p><Field id="collection-export-formats" label="Output formats"><select id="collection-export-formats" className="input" value={formats} disabled={!canEdit||pending} onChange={e=>setFormats(e.target.value)}><option value="csv,xlsx">CSV and XLSX</option><option value="csv">CSV</option><option value="xlsx">XLSX</option></select></Field><Field id="collection-template" label="XLSX template"><select className="input" id="collection-template" value={template} onChange={e=>setTemplate(e.target.value)} disabled={!canEdit||pending||!formats.includes('xlsx')}><option value="">Create a new workbook</option>{collection.sources.filter(source=>source.media_type.includes('spreadsheetml')).map(source=><option key={source.id} value={source.id}>{source.filename}</option>)}</select></Field>{template&&formats.includes('xlsx')&&<Field id="collection-template-bindings" label="Template bindings (JSON)" help="Specify sheet, start_row and columns mapping output keys to Excel letters. Numeric/date conversion is explicit through types. Unsupported workbook features are rejected."><Textarea id="collection-template-bindings" className="collection-code" rows={9} value={bindings} onChange={e=>setBindings(e.target.value)} disabled={!canEdit||pending}/></Field>}<Button variant="outline" disabled={!canEdit||pending||!first} onClick={applyExport}>Add output layout to recipe</Button></Card>
 <Card><h2>Available fields</h2>{inputs.map(table=><div className="record" key={table.id}><strong>{table.title}</strong><code className="collection-id">{table.table_id}</code><p className="caption">{table.columns.map(c=>c.key+' = '+c.label).join(' · ')}</p></div>)}{!first&&<p className="muted">Upload and extract files to discover fields.</p>}</Card>
 <Card><h2>Last transformation</h2>{collection.steps.length?collection.steps.map((s,i)=><div className="record" key={String(s.id??i)}><strong>{String(s.id??'Step '+(i+1))} · {String(s.operation??s.op??'')}</strong><p className="caption">{String(s.input_rows??'—')} input rows → {String(s.output_rows??'—')} output rows</p><details><summary>Step details</summary><pre className="collection-json">{JSON.stringify(s,null,2)}</pre></details></div>):<p className="muted">The next run will show row counts and diagnostics for each step here.</p>}</Card></div></div>;
}
