import { useState } from 'react';
import { Button, Card, Input, Badge } from '../../components/ui';
import { Field } from '../../components/closegraph/Field';
import type { CollectionsApi } from './api';
import type { Collection, Party, Requirement } from './model';
import { datasetLabel, documentsFor, statusLabel } from './presentation';
const kinds:Record<Requirement['kind'],string>={evidence:'Document is present and current',required_fields:'Required values are filled in',unique:'Identifiers have no duplicates',total:'Total matches an expected amount',bank_balance:'Opening and closing balances reconcile',fee:'Fee matches an approved calculation'};
const decimal=(value:string)=>/^-?\d+(?:\.\d+)?$/.test(value);
interface Props {collection:Collection;api:CollectionsApi;pending:boolean;canManage:boolean;onChange:(action:()=>Promise<Collection>)=>Promise<void>;onDocument:(id:string)=>void}
export function RequirementsPanel({collection,api,pending,canManage,onChange,onDocument}:Props){
 const [editing,setEditing]=useState(''),[title,setTitle]=useState(''),[kind,setKind]=useState<Requirement['kind']>('evidence'),[documentId,setDocumentId]=useState(''),[tableTitle,setTableTitle]=useState(''),[columns,setColumns]=useState<string[]>([]),[owner,setOwner]=useState(''),[party,setParty]=useState<Party>('accountant'),[period,setPeriod]=useState(''),[freshness,setFreshness]=useState(''),[due,setDue]=useState(''),[blocking,setBlocking]=useState(true),[parameters,setParameters]=useState<Record<string,string>>({}),[error,setError]=useState('');
 const docs=documentsFor(collection),doc=docs.find(d=>d.id===documentId),tables=collection.datasets.filter(d=>d.kind==='extraction'&&d.source_id===doc?.current_revision_id),table=tables.find(t=>t.title===tableTitle)??tables[0],members=(collection.members??[]).filter(m=>m.party===party);
 function setParam(key:string,value:string){setParameters(p=>({...p,[key]:value}));}
 function edit(req:Requirement){setEditing(req.id);setTitle(req.title);setKind(req.kind);setDocumentId(req.dataset_selector?.document_id??req.document_ids[0]??'');setTableTitle(req.dataset_selector?.table_title??'');setColumns(Array.isArray(req.parameters.columns)?req.parameters.columns.map(String):[]);setOwner(req.owner_actor_id??'');setParty(req.owner_party);setPeriod(req.period??'');setFreshness(req.freshness_days===undefined?'':String(req.freshness_days));setDue(req.due_at?new Date(new Date(req.due_at).getTime()-new Date(req.due_at).getTimezoneOffset()*60000).toISOString().slice(0,16):'');setBlocking(req.blocking);setParameters(Object.fromEntries(Object.entries(req.parameters).filter(([,value])=>typeof value!=='object').map(([key,value])=>[key,String(value)])));setError('');}
 function reset(){setEditing('');setTitle('');setKind('evidence');setDocumentId('');setTableTitle('');setColumns([]);setParameters({});setPeriod('');setFreshness('');setDue('');setOwner('');setError('');}
 async function save(event:React.FormEvent){event.preventDefault();try{
  setError('');if(!title.trim()||kind!=='evidence'&&!documentId||!owner)throw new Error('Enter a check name, assign a responsible person and choose the document if it has arrived.');
  if(kind!=='evidence'&&!table)throw new Error('Read the selected document before choosing the data to check.');
  const p:Record<string,unknown>={};
  if(kind==='evidence')p.minimum_documents=1;
  if(kind==='required_fields'||kind==='unique'){if(!columns.length)throw new Error('Choose at least one field.');p.columns=columns;}
  if(kind==='total'){p.column=parameters.column;p.expected=parameters.expected;p.tolerance=parameters.tolerance||'0';}
  if(kind==='bank_balance'){p.opening=parameters.opening;p.closing=parameters.closing;p.credit_column=parameters.credit_column;p.debit_column=parameters.debit_column;p.debit_sign=parameters.debit_sign||'negative';p.tolerance=parameters.tolerance||'0';}
  if(kind==='fee'){p.base_column=parameters.base_column;p.actual_column=parameters.actual_column;p.rate=parameters.rate;p.scale=Number(parameters.scale||'2');p.tolerance=parameters.tolerance||'0';p.rule_id=parameters.rule_id;p.rule_version=parameters.rule_version;if(!p.rule_id||!p.rule_version)throw new Error('Name the approved fee rule and its version.');}
  for(const key of ['expected','opening','closing','rate','tolerance'])if(key in p&&!decimal(String(p[key]??'')))throw new Error('Enter '+key.replace('_',' ')+' as a plain decimal without commas or currency symbols.');
  for(const key of ['column','credit_column','debit_column','base_column','actual_column'])if(key in p&&!table?.columns.some(c=>c.key===p[key]))throw new Error('Choose every field needed for this check.');
  if(freshness&&(!Number.isInteger(Number(freshness))||Number(freshness)<1))throw new Error('Freshness must be a whole number of days greater than zero.');
  const req:Requirement={id:editing||crypto.randomUUID(),title:title.trim(),kind,blocking,owner_party:party,owner_actor_id:owner,document_ids:documentId?[documentId]:[],...(kind==='evidence'?{}:{dataset_selector:{document_id:documentId,table_title:table!.title}}),...(period.trim()?{period:period.trim()}:{}),...(freshness?{freshness_days:Number(freshness)}:{}),...(due?{due_at:new Date(due).toISOString()}:{}),parameters:p};
  const next=editing?(collection.requirements??[]).map(r=>r.id===editing?req:r):[...(collection.requirements??[]),req];
  await onChange(()=>api.requirements(collection.id,collection.version,next));reset();
 }catch(e){setError((e as Error).message);}}
 function fieldSelect(key:string,label:string){return <Field key={key} id={'check-'+key} label={label}><select id={'check-'+key} className="input" value={parameters[key]??''} onChange={e=>setParam(key,e.target.value)} disabled={pending}><option value="">Choose a field</option>{table?.columns.map(c=><option key={c.key} value={c.key}>{c.label}</option>)}</select></Field>;}
 function numberField(key:string,label:string,help?:string,placeholder?:string){return <Field key={key} id={'check-'+key} label={label} help={help}><Input id={'check-'+key} value={parameters[key]??''} placeholder={placeholder} onChange={e=>setParam(key,e.target.value)} disabled={pending}/></Field>;}
 return <div className="stack"><Card><div className="section-head"><div><h2>Required evidence and checks</h2><p className="caption">Each check records which document version was used and routes anything unresolved to its owner.</p></div><Button variant="outline" disabled={pending||!canManage&&(collection.access?.can_prepare===false)} onClick={()=>void onChange(()=>api.evaluate(collection.id,collection.version)).catch(()=>{})}>Run checks</Button></div>{!(collection.requirements?.length)&&<p className="collection-callout">No checks are configured yet. A manager needs to define the evidence and checks required before output can be released.</p>}
 <div className="evidence-check-list">{(collection.requirements??[]).map(req=>{const result=[...(collection.check_results??[])].reverse().find(c=>c.requirement_id===req.id);return <div className="record" key={req.id}><div className="section-head"><strong>{req.title}</strong><Badge tone={result?.status==='PASS'?'success':result?.status==='FAIL'||result?.status==='ERROR'?'danger':'warning'}>{statusLabel(result?.status??'NOT_RUN')}</Badge></div><p className="caption">{kinds[req.kind]} · {req.blocking?'Required before release':'Informational'}</p>{result?.message&&<p>{result.message}</p>}<div className="topbar-actions">{req.document_ids.map(id=><Button key={id} variant="link" onClick={()=>onDocument(id)}>Open {docs.find(d=>d.id===id)?.title??'document'}</Button>)}{canManage&&<><Button variant="outline" size="sm" disabled={pending} onClick={()=>edit(req)}>Edit check</Button><Button variant="link" size="sm" disabled={pending} onClick={()=>void onChange(()=>api.requirements(collection.id,collection.version,(collection.requirements??[]).filter(r=>r.id!==req.id))).catch(()=>{})}>Remove check</Button></>}</div></div>;})}</div></Card>
 {canManage&&<details className="collection-details" open={Boolean(editing)}><summary>{editing?'Edit required check':'Add a required check'}</summary><Card><form className="collection-form evidence-check-form" onSubmit={save}><Field id="check-title" label="Check name"><Input id="check-title" value={title} onChange={e=>setTitle(e.target.value)} placeholder="March statement reconciles" required disabled={pending}/></Field><Field id="check-kind" label="What should be checked?"><select id="check-kind" className="input" value={kind} onChange={e=>{setKind(e.target.value as Requirement['kind']);setParameters({});setColumns([]);}} disabled={pending}>{Object.entries(kinds).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field id="check-document" label="Document"><select id="check-document" className="input" value={documentId} onChange={e=>{setDocumentId(e.target.value);setTableTitle('');setColumns([]);}} disabled={pending}><option value="">{kind==='evidence'?'Document not received yet':'Choose a document'}</option>{docs.map(d=><option value={d.id} key={d.id}>{d.title}</option>)}</select></Field>{kind!=='evidence'&&<Field id="check-table" label="Data to check"><select id="check-table" className="input" value={table?.title??''} onChange={e=>{setTableTitle(e.target.value);setColumns([]);setParameters({});}} disabled={pending}>{!tables.length&&<option value="">Read this document first</option>}{tables.map((t,index)=><option value={t.title} key={t.id}>{datasetLabel(t,index)} · {t.row_count} rows</option>)}</select></Field>}
 {(kind==='required_fields'||kind==='unique')&&<fieldset className="evidence-fieldset"><legend>{kind==='required_fields'?'Required fields':'Fields that identify a unique row'}</legend>{table?.columns.map(c=><label className="attestation" key={c.key}><input type="checkbox" checked={columns.includes(c.key)} onChange={e=>setColumns(list=>e.target.checked?[...list,c.key]:list.filter(k=>k!==c.key))} disabled={pending}/><span>{c.label}</span></label>)}</fieldset>}
 {kind==='total'&&<>{fieldSelect('column','Amount field')}{numberField('expected','Expected total',undefined,'0.00')}</>}
 {kind==='bank_balance'&&<>{numberField('opening','Opening balance')}{numberField('closing','Closing balance')}{fieldSelect('credit_column','Money in field')}{fieldSelect('debit_column','Money out field')}<Field id="check-debit-sign" label="How are money out values written?"><select id="check-debit-sign" className="input" value={parameters.debit_sign??'negative'} onChange={e=>setParam('debit_sign',e.target.value)}><option value="negative">Negative values, for example −25.00</option><option value="positive">Positive values, for example 25.00</option></select></Field></>}
 {kind==='fee'&&<>{fieldSelect('base_column','Amount used to calculate the fee')}{numberField('rate','Fee multiplier','Enter the multiplier for this exact period, for example 0.01 for 1%. Annualisation is not assumed.')}{fieldSelect('actual_column','Recorded fee field')}{numberField('scale','Decimal places',undefined,'2')}{numberField('rule_id','Approved fee rule name')}{numberField('rule_version','Approved fee rule version')}<p className="caption">Saving this rule records the manager who approved it. State the fee period and convention in the check name.</p></>}
 {['total','bank_balance','fee'].includes(kind)&&numberField('tolerance','Allowed difference','Use 0 for an exact match.','0')}
 <Field id="check-period" label="Required reporting period"><Input id="check-period" value={period} onChange={e=>setPeriod(e.target.value)} disabled={pending} placeholder="Leave blank if any period is acceptable"/></Field><Field id="check-freshness" label="Maximum age in days"><Input id="check-freshness" type="number" min={1} step={1} value={freshness} onChange={e=>setFreshness(e.target.value)} disabled={pending} placeholder="No age limit"/></Field><Field id="check-due" label="Due by"><Input id="check-due" type="datetime-local" value={due} onChange={e=>setDue(e.target.value)} disabled={pending}/></Field><Field id="check-party" label="Responsible team"><select id="check-party" className="input" value={party} onChange={e=>{setParty(e.target.value as Party);setOwner('');}} disabled={pending}>{['account_manager','accountant','fund_manager','investor'].map(value=><option value={value} key={value}>{statusLabel(value)}</option>)}</select></Field><Field id="check-owner" label="Responsible person"><select id="check-owner" className="input" value={owner} onChange={e=>setOwner(e.target.value)} disabled={pending}><option value="">Choose a person</option>{members.map((m,index)=><option value={m.actor_id} key={m.actor_id}>{m.display_name??statusLabel(m.party)+' '+(index+1)}</option>)}</select></Field><label className="attestation"><input type="checkbox" checked={blocking} onChange={e=>setBlocking(e.target.checked)} disabled={pending}/><span>Prevent output release until this check passes</span></label>{error&&<p role="alert">{error}</p>}<div className="topbar-actions"><Button type="submit" disabled={pending}>{editing?'Save check changes':'Add check'}</Button>{editing&&<Button variant="outline" disabled={pending} onClick={reset}>Cancel editing</Button>}</div></form></Card></details>}
 </div>;
}

