import { useEffect, useRef, useState } from 'react';
import { Button, Card, Input, Textarea, Badge } from '../../components/ui';
import { Field } from '../../components/closegraph/Field';
import type { CollectionsApi } from './api';
import type { Collection, EvidenceTask, Party } from './model';
import {actorLabel,readableDate} from '../fund-review/presentation';
import { documentName, documentsFor, statusLabel } from './presentation';
import type { UploadOptions } from './DocumentsPanel';
const actionLabels:Record<string,string>={reply:'Send reply',acknowledge:'Acknowledge request',evidence_received:'Record evidence received',request_verification:'Request verification',resolve:'Resolve concern',release:'Send request to investor',reopen:'Reopen concern',make_blocking:'Require resolution before output release'};
interface Props {focusTask?:string;collection:Collection;api:CollectionsApi;pending:boolean;actor:string;canFlag:boolean;restricted:boolean;onChange:(action:()=>Promise<Collection>)=>Promise<void>;onUpload:(files:File[],options:UploadOptions)=>Promise<void>;onDocument:(id:string)=>void}
export function TasksPanel({collection,api,pending,actor,canFlag,restricted,onChange,onUpload,onDocument,focusTask}:Props){
 const [filter,setFilter]=useState('active'),[selected,setSelected]=useState(''),[note,setNote]=useState(''),[file,setFile]=useState<File|null>(null),[asOf,setAsOf]=useState(''),[localError,setLocalError]=useState(''),[sent,setSent]=useState(''),[flagTitle,setFlagTitle]=useState(''),[flagReason,setFlagReason]=useState(''),[flagDocument,setFlagDocument]=useState(''),[flagOwner,setFlagOwner]=useState(''),[flagParty,setFlagParty]=useState<Party>('accountant');
 useEffect(()=>{if(focusTask){setSelected(focusTask);setFilter('all');}},[focusTask]);
 const responseInput=useRef<HTMLInputElement>(null);
 const tasks=collection.tasks??[],visible=tasks.filter(t=>filter==='all'||filter==='mine'&&t.owner_actor_id===actor||filter==='active'&&t.active!==false&&t.status!=='resolved'),task=visible.find(t=>t.id===selected)??visible[0];
 const canRaise=collection.access?.can_flag??canFlag,recipients=(collection.flag_recipients??collection.members??[]).filter(m=>!restricted||['account_manager','fund_manager'].includes(m.party)),members=restricted?recipients:recipients.filter(m=>m.party===flagParty);
 const actions=(task?.allowed_actions??[]).filter(value=>task?.active!==false&&value in actionLabels&&(!restricted||value!=='evidence_received')&&(value!=='make_blocking'||collection.access?.can_manage===true));
 const ownerName=(t:EvidenceTask)=>collection.members?.find(m=>m.actor_id===t.owner_actor_id)?.display_name??(t.owner_actor_id===actor?'You':statusLabel(t.owner_party??'Unassigned'));
 async function action(value:string){if(!task||!actions.includes(value))return;setLocalError('');if(!note.trim()){setLocalError('Add a note explaining your action.');return;}try{await onChange(()=>api.taskAction(collection.id,collection.version,task.id,value,note.trim()));setNote('');setSent(value==='reply'?'Reply sent. The request remains open.':'Request updated.');}catch(e){setLocalError((e as Error).message);}}
 async function attach(){if(!task||!file)return;try{setLocalError('');await onUpload([file],{task_id:task.id,reason:note.trim()||'Evidence supplied in response to this request.',...(asOf?{as_of:asOf}:{})});setFile(null);setAsOf('');setNote('');setSent('Evidence attached. It still needs verification.');if(responseInput.current)responseInput.current.value='';}catch(e){setLocalError((e as Error).message);}}
 async function flag(event:React.FormEvent){event.preventDefault();try{setLocalError('');if(!flagOwner||!members.some(member=>member.actor_id===flagOwner))throw new Error('Choose an available responsible person.');await onChange(()=>api.flag(collection.id,collection.version,{title:flagTitle.trim(),reason:flagReason.trim(),document_ids:flagDocument?[flagDocument]:[],owner_actor_id:flagOwner}));setFlagTitle('');setFlagReason('');}catch(e){setLocalError((e as Error).message);}}
 return <div className="stack"><Card><div className="section-head"><div><h2>{restricted?'Your requests':'Requests'}</h2><p className="caption">{restricted?'Only requests and documents explicitly shared with you appear here.':'Acknowledge requests, attach evidence and follow verification through to completion.'}</p></div><label className="caption">Show <select className="collection-inline-select" aria-label="Task filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Active tasks</option><option value="mine">Assigned to me</option><option value="all">All tasks</option></select></label></div></Card>
 <div className="evidence-task-layout"><Card><div className="evidence-task-list">{visible.map(item=><button className="collection-list-item" key={item.id} aria-current={item.id===task?.id?'page':undefined} onClick={()=>{setSelected(item.id);setNote('');setFile(null);setLocalError('');}}><strong>{item.title}</strong><small>Status: {item.active===false?'Withdrawn':statusLabel(item.status)}</small><small>Assigned to: {ownerName(item)}</small><span>View request →</span>{item.due_at&&<small>Due {new Date(item.due_at).toLocaleDateString()}</small>}</button>)}</div>{!visible.length&&<p className="empty muted">No tasks match this view.</p>}</Card>
 {task&&<Card><div className="section-head"><h2>{task.title}</h2><Badge tone={task.status==='resolved'?'success':'warning'}>{task.active===false?'Withdrawn':statusLabel(task.status)}</Badge></div>{task.kind==='manual'&&<><Badge tone="info">Manually raised concern</Badge><p className="caption">Raised by a person; an automated check has not verified this concern. {task.blocking?'Resolution is required before output release.':'This concern does not currently block output release.'}</p></>}<p>{task.description??task.message??task.reason??'Follow the request and record your response below.'}</p><p className="caption">Assigned to {ownerName(task)}{task.due_at?' · Due '+new Date(task.due_at).toLocaleDateString():''}</p>{Boolean(task.document_ids?.length)&&<div className="evidence-document-links">{task.document_ids?.filter(id=>documentsFor(collection).some(doc=>doc.id===id)).map(id=><Button key={id} variant="link" onClick={()=>onDocument(id)}>Open {documentName(collection,id)}</Button>)}</div>}
 {task.status==='pending_manager_release'&&<p className="collection-callout">This investor request has not been sent. A manager must release it before the investor can see it.</p>}{task.requirement_id&&task.status!=='resolved'&&<p className="caption">This task closes when its check passes after verification. Acknowledgement or an upload alone does not mark it complete.</p>}
 {actions.length>0&&<Field id="task-note" label="Response or action note"><Textarea id="task-note" value={note} onChange={e=>setNote(e.target.value)} disabled={pending}/></Field>}
 <div className="topbar-actions">{actions.map(value=><Button key={value} variant={value==='release'||value==='reply'?'primary':'outline'} disabled={pending||!note.trim()} onClick={()=>void action(value)}>{actionLabels[value]}</Button>)}</div>
 {task.status!=='resolved'&&task.status!=='pending_manager_release'&&task.allowed_actions?.includes('evidence_received')&&<div className="evidence-task-response"><h3>Attach requested evidence</h3><p className="caption">The file is attached to this request. The request stays open until the evidence is checked. You can include a message in the response note above.</p><Field id="task-response-file" label="Choose evidence file"><Input key={task.id} id="task-response-file" ref={responseInput} type="file" accept=".pdf,.csv,.xlsx" disabled={pending} onChange={e=>setFile(e.target.files?.[0]??null)}/></Field><Field id="task-evidence-date" label="Evidence date" help="The date this document describes; used for freshness checks."><Input id="task-evidence-date" type="date" value={asOf} onChange={e=>setAsOf(e.target.value)} disabled={pending}/></Field><Button disabled={pending||!file} onClick={()=>void attach()}>{pending?'Attaching evidence…':'Attach evidence'}</Button></div>}
 {sent&&<p role="status">{sent}</p>}
 {(task.history??task.responses??(task as EvidenceTask&{events?:Record<string,unknown>[]}).events)?.length?<details open className="collection-details"><summary>Request activity</summary>{[...(task.history??task.responses??(task as EvidenceTask&{events?:Record<string,unknown>[]}).events??[])].reverse().map((event,i)=><div className="record" key={i}><strong>{event.action==='reply'?'Reply sent':event.action==='evidence_received'?'Evidence attached':statusLabel(String(event.action??event.type??'Activity'))}</strong>{Boolean(event.note??event.reason)&&<p>{String(event.note??event.reason)}</p>}<p className="caption">{String(event.actor_name??actorLabel(event.actor_id,collection))} · {readableDate(event.at??event.created_at)}</p>{Array.isArray(event.document_ids)&&event.document_ids.filter((id)=>documentsFor(collection).some(doc=>doc.id===id)).map(id=><Button key={String(id)} variant="link" onClick={()=>onDocument(String(id))}>Open {documentName(collection,String(id))}</Button>)}</div>)}</details>:null}</Card>}</div>
 {localError&&<p role="alert">{localError}</p>}
 {canRaise&&<details className="collection-details"><summary>Raise a concern or request evidence</summary><Card><p className="caption">Raise a concern for a person to investigate. It is recorded as a manually raised concern, not a verified finding.</p><form className="collection-form" onSubmit={flag}><Field id="flag-title" label="What needs attention?"><Input id="flag-title" value={flagTitle} onChange={e=>setFlagTitle(e.target.value)} disabled={pending} required/></Field><Field id="flag-reason" label="Explain the request"><Textarea id="flag-reason" value={flagReason} onChange={e=>setFlagReason(e.target.value)} disabled={pending} required/></Field><Field id="flag-document" label="Related document"><select id="flag-document" className="input" value={flagDocument} onChange={e=>setFlagDocument(e.target.value)}><option value="">No document yet</option>{documentsFor(collection).map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></Field>{!restricted&&<Field id="flag-party" label="Responsible team"><select id="flag-party" className="input" value={flagParty} onChange={e=>{setFlagParty(e.target.value as Party);setFlagOwner('');}}>{['account_manager','accountant','fund_manager','investor'].map(value=><option key={value} value={value}>{statusLabel(value)}</option>)}</select></Field>}<Field id="flag-owner" label="Assign to"><select id="flag-owner" className="input" value={flagOwner} onChange={e=>setFlagOwner(e.target.value)}><option value="">Choose a person</option>{members.map((m,index)=><option value={m.actor_id} key={m.actor_id}>{m.display_name??statusLabel(m.party)+' '+(index+1)}</option>)}</select></Field>{!restricted&&flagParty==='investor'&&<p className="caption">The request waits for manager release before it is visible to the investor.</p>}{restricted&&!members.length&&<p className="caption">No manager is available to receive a concern. Ask your collection contact to assign one.</p>}<Button type="submit" disabled={pending||!flagTitle.trim()||!flagReason.trim()||!flagOwner}>Create task</Button></form></Card></details>}
 </div>;
}

