import {useEffect,useState} from 'react';
import type {AffectedRecordsPage,Finding,FundReviewApi} from './api';
import {display,sourceLocation} from './Checks';

export function AllAffectedRecords({api,workId,finding,stale,pending,onRerun,onDownloaded}:{api:FundReviewApi;workId:string;finding:Finding;stale:boolean;pending:boolean;onRerun?:()=>void;onDownloaded?:()=>void}) {
 const [open,setOpen]=useState(false),[offset,setOffset]=useState(0),[page,setPage]=useState<AffectedRecordsPage|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[downloading,setDownloading]=useState(false);
 useEffect(()=>{setOpen(false);setOffset(0);setPage(null);setError('');},[finding.id,workId]);
 useEffect(()=>{if(!open||stale)return;let active=true;setLoading(true);setError('');setPage(null);api.records(workId,finding.id,offset).then(value=>{if(active)setPage(value);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'The affected records could not be loaded.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[api,workId,finding.id,open,offset,stale]);
 const incomplete=finding.records_complete===false||page?.complete===false;
 async function download(){if(downloading)return;setDownloading(true);setError('');try{const response=await fetch(api.recordsDownload(workId,finding.id),{credentials:'same-origin'});if(!response.ok){let detail:unknown;try{detail=(await response.json()).detail;}catch{}throw new Error(typeof detail==='string'?detail:'The records could not be downloaded. Refresh the review and try again.');}const url=URL.createObjectURL(await response.blob()),link=document.createElement('a');link.href=url;link.download=response.headers.get('Content-Disposition')?.match(/filename="?([^";]+)"?/i)?.[1]??'affected-records.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);onDownloaded?.();}catch(e){setError(e instanceof Error?e.message:'The download could not be prepared.');}finally{setDownloading(false);}}
 return <section className="fr-affected-records fr-space-top" aria-label="All affected records"><div className="fr-row"><div><h3>All affected records</h3><p className="fr-muted">Read the complete source rows behind this finding, or download them for work in Excel. Import identifiers as text in Excel to preserve leading zeros.</p></div><button className="fr-button secondary" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'Hide affected records':'View affected records'}</button></div>
 {(stale||incomplete)&&<div className="fr-notice"><strong>{stale?'These results are no longer current.':'This saved review contains cited examples only.'}</strong><p>{stale?'Rerun the checks against the current evidence before opening or downloading affected records.':page?.message??'Rerun this review to build the complete affected-record list. The cited examples do not represent every affected row.'}</p>{onRerun?<button className="fr-button secondary" disabled={pending} onClick={onRerun}>Rerun checks for all records</button>:<p>Ask the accountant or account manager to rerun this review.</p>}</div>}
 {open&&!stale&&<>{loading&&<p role="status">Loading affected records…</p>}{error&&<p className="fr-error" role="alert">{error}</p>}{page&&<><div className="fr-row fr-space-top"><p>{page.complete?`${page.total.toLocaleString()} source records in this finding.`:'Available cited examples are shown below. The complete affected-record count has not been reconstructed.'}</p>{page.complete&&!incomplete&&<a className="fr-button secondary" href={api.recordsDownload(workId,finding.id)} download aria-disabled={downloading} onClick={event=>{event.preventDefault();void download();}}>{downloading?'Preparing CSV…':'Download all affected records (CSV)'}</a>}</div><div className="fr-table-scroll"><table><caption className="sr-only">{page.complete?'All affected records':'Available cited examples'}</caption><thead><tr><th scope="col">Source</th><th scope="col">Location</th><th scope="col">Selected field</th><th scope="col">Effective value</th><th scope="col">Complete source record</th></tr></thead><tbody>{page.records.map((record,index)=>{const locator=record.locator??{};const location=sourceLocation(locator);const column=record.columns.find(c=>c.key===(record.column_key??record.column));return <tr key={index}><td>{record.source_name}</td><td>{location||'Location unavailable'}</td><td>{column?.label??'Selected record'}</td><td>{display(record.effective_value??record.raw_value)}{record.correction&&<small>Corrected by {record.correction.actor_id??'recorded user'}{record.correction.reason?' · '+record.correction.reason:''}</small>}</td><td><details><summary>Show full record {offset+index+1}</summary><dl className="fr-record">{record.columns.map(c=>{const correction=record.corrections?.[c.key],originalAvailable=Boolean(record.original_values&&Object.prototype.hasOwnProperty.call(record.original_values,c.key)),original=record.original_values?.[c.key];return <div key={c.key}><dt>{c.label} · Effective value</dt><dd>{display(record.values[c.key])}</dd>{originalAvailable&&(correction||original!==record.values[c.key])&&<><dt>{c.label} · Original extracted value</dt><dd>{display(original)}</dd></>}{correction&&<small>Corrected by {correction.actor_id??'recorded user'}{correction.reason?' · '+correction.reason:''}</small>}</div>;})}</dl></details></td></tr>;})}</tbody></table></div><div className="fr-pagination"><span>{page.records.length?offset+1:0}–{offset+page.records.length} of {page.total.toLocaleString()} {page.complete?'source records':'available examples'}</span><button className="fr-button secondary" aria-label="Previous affected records" disabled={loading||offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button><button className="fr-button secondary" aria-label="Next affected records" disabled={loading||offset+page.records.length>=page.total} onClick={()=>setOffset(offset+50)}>Next</button></div></>}</>}
 </section>;
}
