import {afterEach,describe,it,expect,vi} from 'vitest';
import {FundReviewApi} from './api';
afterEach(()=>vi.restoreAllMocks());
describe('fund review results request contract',()=>{
 it('omits an empty status rather than sending an invalid literal',async()=>{const fetcher=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response('{}'));await new FundReviewApi('csrf').results('review/a','','source value',50);const query=new URL(String(fetcher.mock.calls[0][0]),'http://localhost');expect(query.pathname).toBe('/api/collections/review%2Fa/fund-review/results');expect(query.searchParams.has('status')).toBe(false);expect(query.searchParams.get('q')).toBe('source value');expect(query.searchParams.get('offset')).toBe('50');});
 it('sends an explicitly selected status',async()=>{const fetcher=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response('{}'));await new FundReviewApi('csrf').results('review','difference');expect(new URL(String(fetcher.mock.calls[0][0]),'http://localhost').searchParams.get('status')).toBe('difference');});
 it('filters supporting notes on the server without changing passed-result semantics',async()=>{const fetcher=vi.spyOn(globalThis,'fetch').mockImplementation(async()=>new Response('{}'));const api=new FundReviewApi('csrf');await api.results('review','passed','',0,true);await api.results('review','','',50,false);const [main,notes]=fetcher.mock.calls.map(call=>new URL(String(call[0]),'http://localhost'));expect(main.searchParams.get('blocking')).toBe('true');expect(main.searchParams.get('status')).toBe('passed');expect(notes.searchParams.get('blocking')).toBe('false');expect(notes.searchParams.has('status')).toBe(false);expect(notes.searchParams.get('offset')).toBe('50');});
 it('encodes finding identifiers and requests paginated affected records',async()=>{const fetcher=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response('{}'));const api=new FundReviewApi('csrf');await api.records('review/a','finding/b',50);expect(fetcher.mock.calls[0][0]).toBe('/api/collections/review%2Fa/fund-review/findings/finding%2Fb/records?offset=50&limit=50');expect(api.recordsDownload('review/a','finding/b')).toBe('/api/collections/review%2Fa/fund-review/findings/finding%2Fb/download');});
});
