import {render,screen,within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {afterEach,describe,expect,it,vi} from 'vitest';
import {AllAffectedRecords} from './AffectedRecords';
import {actionableCount,reviewBlockers,ReviewScope,SupportingNotes} from './ReviewReadiness';
import {CheckCard,sourceLocation} from './Checks';
import {FundReviewApi,type BriefResults,type Finding,type FundWork,type ReviewCheck,type TableProfile} from './api';

afterEach(()=>vi.restoreAllMocks());
const finding:Finding={id:'finding/b',match_key:'absent-mapping',status:'difference',title:'References are missing',explanation:'The selected references are absent.',kind:'reference',evidence:[],evidence_total:63,records_total:63,records_complete:true,affected_count:63};
const check:ReviewCheck={id:'mapping',title:'Identifiers have a reference',kind:'reference',confirmed:true,left:{dataset_id:'source',column:'id'},right:{dataset_id:'reference',column:'id'}};
const tables:TableProfile[]=[{dataset_id:'source',source_id:'s1',source_name:'Reporting pack.csv',title:'Holdings',row_count:63,columns:[{key:'id',label:'Investment ID'}],preview:[]},{dataset_id:'reference',source_id:'s2',source_name:'Reference list.csv',title:'Register',row_count:63,columns:[{key:'id',label:'Investment ID'}],preview:[]}];
const results:BriefResults={tables,suggestions:[],findings:[],total:1,summary:{difference:0,needs_input:1,passed:1,blocking_difference:0,blocking_needs_input:0,nonblocking_needs_input:1},coverage:{complete:true},changes:{}};
const work={id:'review',version:3,status:'NEEDS_REVIEW',sources:[],fund_review:{status:'COMPLETE',config:{checks:[check],confirmed_source_ids:[]}}} as unknown as FundWork;

describe('complete finding records and scoped readiness',()=>{
 it('shows physical CSV row and column locations instead of a page ordinal',()=>{expect(sourceLocation({kind:'csv',row:1042,column:7})).toBe('Row 1042 · Column 7');expect(sourceLocation({sheet:'Holdings',cell:'G1042',row:1042})).toBe('Holdings · G1042');});
 it('shows all 63 records across two pages, including complete values beyond cited examples',async()=>{
  const api=new FundReviewApi('test');const records=Array.from({length:63},(_,index)=>({source_name:'Reporting pack.csv',row_id:'row-'+index,column_key:'id',raw_value:'Corrected reference',effective_value:'Corrected reference',original_raw_value:'Missing reference',original_value_available:true,correction:{actor_id:'accountant',reason:'Checked against the register'},columns:[{key:'id',label:'Investment ID'},{key:'amount',label:'Amount'}],values:{id:'Corrected reference',amount:String(1000+index)},original_values:{id:'Missing reference',amount:String(1000+index)},corrections:{id:{actor_id:'accountant',reason:'Checked against the register'}}}));
  const read=vi.spyOn(api,'records').mockImplementation(async(_id,_finding,offset=0)=>({records:records.slice(offset,offset+50),total:63,offset,limit:50,complete:true}));
  render(<AllAffectedRecords api={api} workId="review/a" finding={finding} stale={false} pending={false}/>);const user=userEvent.setup();expect(read).not.toHaveBeenCalled();await user.click(screen.getByRole('button',{name:'View affected records'}));
  expect(await screen.findByText('1–50 of 63 source records')).toBeVisible();expect(screen.getByRole('columnheader',{name:'Effective value'})).toBeVisible();expect(screen.getAllByText('Corrected by accountant · Checked against the register').length).toBeGreaterThan(0);expect(within(screen.getByRole('table')).getAllByRole('row')).toHaveLength(51);expect(screen.getByRole('link',{name:'Download all affected records (CSV)'})).toHaveAttribute('href','/api/collections/review%2Fa/fund-review/findings/finding%2Fb/download');
  await user.click(screen.getByRole('button',{name:'Next affected records'}));expect(await screen.findByText('51–63 of 63 source records')).toBeVisible();expect(read).toHaveBeenLastCalledWith('review/a','finding/b',50);expect(within(screen.getByRole('table')).getAllByRole('row')).toHaveLength(14);await user.click(screen.getByText('Show full record 63'));expect(screen.getAllByText('Investment ID · Effective value').length).toBeGreaterThan(0);expect(screen.getAllByText('Investment ID · Original extracted value').length).toBeGreaterThan(0);expect(screen.getAllByText('1062').length).toBeGreaterThan(0);expect(screen.getByRole('button',{name:'Next affected records'})).toBeDisabled();
 });
 it('labels legacy samples honestly and offers a rerun instead of a partial download',async()=>{
  const api=new FundReviewApi('test'),rerun=vi.fn();vi.spyOn(api,'records').mockResolvedValue({records:[],total:12,offset:0,limit:50,complete:false,message:'Only cited examples were saved; rerun to collect every affected row.'});render(<AllAffectedRecords api={api} workId="review" finding={{...finding,records_complete:undefined}} stale={false} pending={false} onRerun={rerun}/>);const user=userEvent.setup();await user.click(screen.getByRole('button',{name:'View affected records'}));expect(await screen.findByText('This saved review contains cited examples only.')).toBeVisible();expect(screen.queryByRole('link',{name:/Download all/})).not.toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Rerun checks for all records'}));expect(rerun).toHaveBeenCalledOnce();
 });
 it('keeps stale records unavailable until the checks are rerun',async()=>{const api=new FundReviewApi('test'),read=vi.spyOn(api,'records');render(<AllAffectedRecords api={api} workId="review" finding={finding} stale pending={false}/>);await userEvent.setup().click(screen.getByRole('button',{name:'View affected records'}));expect(screen.getByText('These results are no longer current.')).toBeVisible();expect(read).not.toHaveBeenCalled();expect(screen.queryByRole('link')).not.toBeInTheDocument();});
 it('separates unverified supporting notes from passing results and approval blockers',async()=>{
  const api=new FundReviewApi('test');const note:Finding={...finding,id:'note',status:'needs_input',kind:'formula_scope',blocking:false,title:'Unselected formula results are not verified',explanation:'The chosen identifier check does not use these formula columns.'};const read=vi.spyOn(api,'results').mockResolvedValue({...results,findings:[note]});const select=vi.fn();render(<SupportingNotes api={api} workId="review" version={3} total={1} onSelect={select}/>);const user=userEvent.setup();await user.click(screen.getByRole('button',{name:'1 supporting note outside the selected checks'}));expect(await screen.findByText(note.title)).toBeVisible();expect(read).toHaveBeenCalledWith('review','','',0,false);expect(screen.getByText('Supporting note · not verified')).toBeVisible();expect(screen.queryByText('Passed results')).not.toBeInTheDocument();await user.click(screen.getByRole('button',{name:/Unselected formula results/}));expect(select).toHaveBeenCalledWith(note);expect(actionableCount(results.summary,'needs_input')).toBe(0);expect(actionableCount(results.summary,'passed')).toBe(1);expect(reviewBlockers(work,results)).toEqual([]);expect(reviewBlockers(work,{...results,summary:{...results.summary,blocking_needs_input:1}})).toContain('1 finding still needs your input.');
 });
 it('names the exact source and reference on suggestion cards and in the reviewed scope',()=>{render(<><CheckCard check={check} tables={tables} pending={false} onConfirm={()=>{}} onEdit={()=>{}}/><ReviewScope config={work.fund_review!.config} tables={tables}/></>);expect(screen.getByRole('heading',{name:'Reporting pack.csv · Holdings · Investment ID → Reference list.csv · Register · Investment ID'})).toBeVisible();expect(screen.getByText(/It does not verify unselected formulas/)).toBeInTheDocument();});
});
