import {render,screen,within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {describe,it,expect,vi} from 'vitest';
import {People} from './People';
import {CollectionsApi} from '../collections/api';
import type {Collection,CollectionMember} from '../collections/model';
const work={id:'review',version:3,title:'Quarterly review',sources:[],datasets:[],documents:[{id:'own-evidence',title:'Investor A evidence.xlsx',current_revision_id:'one',revisions:['one']},{id:'other-evidence',title:'Other investor evidence.xlsx',current_revision_id:'two',revisions:['two']}],members:[{actor_id:'manager',party:'account_manager',document_ids:[]}],access:{can_manage:true}} as unknown as Collection;
describe('people and explicit document sharing',()=>{
 it('adds only a permitted account with no files, then saves only the selected grant without presentation fields',async()=>{const api=new CollectionsApi('test');vi.spyOn(api,'participants').mockResolvedValue([{actor_id:'investor',party:'investor',display_name:'Investor A',document_ids:['unexpected-server-default']}]);const save=vi.spyOn(api,'members').mockImplementation(async(_id,_version,members:CollectionMember[])=>({...work,version:4,members}));render(<People work={work} api={api} pending={false} onChange={async action=>{await action();}}/>);const user=userEvent.setup();await screen.findByRole('option',{name:'Investor A · Investor'});await user.selectOptions(screen.getByRole('combobox',{name:'Add a person'}),'investor');await user.click(screen.getByRole('button',{name:'Add person'}));const person=screen.getByRole('article',{name:'Investor A'});expect(within(person).getByRole('checkbox',{name:'Investor A evidence.xlsx'})).not.toBeChecked();expect(within(person).getByRole('checkbox',{name:'Other investor evidence.xlsx'})).not.toBeChecked();await user.click(screen.getByRole('button',{name:'Save people and access'}));expect(save.mock.calls[0][2].find(m=>m.actor_id==='investor')).toEqual({actor_id:'investor',party:'investor',document_ids:[]});await user.click(within(person).getByRole('checkbox',{name:'Investor A evidence.xlsx'}));await user.click(screen.getByRole('button',{name:'Save people and access'}));expect(save.mock.calls[1][2].find(m=>m.actor_id==='investor')).toEqual({actor_id:'investor',party:'investor',document_ids:['own-evidence']});expect(save.mock.calls[1][1]).toBe(4);expect(screen.queryByRole('combobox',{name:'Responsibility'})).not.toBeInTheDocument();});
 it('does not fetch or expose management controls for an external participant',()=>{const api=new CollectionsApi('test');const available=vi.spyOn(api,'participants');render(<People work={{...work,access:{...work.access!,can_manage:false,restricted:true}}} api={api} pending={false} onChange={async()=>{}}/>);expect(screen.getByText('Only an account manager can change people and document access.')).toBeVisible();expect(available).not.toHaveBeenCalled();expect(screen.queryByRole('button',{name:'Save people and access'})).not.toBeInTheDocument();});
});
