import {useEffect,useState} from 'react';
import type {Collection,EvidenceTask} from '../collections/model';
import type {CollectionsApi} from '../collections/api';
import type {UploadOptions} from '../collections/DocumentsPanel';
import {TasksPanel} from '../collections/TasksPanel';
import {statusLabel} from '../collections/presentation';
import type {FundReviewApi,FundWork,Finding} from './api';
type ReviewTask=EvidenceTask&{item_ids?:string[]};
export function FundRequests({work,api,reviewApi,pending,restricted,focusTask,onChange,onUpload,onDocument,onFinding,onError}:{work:FundWork;api:CollectionsApi;reviewApi:FundReviewApi;pending:boolean;restricted:boolean;focusTask:string;onChange:(action:()=>Promise<Collection>)=>Promise<void>;onUpload:(files:File[],options:UploadOptions)=>Promise<void>;onDocument:(id:string)=>void;onFinding:(finding:Finding)=>void;onError:(error:unknown)=>void}){
 const [selected,setSelected]=useState(focusTask),[filter,setFilter]=useState('active'),[loading,setLoading]=useState(false);useEffect(()=>{if(focusTask){setSelected(focusTask);setFilter('all');}},[focusTask]);
 const tasks=[...(work.tasks??[])].reverse() as ReviewTask[];const visible=tasks.filter(t=>filter==='all'||t.active!==false&&t.status!=='resolved');const task=visible.find(t=>t.id===selected)??visible[0];const isFinding=String(task?.kind)==='fund_review';
 async function evidence(id:string){setLoading(true);try{const result=await reviewApi.results(work.id,'',id);const finding=result.findings.find(f=>f.id===id);if(!finding)throw Error('This finding is no longer in the current result. Review the request activity and latest brief before closing the request.');onFinding(finding);}catch(e){onError(e);}finally{setLoading(false);}}
 return <div className="fr-request-layout"><section className="fr-request-list"><div className="fr-row"><h2>Requests</h2><label><span className="sr-only">Show requests</span><select aria-label="Show requests" value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Active</option><option value="all">All</option></select></label></div>{visible.map(item=><button key={item.id} className="fr-request-item" aria-current={item.id===task?.id?'page':undefined} onClick={()=>setSelected(item.id)}><strong>{item.title}</strong><span>{item.active===false?'Withdrawn':statusLabel(item.status)}</span><small>{work.members?.find(m=>m.actor_id===item.owner_actor_id)?.display_name??(item.owner_actor_id===work.access?.actor_id?'You':statusLabel(item.owner_party??'Unassigned'))}{item.due_at?' · Due '+new Date(item.due_at).toLocaleDateString():''}</small><span>View request →</span></button>)}{!visible.length&&<p className="fr-muted">No {filter==='active'?'active ':''}requests. A manually raised question can be added here.</p>}</section><section className="fr-request-detail">{isFinding&&<div className="fr-panel"><span className="fr-label">LINKED TO A REVIEW FINDING</span><p>This request closes only when its check passes on current evidence. Reading it, acknowledging it or attaching a file does not resolve it.</p>{!restricted&&!!task?.item_ids?.length&&<div className="fr-actions">{task.item_ids.slice(0,5).map((id,index)=><button key={id} className="fr-button secondary" disabled={loading} onClick={()=>void evidence(id)}>{loading?'Loading evidence…':task.item_ids!.length>1?'View supporting finding '+(index+1):'View supporting finding'}</button>)}</div>}</div>}<TasksPanel key={task?.id??'empty'} collection={{...work,tasks:task?[task]:[]}} api={api} pending={pending} actor={work.access?.actor_id??''} canFlag={work.access?.can_flag??!restricted} restricted={restricted} focusTask={task?.id} onChange={onChange} onUpload={onUpload} onDocument={onDocument}/></section></div>;
}
