import {render,screen,waitFor,within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {FundReviewWorkspace} from './Workspace';
import {CheckCard} from './Checks';
import {FundRequests} from './Requests';
import {CollectionsApi} from '../collections/api';
import {FundReviewApi,type FundWork} from './api';
import type {ReviewCheck,TableProfile} from './api';
const session={username:'accountant',role:'PREPARER',csrf_token:'test',collection_funds:[{tenant_id:'t',fund_id:'f'}]};
const json=(value:unknown)=>new Response(JSON.stringify(value));
const table:TableProfile={dataset_id:'table-private-key',source_id:'source-private-key',title:'Investor activity',row_count:3,header_row_id:'header',columns:[{key:'c1',label:'Investor name'}],preview:[{row_id:'r2',values:{c1:'Investor A'}}]};
const suggestion:ReviewCheck={id:'mapping',kind:'reference',title:'Investor names have a mapping',confirmed:false,left:{dataset_id:table.dataset_id,column:'c1'},right:{dataset_id:table.dataset_id,column:'c1'},rationale:'Confirm the agreed investor scope before checking.',overlap:{matched_distinct:2,source_distinct:3,reference_distinct:2}};
const work={id:'review',title:'Quarterly fund review',version:3,status:'NEEDS_REVIEW',sources:[{id:table.source_id,filename:'Reporting pack.xlsx',media_type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',status:'EXTRACTED'}],datasets:[],history:[],tasks:[],notifications:[],members:[],access:{can_prepare:true,restricted:false},fund_review:{status:'COMPLETE',config:{checks:[],confirmed_source_ids:[]},summary:{passed:0,difference:0,needs_input:1}}};
beforeEach(()=>{sessionStorage.clear();Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:function(){this.setAttribute('open','');}});Object.defineProperty(HTMLDialogElement.prototype,'close',{configurable:true,value:function(){this.removeAttribute('open');}});});
afterEach(()=>{vi.unstubAllGlobals();vi.restoreAllMocks();});
describe('fund review evidence and consent',()=>{
 it.each([false,true])('keeps a finding through download history updates, unless the review is stale (%s)',async stale=>{
  let downloaded=false;
  const currentWork=()=>({...work,version:downloaded?4:3,fund_review:{...work.fund_review,version:2,completed_at:'2026-09-06T10:00:00Z',stale:downloaded&&stale}});
  const finding=()=>({id:'finding',match_key:'missing',kind:'required',title:'Investor identifier is missing',explanation:downloaded?'The current saved finding was refreshed.':'The selected source record has no investor identifier.',status:'needs_input',affected_count:1,records_complete:true,records_total:1,evidence:[{dataset_id:table.dataset_id,source_id:table.source_id,row_id:'r2',column_key:'c1',raw_value:'Investor A'}]});
  vi.stubGlobal('URL',Object.assign(class extends URL {},{createObjectURL:vi.fn(()=>'blob:test-download'),revokeObjectURL:vi.fn()}));vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});
  vi.spyOn(globalThis,'fetch').mockImplementation(async input=>{const url=String(input);if(url==='/api/collections')return json([currentWork()]);if(url==='/api/collections/review')return json(currentWork());if(url.includes('/fund-review/results?'))return json({tables:[table],suggestions:[],findings:[finding()],total:1,summary:work.fund_review.summary,coverage:{complete:false},changes:{available:false},version:downloaded?4:3,stale:downloaded&&stale});if(url.includes('/findings/finding/records?'))return json({records:[{...finding().evidence[0],source_name:'Reporting pack.xlsx',columns:table.columns,values:{c1:'Investor A'}}],total:1,offset:0,limit:50,complete:true});if(url.endsWith('/findings/finding/download')){downloaded=true;return new Response('Investor name\nInvestor A\n',{headers:{'Content-Type':'text/csv','Content-Disposition':'attachment; filename="affected-records.csv"'}});}throw Error(url);});
  render(<FundReviewWorkspace session={session} notice="" onLogout={()=>{}} onSessionChange={()=>{}}/>);const user=userEvent.setup();await user.click(screen.getByRole('button',{name:'Recent work'}));await user.click(await screen.findByRole('button',{name:'Open work'}));await user.click(await screen.findByRole('button',{name:/Investor identifier is missing/}));const dialog=screen.getByRole('dialog',{name:'Finding and supporting evidence'});await user.click(within(dialog).getByRole('button',{name:'View affected records'}));await user.click(await within(dialog).findByRole('link',{name:'Download all affected records (CSV)'}));
  if(stale){await waitFor(()=>expect(screen.queryByRole('dialog',{name:'Finding and supporting evidence'})).not.toBeInTheDocument());}else{expect(await within(dialog).findByText('The current saved finding was refreshed.')).toBeVisible();expect(screen.getByRole('dialog',{name:'Finding and supporting evidence'})).toBe(dialog);expect(within(dialog).getByRole('button',{name:'Hide affected records'})).toBeVisible();}
 });
 it('requires inspection before confirming a proposed relationship and displays actual values',async()=>{const onConfirm=vi.fn();render(<CheckCard check={suggestion} tables={[table]} pending={false} onConfirm={onConfirm} onEdit={()=>{}}/>);const user=userEvent.setup();expect(screen.queryByRole('button',{name:'Confirm and check'})).not.toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Inspect suggestion'}));expect(screen.getAllByText('Investor A')).toHaveLength(2);expect(screen.getByText(/does not confirm the mapping/)).toBeVisible();expect(onConfirm).not.toHaveBeenCalled();await user.click(screen.getByRole('button',{name:'Confirm and check'}));expect(onConfirm).toHaveBeenCalledWith({...suggestion,confirmed:true});});
 it('shows limited review conclusions, reads the exact cited row and keeps identifiers out of normal labels',async()=>{const calls:string[]=[];vi.spyOn(globalThis,'fetch').mockImplementation(async input=>{const url=String(input);calls.push(url);if(url==='/api/collections')return json([work]);if(url==='/api/collections/review')return json(work);if(url.includes('/fund-review/results?'))return json({tables:[table],suggestions:[],findings:[{id:'finding',match_key:'missing',kind:'required',title:'Investor identifier is missing',explanation:'The selected source record has no investor identifier.',status:'needs_input',affected_count:1,evidence:[{dataset_id:table.dataset_id,source_id:table.source_id,row_id:'r2',column_key:'c1',raw_value:'Investor A'}]}],total:1,summary:work.fund_review.summary,coverage:{complete:false},changes:{available:false}});if(url.includes('/rows?'))return json({dataset_id:table.dataset_id,columns:table.columns,rows:table.preview,total:3,offset:1,limit:1});throw Error(url);});render(<FundReviewWorkspace session={session} notice="" onLogout={()=>{}} onSessionChange={()=>{}}/>);const user=userEvent.setup();await user.click(screen.getByRole('button',{name:'Recent work'}));await user.click(await screen.findByRole('button',{name:'Open work'}));await screen.findByText(/Investor identifier is missing · 1 affected record/);expect(screen.getByText(/Reading a file does not prove its accounting is correct/)).toBeVisible();expect(screen.queryByText('table-private-key')).not.toBeInTheDocument();expect(screen.queryByText('Since the previous review')).not.toBeInTheDocument();await user.click(screen.getByRole('button',{name:/Investor identifier is missing/}));const dialog=screen.getByRole('dialog',{name:'Finding and supporting evidence'});await user.click(within(dialog).getByRole('button',{name:'See complete source record'}));await waitFor(()=>expect(calls.some(url=>url.includes('/table-private-key/rows?')&&url.includes('row_id=r2'))).toBe(true));expect(within(dialog).getByRole('link',{name:'Open original'})).toHaveAttribute('href','/api/collections/review/sources/source-private-key/download');});
 it('keeps external participants in their scoped request view',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValue(json([]));render(<FundReviewWorkspace session={{...session,role:'INVESTOR'}} notice="" onLogout={()=>{}} onSessionChange={()=>{}}/>);expect(screen.queryByRole('button',{name:'New review'})).not.toBeInTheDocument();expect(screen.queryByLabelText('Reporting pack and supporting documents')).not.toBeInTheDocument();expect(screen.getByRole('heading',{name:'Requests'})).toBeVisible();await screen.findByText('No requests to show');});
 it('explains and prevents an independent decision by a contributing manager',async()=>{const managerWork={...work,contributors:['manager'],access:{actor_id:'manager',can_prepare:false,can_manage:true,can_review:true,restricted:false}};const refreshIdentity=vi.fn();vi.spyOn(globalThis,'fetch').mockImplementation(async input=>{const url=String(input);if(url==='/api/collections')return json([managerWork]);if(url==='/api/collections/review')return json(managerWork);if(url.includes('/fund-review/results?'))return json({tables:[table],suggestions:[],findings:[],total:0,summary:work.fund_review.summary,coverage:{complete:false},changes:{available:false}});throw Error(url);});render(<FundReviewWorkspace session={{...session,username:'manager',role:'REVIEWER'}} notice="" onLogout={()=>{}} onSessionChange={refreshIdentity}/>);const user=userEvent.setup();await user.click(screen.getByRole('button',{name:'Recent work'}));await user.click(await screen.findByRole('button',{name:'Open work'}));await user.click(await screen.findByRole('button',{name:'Review and release'}));const dialog=screen.getByRole('dialog',{name:'Independent review'});expect(within(dialog).getByText(/You contributed to this review by uploading/)).toBeVisible();await user.type(within(dialog).getByLabelText('Review notes'),'Checked the selected evidence');expect(within(dialog).getByRole('button',{name:'Approve reviewed brief'})).toBeDisabled();expect(within(dialog).getByRole('button',{name:'Return for correction'})).toBeDisabled();expect(refreshIdentity).not.toHaveBeenCalled();});
 it('opens the newest request and fetches its exact linked finding without granting source access',async()=>{const task={id:'request-new',kind:'fund_review',title:'New mapping question',status:'open',owner_actor_id:'accountant',owner_party:'accountant',item_ids:['specific-finding'],document_ids:[],allowed_actions:['acknowledge','evidence_received'],description:'Confirm this specific mapping.'};const finding={id:'specific-finding',match_key:'key',title:'New mapping question',status:'difference' as const,kind:'reference',explanation:'The reference is missing.',evidence:[]};const reviewApi=new FundReviewApi('test');vi.spyOn(reviewApi,'results').mockResolvedValue({tables:[],suggestions:[],findings:[finding],total:1,summary:{},coverage:{},changes:{}});const onFinding=vi.fn();render(<FundRequests work={{...work,access:{...work.access,actor_id:'accountant'},tasks:[{...task,id:'old',title:'Older request'},task]} as unknown as FundWork} api={new CollectionsApi('test')} reviewApi={reviewApi} pending={false} restricted={false} focusTask="" onChange={async()=>{}} onUpload={async()=>{}} onDocument={()=>{}} onFinding={onFinding} onError={()=>{}}/>);expect(screen.getByText('This request closes only when its check passes on current evidence. Reading it, acknowledging it or attaching a file does not resolve it.')).toBeVisible();expect(screen.getByText('Confirm this specific mapping.')).toBeVisible();expect(screen.queryByText('Manually raised concern')).not.toBeInTheDocument();await userEvent.setup().click(screen.getByRole('button',{name:'View supporting finding'}));expect(reviewApi.results).toHaveBeenCalledWith('review','','specific-finding');expect(onFinding).toHaveBeenCalledWith(finding);});

});
