import {test,expect} from './fixtures';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import type {Page} from '@playwright/test';
test.use({trace:'off'});
test.describe.configure({mode:'serial'});
let completedReviewId:string|undefined;
const fixturePath=process.env.CLOSEGRAPH_REAL_FUND_FILES;
function env(name:string){const value=process.env[name];if(!value)throw Error(name+' required');return value;}
async function login(page:Page){await page.goto('/');await page.getByLabel('Username',{exact:true}).fill(env('CLOSEGRAPH_TEST_PREPARER_USERNAME'));await page.getByLabel('Password',{exact:true}).fill(env('CLOSEGRAPH_TEST_PREPARER_PASSWORD'));await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:/Know what is ready/})).toBeVisible();}
test('actual private-market files: upload, inspect, confirm a check, correct, reevaluate and download',async({page},info)=>{
 test.skip(!fixturePath,'Set CLOSEGRAPH_REAL_FUND_FILES to a private manifest containing workbooks (all three actual GL/loader inputs) and reference (the reference loader path).');test.setTimeout(900000);page.setDefaultTimeout(20000);
 const files=JSON.parse(readFileSync(fixturePath!,'utf8')) as {workbooks:string[];reference:string;revision?:string};expect(files.workbooks.length).toBeGreaterThanOrEqual(2);
 await login(page);await page.screenshot({path:info.outputPath('fund-review-upload.png'),fullPage:true});
 const reuseId=process.env.CLOSEGRAPH_FUND_REUSE_REVIEW_ID;let initial:{id:string};let checkAlreadyConfirmed=false;
 if(reuseId){
  // Resume a recorded upload after a UI-only failure; never silently reuse edited results.
  const saved=await page.evaluate(async id=>{const all=await(await fetch('/api/collections')).json();const work=await(await fetch('/api/collections/'+id)).json();return {work,index:all.findIndex((item:any)=>item.id===id)};},reuseId);
  expect(saved.index).toBeGreaterThanOrEqual(0);const priorChecks=saved.work.fund_review?.config?.checks??[];expect(priorChecks.length).toBeLessThanOrEqual(1);if(priorChecks.length){expect(priorChecks[0].title).toBe('Mapping proposals have a recorded approval');expect(priorChecks[0].kind).toBe('required');checkAlreadyConfirmed=true;}expect(saved.work.sources.length).toBe(files.workbooks.length);initial={id:reuseId};
  await page.getByRole('button',{name:'Recent work',exact:true}).click();await page.locator('.fr-recent-list article').nth(saved.index).getByRole('button',{name:'Open work'}).click();
  test.info().annotations.push({type:'resumed-upload',description:'Continued an already uploaded real pack after a UI-only failure; no new extraction or provider request.'});
 }else{
  await page.getByLabel('Reporting pack and supporting documents').setInputFiles(files.workbooks);await page.getByLabel('Review name',{exact:false}).fill('Acceptance · real private-markets reporting pack');
  const starting=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname.endsWith('/fund-review'));await page.getByRole('button',{name:'Prepare review brief',exact:true}).click();const start=await starting;expect(start.ok(),await start.text()).toBe(true);initial=await start.json();
 }
 async function settled(){await expect.poll(async()=>page.evaluate(async id=>{const r=await fetch('/api/collections/'+id);const w=await r.json();return !['QUEUED','PROCESSING'].includes(w.status)&&w.fund_review?.status==='COMPLETE';},initial.id),{timeout:420000,intervals:[2000,5000]}).toBe(true);await expect(page.getByRole('button',{name:'Download brief',exact:true})).toBeVisible({timeout:30000});await expect(page.locator('.fr-findings .fr-finding').first()).toBeVisible({timeout:30000});}
 await settled();completedReviewId=initial.id;await page.screenshot({path:info.outputPath('fund-review-first-brief.png'),fullPage:true});
 const initialResult=await page.evaluate(async id=>(await(await fetch('/api/collections/'+id+'/fund-review/results?limit=50')).json()),initial.id);expect(initialResult.summary.row_count).toBeGreaterThan(50000);expect(initialResult.summary.financially_verified).toBe(false);expect(initialResult.tables.some((t:any)=>/Investor-Level GL/i.test(t.title))).toBe(true);expect(initialResult.suggestions.length).toBeGreaterThan(0);
 // This test rule is an explicitly chosen requirement for the supplied reference pack,
 // not a default rule and not an assertion that an approval cell proves legal approval.
 const gaps=initialResult.tables.find((t:any)=>t.title.startsWith('Mapping Gaps'));expect(gaps).toBeTruthy();const approval=gaps.columns.find((c:any)=>c.label==='Approval');expect(approval).toBeTruthy();
 let dialog=page.getByRole('dialog',{name:'Checks for this review'});if(!checkAlreadyConfirmed){ await page.getByRole('button',{name:'Choose checks for this pack',exact:true}).click();dialog=page.getByRole('dialog',{name:'Checks for this review'});await dialog.getByRole('button',{name:'Add a check',exact:true}).click();await dialog.getByRole('combobox',{name:'What do you want to check?',exact:true}).selectOption('required');await dialog.getByLabel('Give the check a clear name').fill('Mapping proposals have a recorded approval');await dialog.getByRole('combobox',{name:'Source table',exact:true}).selectOption(gaps.dataset_id);await dialog.getByRole('checkbox',{name:'Approval',exact:true}).check();await dialog.getByRole('checkbox',{name:/I checked these selections/}).check();const saving=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname.endsWith('/fund-review'));await dialog.getByRole('button',{name:'Save and check',exact:true}).click();expect((await saving).ok()).toBe(true);await settled();
 }
 const checked=await page.evaluate(async id=>(await(await fetch('/api/collections/'+id+'/fund-review/results?limit=500')).json()),initial.id);const finding=checked.findings.find((f:any)=>f.title==='Mapping proposals have a recorded approval');expect(finding.status).toBe('difference');expect(finding.affected_count).toBe(2);
 await page.getByLabel('Search findings',{exact:true}).fill('Mapping proposals have a recorded approval');await page.locator('.fr-finding').filter({hasText:'Mapping proposals have a recorded approval'}).first().click();dialog=page.getByRole('dialog',{name:'Finding and supporting evidence'});await dialog.getByRole('button',{name:'See complete source record',exact:true}).first().click();await expect(dialog.locator('.fr-evidence .fr-record').first()).toBeVisible();await page.screenshot({path:info.outputPath('fund-review-source-evidence.png'),fullPage:true});
 await dialog.getByRole('button',{name:'Inspect or correct this extraction',exact:true}).first().click();dialog=page.getByRole('dialog',{name:'Source documents'});await expect(dialog.locator('.collection-cell[aria-pressed="true"]').first()).toBeVisible();await expect(dialog.getByLabel('Corrected value',{exact:true})).toBeEnabled();await dialog.getByLabel('Corrected value',{exact:true}).fill('Isolated test: review decision recorded');await dialog.getByLabel('Reason and source evidence',{exact:true}).fill('Acceptance test only: complete one real missing approval field to verify source correction propagation. Original workbook remains unchanged.');const edit=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname.endsWith('/edits'));await dialog.getByRole('button',{name:'Save extraction decision',exact:true}).click();expect((await edit).ok()).toBe(true);await dialog.getByRole('button',{name:'Close panel',exact:true}).click();await settled();
 const corrected=await page.evaluate(async id=>(await(await fetch('/api/collections/'+id+'/fund-review/results?limit=500')).json()),initial.id);const remaining=corrected.findings.find((f:any)=>f.title==='Mapping proposals have a recorded approval');expect(remaining.status).toBe('difference');expect(remaining.affected_count).toBe(1);expect(corrected.summary.financially_verified).toBe(false);
 await page.getByRole('button',{name:'History',exact:true}).click();dialog=page.getByRole('dialog',{name:'Review history'});await expect(dialog.getByText(/Acceptance test only: complete one real missing approval field/)).toBeVisible();await page.screenshot({path:info.outputPath('fund-review-history.png'),fullPage:true});await dialog.getByRole('button',{name:'Close panel',exact:true}).click();
 const originalHash=createHash('sha256').update(readFileSync(files.reference)).digest('hex');const storedHash=await page.evaluate(async({id,source})=>{const response=await fetch('/api/collections/'+id+'/sources/'+source+'/download');const bytes=await response.arrayBuffer();const hash=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(hash)).map(n=>n.toString(16).padStart(2,'0')).join('');},{id:initial.id,source:gaps.source_id});expect(storedHash).toBe(originalHash);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download brief',exact:true}).click();const file=await download;expect(await file.failure()).toBeNull();await file.saveAs(info.outputPath('working-fund-review.html'));const html=readFileSync(info.outputPath('working-fund-review.html'),'utf8');expect(html).toContain('Mapping proposals have a recorded approval');expect(html).toMatch(/working|unresolved/i);await page.screenshot({path:info.outputPath('fund-review-corrected-brief.png'),fullPage:true});
 await page.reload();await expect(page.getByRole('heading',{name:'Acceptance · real private-markets reporting pack'})).toBeVisible();await expect(page.getByRole('button',{name:'Download brief',exact:true})).toBeVisible();
});

test('actual Excel revision preserves originals and resolves the same required check',async({page},info)=>{
 test.skip(!fixturePath,'Actual private input manifest required.');test.setTimeout(600000);page.setDefaultTimeout(20000);const files=JSON.parse(readFileSync(fixturePath!,'utf8')) as {reference:string;revision?:string};test.skip(!files.revision,'Supply the independently ledgered revision of the actual reference workbook.');const id=completedReviewId??process.env.CLOSEGRAPH_FUND_REUSE_REVIEW_ID;if(!id)throw Error('Complete the real-file review test first or supply its isolated review ID.');
 await login(page);const saved=await page.evaluate(async id=>{const all=await(await fetch('/api/collections')).json();const work=await(await fetch('/api/collections/'+id)).json();const result=await(await fetch('/api/collections/'+id+'/fund-review/results?limit=500')).json();return {work,result,index:all.findIndex((item:any)=>item.id===id)};},id);expect(saved.index).toBeGreaterThanOrEqual(0);const existing=saved.result.findings.find((f:any)=>f.title==='Mapping proposals have a recorded approval');expect(existing.status).toBe('difference');expect(existing.affected_count).toBe(1);const oldTable=saved.result.tables.find((t:any)=>t.title.startsWith('Mapping Gaps'));const oldSource=saved.work.sources.find((source:any)=>source.id===oldTable.source_id);expect(oldSource).toBeTruthy();
 await page.getByRole('button',{name:'Recent work',exact:true}).click();await page.locator('.fr-recent-list article').nth(saved.index).getByRole('button',{name:'Open work'}).click();await page.getByRole('button',{name:'Documents',exact:true}).click();let dialog=page.getByRole('dialog',{name:'Source documents'});await dialog.locator('.evidence-document-list button').filter({hasText:oldSource.filename}).click();await dialog.getByRole('button',{name:'Upload new version',exact:true}).click();await dialog.getByLabel('Replacement file',{exact:true}).setInputFiles(files.revision!);await dialog.getByLabel('What changed?',{exact:true}).fill('Isolated acceptance revision: two recorded review fields supplied in Excel. The independently checked mutation ledger limits the change to these cells.');const upload=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/collections/'+id+'/sources');const run=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/collections/'+id+'/fund-review');await dialog.getByRole('button',{name:'Save new version',exact:true}).click();const uploaded=await upload;expect(uploaded.ok(),await uploaded.text()).toBe(true);expect((await run).ok()).toBe(true);await dialog.getByRole('button',{name:'Close panel',exact:true}).click();await expect.poll(async()=>page.evaluate(async id=>{const work=await(await fetch('/api/collections/'+id)).json();return work.fund_review?.status;},id),{timeout:420000,intervals:[2000,5000]}).toBe('COMPLETE');
 const revised=await page.evaluate(async id=>({work:await(await fetch('/api/collections/'+id)).json(),result:await(await fetch('/api/collections/'+id+'/fund-review/results?limit=500')).json()}),id);const passed=revised.result.findings.find((f:any)=>f.title==='Mapping proposals have a recorded approval');expect(passed.status).toBe('passed');expect(revised.result.summary.financially_verified).toBe(false);expect(revised.result.changes.fixed).toBeGreaterThan(0);const currentDocument=revised.work.documents.find((document:any)=>document.id===oldSource.document_id);expect(currentDocument.current_revision_id).not.toBe(oldSource.id);expect(currentDocument.revisions).toHaveLength(2);
 async function originalHash(source:string){return page.evaluate(async({id,source})=>{const bytes=await(await fetch('/api/collections/'+id+'/sources/'+source+'/download')).arrayBuffer();const digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest)).map(n=>n.toString(16).padStart(2,'0')).join('');},{id,source});}
 expect(await originalHash(oldSource.id)).toBe(createHash('sha256').update(readFileSync(files.reference)).digest('hex'));expect(await originalHash(currentDocument.current_revision_id)).toBe(createHash('sha256').update(readFileSync(files.revision!)).digest('hex'));
 await expect(page.getByRole('button',{name:'Download brief',exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('fund-review-excel-revision-fixed.png'),fullPage:true});await page.getByRole('button',{name:'History',exact:true}).click();dialog=page.getByRole('dialog',{name:'Review history'});await expect(dialog.getByText(/Isolated acceptance revision: two recorded review fields/)).toBeVisible();await expect(dialog.getByText('Fixed',{exact:true}).first()).toBeVisible();await page.screenshot({path:info.outputPath('fund-review-excel-revision-history.png'),fullPage:true});await dialog.getByRole('button',{name:'Close panel',exact:true}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download brief',exact:true}).click();const file=await download;expect(await file.failure()).toBeNull();await file.saveAs(info.outputPath('working-fund-review-after-excel.html'));expect(readFileSync(info.outputPath('working-fund-review-after-excel.html'),'utf8')).toContain('Mapping proposals have a recorded approval');
});
