import {test,expect} from './fixtures';
import {readFileSync} from 'node:fs';
import type {Page} from '@playwright/test';
test.use({trace:'off'});
const configPath=process.env.CLOSEGRAPH_REAL_BANK_FILES;
function required(name:string){const value=process.env[name];if(!value)throw Error(name+' required');return value;}
async function expand(page:Page,label:string){const summary=page.locator('summary').filter({hasText:label}).first();if(!await summary.evaluate(e=>e.parentElement?.hasAttribute('open')))await summary.click();}
test('real bank documents: upload, interpret, inspect differences and download',async({page},info)=>{
 test.skip(!configPath,'Set CLOSEGRAPH_REAL_BANK_FILES to the private actual-file manifest.');test.setTimeout(600000);page.setDefaultTimeout(15000);
 const files=JSON.parse(readFileSync(configPath!,'utf8')) as {statements:string[];journal:string};expect(files.statements.length).toBeGreaterThan(1);
 await page.goto('/');await page.getByLabel('Username',{exact:true}).fill(required('CLOSEGRAPH_TEST_PREPARER_USERNAME'));await page.getByLabel('Password',{exact:true}).fill(required('CLOSEGRAPH_TEST_PREPARER_PASSWORD'));await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Do your bank records agree?'})).toBeVisible();await page.getByLabel('Bank statements',{exact:true}).setInputFiles(files.statements);await page.getByLabel('Journal or working workbook',{exact:true}).setInputFiles(files.journal);
 const start=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname.endsWith('/reconciliation'));
 await page.getByRole('button',{name:'Reconcile documents →'}).click();const response=await start;expect(response.ok(),await response.text()).toBe(true);const first=await response.json();
 async function settled(){await expect.poll(async()=>page.evaluate(async id=>{const r=await fetch('/api/collections/'+id);const w=await r.json();return !['QUEUED','PROCESSING'].includes(w.status)&&w.reconciliation?.status==='COMPLETE';},first.id),{timeout:120000}).toBe(true);await expect(page.getByRole('button',{name:'Compare again',exact:true})).toBeVisible({timeout:30000});await expect(page.getByRole('button',{name:'Compare again',exact:true})).toBeEnabled();}
 async function commit(action:()=>Promise<unknown>){const response=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname.endsWith('/reconciliation'));await action();const r=await response;expect(r.ok(),await r.text()).toBe(true);await settled();await expand(page,'Document interpretation');}
 await settled();await page.screenshot({path:info.outputPath('real-bank-initial.png'),fullPage:true});
 await expand(page,'Choose the journal transaction table');await expect(page.getByRole('combobox',{name:'Transaction table',exact:true}).locator('option').filter({hasText:/DIU/i})).toHaveCount(1,{timeout:30000});const options=await page.getByRole('combobox',{name:'Transaction table',exact:true}).locator('option').allTextContents();const journalTitle=options.find(t=>/DIU/i.test(t));if(!journalTitle)throw Error('Actual workbook DIU table was not exposed');await page.getByRole('combobox',{name:'Transaction table',exact:true}).selectOption({label:journalTitle});
 await commit(()=>page.getByRole('button',{name:'Use this table; keep the others as evidence'}).click());
 await expand(page,'Document interpretation');
 // The fixture choices describe the real workbook's accounting contract; they are never product defaults.
 let card=page.locator('.interpretation').filter({has:page.locator('summary').filter({hasText:/DIU/i})}).first();if(!await card.evaluate(e=>e.hasAttribute('open')))await card.locator(':scope > summary').click();
 for(const [label,value] of Object.entries({Account:'c24',Currency:'c11',Date:'c10',Amount:'c15',Batch:'c6'}))await card.getByRole('combobox',{name:label,exact:true}).selectOption(value);
 await card.getByRole('combobox',{name:'Date order',exact:true}).selectOption('excel_1900');await card.getByRole('combobox',{name:'Number format',exact:true}).selectOption('dot_decimal');
 await card.locator('summary').filter({hasText:'Or select cash entries'}).click();await card.getByRole('combobox',{name:'Cash account column',exact:true}).selectOption('c2');
 const cashValues=await page.evaluate(async id=>{const w=await(await fetch('/api/collections/'+id)).json();const d=w.datasets.find((d:{title:string})=>/DIU/i.test(d.title));let offset=0;const values=new Set<string>();while(true){const p=await(await fetch('/api/collections/'+id+'/datasets/'+d.id+'/rows?offset='+offset+'&limit=500')).json();for(const r of p.rows){const value=r.values.c2;if(typeof value==='string'&&value.startsWith('Cash -'))values.add(value);}offset+=p.rows.length;if(offset>=p.total||!p.rows.length)break;}return [...values].join(', ');},first.id);
 expect(cashValues).not.toBe('');await card.getByLabel('Cash account values, separated by commas').fill(cashValues);await card.locator('summary').filter({hasText:'Direction and reference mappings'}).click();await card.getByRole('combobox',{name:'Transaction direction column',exact:true}).selectOption('c14');await card.getByLabel('Values meaning money in (comma separated)').fill('Yes');await card.getByLabel('Values meaning money out (comma separated)').fill('No');await card.getByLabel('Values meaning money out (comma separated)').blur();
 await card.getByRole('button',{name:'Add exact reference lookup'}).click();await card.getByRole('combobox',{name:'Use this transaction column',exact:true}).selectOption('c24');const referenceOptions=await card.getByRole('combobox',{name:'Reference table',exact:true}).locator('option').allTextContents();const accountMap=referenceOptions.find(t=>/account.*map/i.test(t));expect(accountMap).toBeTruthy();await card.getByRole('combobox',{name:'Reference table',exact:true}).selectOption({label:accountMap!});await card.getByRole('combobox',{name:'Match against',exact:true}).selectOption('c2');await card.getByRole('combobox',{name:'Return value from',exact:true}).selectOption('c1');
 await commit(()=>card.getByRole('button',{name:'Use these choices and compare'}).click());
 // Confirmations are performed only for this independently checked test corpus.
 await commit(()=>page.getByRole('checkbox',{name:/I checked the extracted transactions against all/}).click());
 await commit(()=>page.getByRole('combobox',{name:'Reference matching approach',exact:true}).selectOption('composite'));await commit(()=>page.getByRole('checkbox',{name:/When no unique reference exists/}).click());
 const final=await page.evaluate(async id=>(await(await fetch('/api/collections/'+id+'/reconciliation/results?limit=1')).json()),first.id);expect(final.summary.statement_records).toBe(100);expect(final.summary.journal_records).toBe(100);expect(final.summary.matched).toBe(77);await expect(page.getByRole('button',{name:'View item'}).first()).toBeVisible();await page.getByRole('button',{name:'View item'}).first().click();await expect(page.getByRole('complementary',{name:'Resolve transaction'})).toBeVisible();await expect(page.getByRole('complementary',{name:'Resolve transaction'}).getByText(/Bank statement/).first()).toBeVisible();await page.screenshot({path:info.outputPath('real-bank-evidence.png'),fullPage:true});await page.getByRole('complementary',{name:'Resolve transaction'}).getByRole('button',{name:'Close ×'}).click();
 const download=page.waitForEvent('download');await page.getByRole('link',{name:'Download reconciliation',exact:true}).click();const file=await download;expect(await file.failure()).toBeNull();await file.saveAs(info.outputPath('real-bank-working-reconciliation.csv'));expect(readFileSync(info.outputPath('real-bank-working-reconciliation.csv'),'utf8')).toContain('matched');await page.screenshot({path:info.outputPath('real-bank-results.png'),fullPage:true});
});

test('actual workbook correction is reevaluated and restored through the UI',async({page},info)=>{
 test.skip(!configPath,'Actual bank fixture is required.');test.setTimeout(180000);page.setDefaultTimeout(20000);
 await page.goto('/');await page.getByLabel('Username',{exact:true}).fill(required('CLOSEGRAPH_TEST_PREPARER_USERNAME'));await page.getByLabel('Password',{exact:true}).fill(required('CLOSEGRAPH_TEST_PREPARER_PASSWORD'));await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Do your bank records agree?'})).toBeVisible();
 const data=await page.evaluate(async()=>{const all=await(await fetch('/api/collections')).json();const w=all.find((x:any)=>x.reconciliation?.summary?.matched===77&&x.reconciliation?.summary?.statement_records===100);if(!w)throw Error('Run the real-bank baseline successfully before the correction check');const full=await(await fetch('/api/collections/'+w.id)).json();const ds=full.datasets.find((d:any)=>/DIU/i.test(d.title));const rows=await(await fetch('/api/collections/'+w.id+'/datasets/'+ds.id+'/rows?limit=50')).json();const results=await(await fetch('/api/collections/'+w.id+'/reconciliation/results?status=matched&limit=500')).json();const item=results.items.find((x:any)=>x.journal.length===1&&rows.rows.some((r:any)=>r.row_id===x.journal[0].row_id));if(!item)throw Error('No matched cash entry in first DIU page');const index=rows.rows.findIndex((r:any)=>r.row_id===item.journal[0].row_id);return {id:w.id,index:all.findIndex((x:any)=>x.id===w.id),dataset:ds.id,filename:full.sources.find((s:any)=>s.id===ds.source_id).filename,row:index+1,column:rows.columns.find((c:any)=>c.key==='c15').label,original:rows.rows[index].values.c15};});
 await page.getByRole('button',{name:'Recent work',exact:true}).click();await page.locator('.recent-list > button').nth(data.index).click();await expect(page.getByRole('button',{name:'Documents',exact:true})).toBeVisible();
 async function edit(value:string,oldValue:string,reason:string){await page.getByRole('button',{name:'Documents',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Source documents'});await dialog.locator('.evidence-document-list button').filter({hasText:data.filename}).click();await dialog.getByRole('combobox',{name:'Part of this document',exact:true}).selectOption(data.dataset);await dialog.getByRole('button',{name:data.column+', row '+data.row+': '+oldValue,exact:true}).click();await dialog.getByLabel('Corrected value',{exact:true}).fill(value);await dialog.getByLabel('Reason and source evidence',{exact:true}).fill(reason);const result=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/collections/'+data.id+'/edits');await dialog.getByRole('button',{name:'Save extraction decision',exact:true}).click();const response=await result;expect(response.ok(),await response.text()).toBe(true);await dialog.getByRole('button',{name:'Close ×',exact:true}).click();await expect.poll(async()=>page.evaluate(async id=>{const w=await(await fetch('/api/collections/'+id)).json();return w.reconciliation?.status;},data.id),{timeout:120000}).toBe('COMPLETE');await expect(page.getByRole('button',{name:'Documents',exact:true})).toBeEnabled();}
 const altered=String(Number(data.original)+1);await edit(altered,data.original,'Isolated acceptance test: deliberately add one to a real matched cash amount to verify discrepancy propagation.');const changed=await page.evaluate(async id=>(await(await fetch('/api/collections/'+id+'/reconciliation/results?limit=1')).json()),data.id);expect(changed.summary.matched).toBeLessThan(77);await page.screenshot({path:info.outputPath('real-correction-detected.png'),fullPage:true});
 await edit(data.original,altered,'Restore the exact original value after the deliberate fault; independently checked against the supplied workbook.');const restored=await page.evaluate(async id=>(await(await fetch('/api/collections/'+id+'/reconciliation/results?limit=1')).json()),data.id);expect(restored.summary.matched).toBe(77);expect(restored.summary.statement_records).toBe(100);expect(restored.summary.journal_records).toBe(100);const download=page.waitForEvent('download');await page.getByRole('link',{name:'Download reconciliation',exact:true}).click();const file=await download;await file.saveAs(info.outputPath('real-bank-restored-reconciliation.csv'));await page.screenshot({path:info.outputPath('real-correction-restored.png'),fullPage:true});
});
