import { useCallback, useEffect, useId, useRef, useState } from 'react';
import { Alert, Button, Card, Input } from './components/ui';
import { Field } from './components/closegraph/Field';
import { ApiError, ClosegraphApi } from './lib/api';
import { canPrepare, type PackSnapshot, type Session } from './lib/model';
import type { ReviewWork } from './features/packs/ReviewWork';
import { PackReview } from './features/packs/PackReview';
import { UploadPanel } from './features/packs/UploadPanel';
const api=new ClosegraphApi();
function Login({onLogin}:{onLogin:(session:Session)=>void}) {
 const id=useId(),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[pending,setPending]=useState(false),ref=useRef<HTMLInputElement>(null);
 async function submit(e:React.FormEvent){e.preventDefault();if(!username||!password){setError('Enter your username and password.');ref.current?.focus();return;}setPending(true);setError('');try{onLogin(await api.login(username,password));}catch(error){setError((error as Error).message);}finally{setPending(false);}}
 return <main className="login"><Card><div className="brand"><span className="brand-mark" aria-hidden/>CloseGraph</div><h1>Sign in to review a pack</h1><p className="muted">Use your scoped local account. Preparation and independent review use separate identities.</p>{error&&<div role="alert"><Alert title="Sign-in failed" tone="danger">{error}</Alert></div>}<form onSubmit={submit} noValidate><Field id={id+'-username'} label="Username"><Input id={id+'-username'} ref={ref} autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required disabled={pending}/></Field><Field id={id+'-password'} label="Password"><Input id={id+'-password'} type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required disabled={pending}/></Field><Button type="submit" disabled={pending}>{pending?'Signing in…':'Sign in'}</Button></form></Card></main>;
}
export default function App(){
 const [session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(true),[packs,setPacks]=useState<PackSnapshot[]>([]),[pack,setPack]=useState<PackSnapshot|null>(null),[pending,setPending]=useState(false),[error,setError]=useState(''),[announcement,setAnnouncement]=useState('');
 const [uploadOpen,setUploadOpen]=useState(false);
 const [reviewWork,setReviewWork]=useState<ReviewWork>(),[reviewWorkError,setReviewWorkError]=useState('');
 const authKey=useRef<string|null>(null);authKey.current=session?.csrf_token??null;
 const currentId=useRef<string|null>(null);currentId.current=pack?.pack_id??null;
 useEffect(()=>{let live=true;api.session().then(s=>{if(live)setSession(s);}).catch(err=>{if(live&&!(err instanceof ApiError&&err.status===401))setError((err as Error).message);}).finally(()=>{if(live)setChecking(false);});return()=>{live=false;};},[]);
 const handleError=useCallback((err:unknown)=>{if(err instanceof ApiError&&err.status===401){setSession(null);setPack(null);setPacks([]);}setError((err as Error).message);},[]);
 const loadPacks=useCallback(async()=>{const key=authKey.current;setError('');try{const list=await api.list();if(!key||authKey.current!==key)return;const selected=list.find(p=>p.pack_id===currentId.current)??list[0];const detail=selected?await api.pack(selected.pack_id):null;if(authKey.current!==key)return;setPacks(list);setPack(detail);}catch(err){if(authKey.current===key)handleError(err);}},[handleError]);
 useEffect(()=>{if(session)void loadPacks();},[session,loadPacks]);
 useEffect(()=>{if(!pack||!['PENDING','RUNNING','QUEUED'].includes(pack.execution_status.toUpperCase()))return;const id=pack.pack_id,key=authKey.current,controller=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const fresh=await api.pack(id,controller.signal);if(!controller.signal.aborted&&authKey.current===key&&currentId.current===id){setPack(fresh);if(['PENDING','RUNNING','QUEUED'].includes(fresh.execution_status.toUpperCase()))timer=setTimeout(()=>void poll(),1000);else setAnnouncement('Version '+fresh.version+' processing '+fresh.execution_status.toLowerCase()+'. Review is '+fresh.review_status.toLowerCase().replaceAll('_',' ')+'.');}}catch(err){if(!controller.signal.aborted&&authKey.current===key&&(err as Error).name!=='AbortError')handleError(err);}};timer=setTimeout(()=>void poll(),1000);return()=>{controller.abort();clearTimeout(timer);};},[pack?.pack_id,pack?.version,pack?.execution_status,handleError]);
 useEffect(()=>{setReviewWork(undefined);setReviewWorkError('');if(!pack||!session)return;const controller=new AbortController(),key=authKey.current;api.reviewWork(pack.pack_id,controller.signal).then(work=>{if(!controller.signal.aborted&&authKey.current===key)setReviewWork(work);}).catch(err=>{if(!controller.signal.aborted&&authKey.current===key)setReviewWorkError((err as Error).message);});return()=>controller.abort();},[pack?.pack_id,pack?.version,session]);
 async function mutate(action:()=>Promise<PackSnapshot>){const key=authKey.current;if(pending)throw new Error('Wait for the current action to complete.');setPending(true);setError('');try{const result=await action();if(authKey.current!==key)return;setPack(result);setPacks(list=>list.map(p=>p.pack_id===result.pack_id?result:p));setAnnouncement('Version '+result.version+' saved. Processing '+result.execution_status.toLowerCase()+'.');}catch(err){if(authKey.current!==key)throw err;handleError(err);if(err instanceof ApiError&&err.status===409&&pack){try{const fresh=await api.pack(pack.pack_id);if(authKey.current===key&&currentId.current===pack.pack_id)setPack(fresh);}catch{}}throw err;}finally{setPending(false);}}
 async function logout(){setPending(true);try{await api.logout();authKey.current=null;setSession(null);setPack(null);setPacks([]);setError('');}catch(err){handleError(err);}finally{setPending(false);}}
 if(checking)return <main className="login"><p role="status">Checking your local session…</p></main>;
 if(!session)return <Login onLogin={s=>{setSession(s);setError('');}}/>;
 if(!pack)return <main className="login"><Card><h1>Your reporting packs</h1>{error?<div role="alert"><Alert title="Packs could not be loaded" tone="danger">{error}</Alert></div>:<p>No pack is assigned to your session. A locally provisioned scope is required.</p>}<div className="controls"><Button onClick={()=>void loadPacks()}>Reload packs</Button><Button variant="outline" onClick={()=>void logout()}>Sign out</Button></div></Card></main>;
 const selected=pack;
 const toolbar=<div className="story-settings"><div className="topbar-actions"><div><label className="label" htmlFor="active-pack">Reporting pack</label><select className="input" id="active-pack" value={pack.pack_id} disabled={pending} onChange={e=>{setError('');const key=authKey.current;void api.pack(e.target.value).then(result=>{if(authKey.current===key)setPack(result);}).catch(err=>{if(authKey.current===key)handleError(err);});}}>{packs.map(p=><option value={p.pack_id} key={p.pack_id}>{p.title} · {p.fund_id}</option>)}</select></div>{canPrepare(session)&&<UploadPanel open={uploadOpen} onOpenChange={setUploadOpen} pack={pack} pending={pending} onUpload={input=>mutate(()=>api.upload(selected.pack_id,input))}/>}<Button variant="link" disabled={pending} onClick={()=>void loadPacks()}>Refresh current version</Button></div></div>;
 return <PackReview reviewWork={reviewWork} reviewWorkError={reviewWorkError} pack={pack} session={session} pending={pending} error={error} announcement={announcement} toolbar={toolbar} onLogout={()=>void logout()} actions={{replaceSource:()=>setUploadOpen(true),observe:async input=>{const key=authKey.current;await api.recordEvent(selected.pack_id,input);const work=await api.reviewWork(selected.pack_id);if(authKey.current===key&&currentId.current===selected.pack_id){setReviewWork(work);setReviewWorkError('');}},correct:input=>mutate(()=>api.correct(selected.pack_id,input)),recompute:()=>mutate(()=>api.recompute(selected.pack_id,selected.version)),review:input=>mutate(()=>api.review(selected.pack_id,input)),resolve:input=>mutate(()=>api.resolve(selected.pack_id,input)),reject:input=>mutate(()=>api.reject(selected.pack_id,input)),publish:()=>mutate(()=>api.publish(selected.pack_id,selected.version))}}/>;
}
