import { Badge, Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '../ui';
import { humanize, type Check, type PackSnapshot } from '../../lib/model';
export function CheckBadge({status}:{status:Check['status']}) {
  const styles = { PASS:['success','✓ Passed'], FAIL:['danger','× Failed'], UNKNOWN:['warning','! Unknown'], NOT_RUN:['warning','! Not checked'], NOT_APPLICABLE:['neutral','— Not applicable'] } as const;
  const [tone,label] = styles[status] ?? styles.UNKNOWN;
  return <Badge tone={tone}>{label}</Badge>;
}
export function CheckList({checks}:{checks:Check[]}) { return <ul className="check-list">{checks.map(check=><li key={check.id}><div className="check-line"><strong>{check.label}</strong><CheckBadge status={check.status}/></div><p>{check.detail}</p><p className="caption">{check.required ? 'Required relationship' : 'Additional check'}</p></li>)}</ul>; }
export function StatusDetails({pack}:{pack:PackSnapshot}) {
 const pass=pack.checks.filter(c=>c.status==='PASS').length;
 return <Accordion type="multiple" className="accordion"><AccordionItem value="state"><AccordionTrigger>Processing and review details</AccordionTrigger><AccordionContent className="accordion-body"><dl className="status-grid"><div><dt>Processing</dt><dd>{humanize(pack.execution_status)}</dd></div><div><dt>Checks</dt><dd>{pass} of {pack.checks.length} passed</dd></div><div><dt>Review routing</dt><dd>{humanize(pack.routing_status)}</dd></div><div><dt>Approval</dt><dd>{humanize(pack.review_status)}</dd></div><div><dt>Version currency</dt><dd>{humanize(pack.freshness)}</dd></div><div><dt>Routing policy</dt><dd>{pack.policy_version ?? 'See check evidence'}</dd></div></dl><p>Passing the declared checks makes this snapshot eligible for independent review. Processing completion is separate from financial approval.</p>{[...new Set([...(pack.routing_reasons??[]),...(pack.routing_explanation?.reasons??[])])].map((reason,i)=><p key={i}>{reason}</p>)}{pack.routing_explanation&&<div className="separator"><h3>Recorded routing evidence</h3><p>Policy {pack.routing_explanation.policy_version} · {pack.routing_explanation.required_check_coverage[0]} of {pack.routing_explanation.required_check_coverage[1]} required relationships satisfied.</p><p>Reader agreement: {humanize(pack.routing_explanation.agreement)}. Recorded reader signal: {humanize(pack.routing_explanation.confidence.status)}{pack.routing_explanation.confidence.value!=null?' · '+pack.routing_explanation.confidence.value:''}.</p>{pack.routing_explanation.confidence.reason&&<p>{pack.routing_explanation.confidence.reason}</p>}<p>This signal describes the recorded evidence; it is not a probability that the financial output is correct. Approval is recorded separately above.</p></div>}{pack.priority&&<div className="separator"><h3>Review priority</h3><p>{pack.priority.status==='AVAILABLE'&&pack.priority.level?humanize(pack.priority.level)+' within this review route':'Unavailable: no applicable configured priority threshold'}</p>{pack.priority.status==='AVAILABLE'&&<p>Policy {pack.priority.policy_version} · declared amount {pack.priority.currency} {pack.priority.amount_decimal??'unavailable'} · materiality threshold {pack.priority.materiality_decimal??'unavailable'} · dependent outputs {pack.priority.dependent_outputs??'unavailable'} · impact threshold {pack.priority.impact_threshold??'unavailable'}.</p>}{pack.priority.reasons.map((reason,i)=><p key={i}>{reason}</p>)}</div>}{pack.execution_error && <p className="field-error">{pack.execution_error}</p>}</AccordionContent></AccordionItem></Accordion>;
}

export function History({pack}:{pack:PackSnapshot}) {
 return <Accordion type="multiple" className="accordion"><AccordionItem value="history"><AccordionTrigger>Version and review history</AccordionTrigger><AccordionContent className="accordion-body">{pack.history.length===0?<p>No events recorded yet.</p>:[...pack.history].reverse().map((entry,i)=>{
 const note=entry.note ?? entry.reason;
 const at=entry.timestamp ?? entry.at;
 const actor=typeof entry.actor==='string'?entry.actor:entry.actor?JSON.stringify(entry.actor):'';
 return <div className="record" key={i}><strong>{entry.version ? 'Version '+entry.version+' · ' : ''}{entry.title ?? humanize(entry.action ?? 'Recorded event')}</strong>{note!=null&&<p>{String(note)}</p>}{entry.before!=null&&entry.after!=null&&<p>Changed from {String(entry.before)} to {String(entry.after)}.</p>}{actor&&<p>{actor}</p>}{at!=null&&<time dateTime={String(at)}>{String(at)}</time>}{entry.execution_status!=null&&<p>Processing: {humanize(String(entry.execution_status))}</p>}{entry.routing_status!=null&&<p>Review routing: {humanize(String(entry.routing_status))}</p>}{entry.checks && <Accordion type="multiple"><AccordionItem value={'checks-'+i}><AccordionTrigger>Check results saved with this version</AccordionTrigger><AccordionContent className="accordion-body"><CheckList checks={entry.checks}/></AccordionContent></AccordionItem></Accordion>}</div>;
 })}</AccordionContent></AccordionItem></Accordion>;
}
