import { useState } from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { expect, userEvent, within } from 'storybook/test';
import { Button } from '../../components/ui';
import { Field } from '../../components/closegraph/Field';
import { initialScenario, scenarios, snapshot, transition, type ScenarioId, type SyntheticAction } from '../../lib/synthetic';
import { PackReview } from './PackReview';
import type { Page } from '../../lib/model';
const initialPages:Record<ScenarioId,Page>={correction:'overview',missing:'overview',disagreement:'correction',dependency:'checks',provider:'overview',ready:'review',stale:'review',template:'review'};
export function Scenario({scenario}:{scenario:ScenarioId}){
 const [state,setState]=useState(()=>initialScenario(scenario)),[error,setError]=useState(''),[announcement,setAnnouncement]=useState(''),[exported,setExported]=useState(false);
 const pack=snapshot(state);
 async function act(action:SyntheticAction){setError('');try{const next=transition(state,action);setState(next);setAnnouncement('Synthetic version '+next.version+' updated. Original history retained.');}catch(error){setError((error as Error).message);throw error;}}
 const toolbar=<section className="story-settings" aria-label="Synthetic example settings"><strong>Explore this example</strong><p className="muted">Fictional fund data. Actions change this Storybook example; no files are sent or published.</p><div className="story-settings-controls"><Field id="story-scenario" label="Scenario"><select id="story-scenario" className="input" value={state.scenario} onChange={e=>{setState(initialScenario(e.target.value as ScenarioId));setExported(false);setError('');}}>{scenarios.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field id="story-person" label="Person using the example"><select id="story-person" className="input" value={state.role} onChange={e=>void act({type:'role',role:e.target.value as 'accountant'|'reviewer'})}><option value="accountant">Jamie · Accountant</option><option value="reviewer">Morgan · Independent reviewer</option></select></Field><Button variant="outline" onClick={()=>{setState(initialScenario(state.scenario));setError('');setExported(false);}}>Restart this scenario</Button></div></section>;
 const storyActions=(state.scenario==='missing'&&!state.evidence)||(!state.capitalFresh&&state.fee==='60000.00')||state.stale||exported ? <>{state.scenario==='missing'&&!state.evidence&&<Button variant="outline" disabled={state.role!=='accountant'} onClick={()=>void act({type:'receive'})}>Add example agreement</Button>}{!state.capitalFresh&&state.fee==='60000.00'&&<Button disabled={state.role!=='accountant'} onClick={()=>void act({type:'repair'})}>Update capital statement</Button>}{state.stale&&<Button disabled={state.role!=='accountant'} onClick={()=>void act({type:'recheck'})}>Recheck source version</Button>}{exported&&<p>Example export: synthetic-harbour-q2-v{state.version}-reviewed.xlsx and review-manifest.json. No files were generated.</p>}</> : null;
 return <PackReview key={state.scenario} pack={pack} session={{username:state.role==='reviewer'?'Morgan Ellis (synthetic)':'Jamie Park (synthetic)',role:state.role,csrf_token:'storybook-only'}} initialPage={initialPages[state.scenario]} toolbar={toolbar} synthetic error={error} announcement={announcement} storyActions={storyActions} actions={{correct:input=>act({type:'correct',value:input.value_decimal,reason:input.reason}),recompute:()=>act({type:'recheck'}),resolve:input=>act({type:'resolve',note:input.reason}),review:input=>act({type:'approve',note:input.note,attested:input.attested}),publish:async()=>{if(pack.review_status!=='APPROVED')throw new Error('Independent approval required.');setExported(true);}}}/>;
}
const meta={title:'CloseGraph/Workflows',component:Scenario,parameters:{layout:'fullscreen'},tags:['autodocs']} satisfies Meta<typeof Scenario>;
export default meta;type Story=StoryObj<typeof meta>;
export const FeeCorrection:Story={name:'Fee correction — start here',args:{scenario:'correction'},play:async({canvasElement})=>{const canvas=within(canvasElement);await expect(canvas.getByRole('heading',{name:'Q2 reporting pack'})).toBeVisible();await userEvent.click(canvas.getByRole('link',{name:'Correction'}));await expect(canvas.getByRole('tab',{name:'Fee rule'})).toHaveAttribute('aria-selected','true');await userEvent.click(canvas.getByRole('link',{name:'Overview'}));}};
export const MissingAgreement:Story={name:'Missing fee agreement',args:{scenario:'missing'}};
export const ReaderDisagreement:Story={name:'Document readers disagree',args:{scenario:'disagreement'},play:async({canvasElement})=>{const canvas=within(canvasElement);await expect(canvas.getByRole('button',{name:'Record review resolution'})).toBeVisible();}};
export const UnknownDependency:Story={name:'Unknown effect on a statement',args:{scenario:'dependency'}};
export const ProviderUnavailable:Story={name:'PDF processing unavailable',args:{scenario:'provider'}};
export const ReadyForReview:Story={name:'Ready for independent review',args:{scenario:'ready'},play:async({canvasElement})=>{const canvas=within(canvasElement);await expect(canvas.getByRole('button',{name:'Approve version 4'})).toBeDisabled();await userEvent.click(canvas.getByText('I have reviewed version 4, the candidate workbook and its supporting evidence.'));await expect(canvas.getByRole('button',{name:'Approve version 4'})).toBeEnabled();await userEvent.click(canvas.getByRole('checkbox'));await expect(canvas.getByRole('button',{name:'Approve version 4'})).toBeDisabled();}};
export const StaleApproval:Story={name:'Source changed after approval',args:{scenario:'stale'}};
export const UnsupportedWorkbook:Story={name:'Unsupported workbook feature',args:{scenario:'template'}};
