import {accountLabel} from '../../lib/roles';
import { useEffect, useRef, useState } from 'react';
import { ArrowRight, RefreshCw } from 'lucide-react';
import { Alert, Button, Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '../../components/ui';
import { CheckList, History, StatusDetails } from '../../components/closegraph/Status';
import { snapshotVersion, canPrepare, eligibleForReview, formatFactValue, humanize, isApproved, isCurrent, locatorText, sourceOf, type Correction, type PackSnapshot, type Page, type Session } from '../../lib/model';
import { SourceEvidence, sourceEntries, sourceName, sourceTabForFact } from './SourceEvidence';
import { CorrectionPanel } from './CorrectionPanel';
import { ReviewDecision, ResolutionPanel, type ResolutionInput, type ReviewInput } from './ReviewDecision';
import { ReadySample,ReviewWorkReport,type ReviewEventInput,type ReviewWork } from './ReviewWork';
import { CandidatePreview, ReleasePanel } from './ReleasePanel';

export interface PackActions {replaceSource?:()=>void;observe?:(input:ReviewEventInput)=>Promise<void>;correct:(input:Correction)=>Promise<void>;recompute:()=>Promise<void>;review:(input:ReviewInput)=>Promise<void>;resolve:(input:ResolutionInput)=>Promise<void>;reject?:(input:{expected_version:number;note:string})=>Promise<void>;publish:()=>Promise<void>}
export interface PackReviewProps {reviewWork?:ReviewWork;reviewWorkError?:string;pack:PackSnapshot;session:Session;actions:PackActions;pending?:boolean;error?:string;announcement?:string;initialPage?:Page;onLogout?:()=>void;toolbar?:React.ReactNode;synthetic?:boolean;storyActions?:React.ReactNode}
const pages:[Page,string][]=[['overview','Overview'],['correction','Correction'],['checks','Checks'],['review','Approval']];
function pageFromHash():Page|undefined { const page=window.location.hash.slice(1);return pages.find(([id])=>id===page)?.[0]; }
export function PackReview({reviewWork,reviewWorkError,pack,session,actions,pending=false,error,announcement,initialPage='overview',onLogout,toolbar,synthetic=false,storyActions}:PackReviewProps) {
 const [page,setPage]=useState<Page>(initialPage),[factId,setFactId]=useState(pack.facts[0]?.fact_id??''),[sourceId,setSourceId]=useState<string|undefined>(undefined),mainRef=useRef<HTMLElement>(null),first=useRef(true);
 const [observing,setObserving]=useState(false),[observationError,setObservationError]=useState('');
 async function observe(event:Omit<ReviewEventInput,'observed_snapshot_version'>){if(!actions.observe)return;setObserving(true);setObservationError('');try{await actions.observe({...event,observed_snapshot_version:pack.version});}catch(error){setObservationError((error as Error).message);}finally{setObserving(false);}}
 function selectFact(id:string){const selected=pack.facts.find(f=>f.fact_id===id);if(!selected)return;setFactId(id);setSourceId(sourceTabForFact(pack,selected));}
 function inspectFact(id:string,sample=false){if(!pack.facts.some(f=>f.fact_id===id))return;void observe({event_type:sample?'READY_ITEM_SAMPLED':'VALUE_INSPECTED',fact_id:id});selectFact(id);navigate('correction');}
 const fact=pack.facts.find(f=>f.fact_id===factId)??pack.facts[0];
 useEffect(()=>{if(synthetic)return;const change=()=>setPage(pageFromHash()??'overview');change();window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[synthetic]);
 useEffect(()=>{if(first.current){first.current=false;return;}mainRef.current?.focus({preventScroll:true});},[page]);
 const navigate=(next:Page)=>{setPage(next);if(!synthetic)window.history.replaceState(null,'','#'+next);};
 const active=pack.checks.some(c=>c.required&&!['PASS','NOT_APPLICABLE'].includes(c.status));
 const processing=['PENDING','RUNNING','QUEUED'].includes(pack.execution_status.toUpperCase());
 const soft=pack.routing_status==='RESOLUTION_REQUIRED'||pack.unresolved_soft_signals||(pack.routing_status==='NEEDS_REVIEW'&&!pack.resolution);
 let task:{title:string;text:string;page?:Page;label?:string;tone:'warning'|'danger'|'info'}={title:'The pack is ready for independent review',text:'The declared checks passed. Inspect the values and evidence before approving this exact snapshot.',page:'review',label:'Review the updated pack',tone:'info'};
 if(processing)task={title:'Checking this pack version',text:'The latest request is processing. Checks, candidate output and review eligibility update when it completes.',tone:'info'};
 else if(pack.execution_status==='FAILED')task={title:'Processing needs attention',text:pack.execution_error??'Required processing is unavailable. Inspect the source and diagnostic before retrying.',page:'checks',label:'Inspect processing details',tone:'danger'};
 else if(!isCurrent(pack))task={title:'Source changed after approval',text:'Earlier approval covers a historical snapshot. Recheck this source version, then obtain new independent approval.',page:'checks',label:'Inspect current checks',tone:'warning'};
 else if(active)task={title:'This pack needs a correction',text:pack.checks.find(c=>c.required&&c.status!=='PASS')?.detail??'Resolve the required relationships before review.',page:'correction',label:'Review the source and values',tone:'warning'};
 else if(soft)task={title:'Review the different readings',text:'Financial checks passed, but the reader observations need an evidence-backed resolution before separate approval.',page:'correction',label:'Review the source readings',tone:'warning'};
 else if(isApproved(pack))task={title:'Version '+snapshotVersion(pack)+' is approved',text:'The recorded independent approval covers this exact version and source snapshot.',page:'review',label:'Inspect the reviewed pack',tone:'info'};
 const attention=<Alert title={task.title} tone={task.tone}><p>{task.text}</p>{task.page&&task.page!==page&&!storyActions&&<Button onClick={()=>navigate(task.page!)}>{task.label}<ArrowRight size={16} aria-hidden/></Button>}{storyActions}</Alert>;
 const title=page==='overview'?pack.title:page==='correction'?soft?'Review the different readings':'Correct a pack value':page==='checks'?'Check the updated pack':'Review and approve';
 return <div className="workspace"><a href="#current-task" className="skip-link" onClick={e=>{e.preventDefault();mainRef.current?.focus();}}>Skip to current task</a><header className="topbar"><div className="brand"><span className="brand-mark" aria-hidden/>CloseGraph</div><div className="topbar-actions"><span className="user">{accountLabel(session.username,session.role)}</span>{onLogout&&<Button variant="link" onClick={onLogout}>Sign out</Button>}</div></header>{toolbar}<div className="layout"><aside className="sidebar"><p className="pack-name">{pack.title}</p><nav className="nav" aria-label="Pack pages">{pages.map(([id,label],i)=><a href={'#'+id} key={id} aria-current={page===id?'page':undefined} onClick={event=>{event.preventDefault();navigate(id);}}><span className="nav-number" aria-hidden>{String(i+1).padStart(2,'0')}</span>{label}</a>)}</nav><div className="sidebar-end">{pack.fund_id}<br/>{pack.facts[0]?.period}</div></aside><main ref={mainRef} id="current-task" className="main" tabIndex={-1}><div className="page-head"><div><h1>{title}</h1><p>{page==='checks'?'See which values changed and whether the required relationships agree.':pack.fund_id+' · '+(pack.facts[0]?.period??'Period pending')+' · '+(pack.facts[0]?.currency??'Currency pending')}</p></div><span className="version">Version {snapshotVersion(pack)}</span></div>{error&&<div role="alert"><Alert tone="danger" title="Action could not be completed"><p>{error}</p><p>Your entered values are retained. Reload the current version if another user changed this pack.</p></Alert></div>}{observationError&&<Alert title="Review activity was not recorded" tone="warning"><p role="alert">{observationError}</p></Alert>}{attention}{page==='overview'&&<div className="grid"><section><div className="section-head"><h2>Documents in this pack</h2><span className="caption">{sourceEntries(pack).length} sources</span></div><ul className="files">{sourceEntries(pack).map(([id,source])=><li key={id}><Button variant="link" onClick={()=>{setSourceId(id);if(typeof source.document_version_id==='string')void observe({event_type:'SOURCE_OPENED',document_version_id:source.document_version_id});navigate('correction');}}><span><span className="file-name">{sourceName(id,source)} ↗</span><span className="caption">{locatorText(source.locator)}</span></span></Button></li>)}</ul>{!sourceEntries(pack).length&&<p className="muted">Upload the required source files to begin verification.</p>}</section><section><h2>Review responsibilities</h2><dl className="metadata"><div><dt>Prepares and corrects</dt><dd>Authorised accountant for this pack</dd></div><div><dt>Independently approves</dt><dd>An account manager who did not prepare the corrected scope</dd></div><div><dt>Your scope</dt><dd>{pack.fund_id} · {pack.pack_id}</dd></div></dl><p className="caption">Source access and actions are authorised by your server session.</p></section></div>}
 {page==='correction'&&<div className="grid"><SourceEvidence pack={pack} fact={fact} onOpenDocument={document=>void observe({event_type:'SOURCE_OPENED',document_version_id:document})} selectedSource={sourceId} onSelectSource={id=>{setSourceId(id);const s=sourceEntries(pack,fact).find(([key])=>key===id)?.[1];if(typeof s?.document_version_id==='string')void observe({event_type:'SOURCE_OPENED',document_version_id:s.document_version_id});}} synthetic={synthetic}/>{(soft||pack.resolution)&&!canPrepare(session)?<ResolutionPanel key={'resolution-'+pack.pack_id+'-'+pack.version} pack={pack} session={session} pending={pending} onResolve={actions.resolve}/>:<CorrectionPanel key={pack.pack_id} pack={pack} fact={fact} session={session} pending={pending} onFactChange={selectFact} onReplaceSource={actions.replaceSource} onCorrect={async input=>{await actions.correct(input);navigate('checks');}}/>}</div>}
 {page==='checks'&&<><div className="section-head"><h2>All pack values</h2><span className="caption">Original and current observations</span></div><div className="table-wrap" role="region" aria-label="Pack value comparison" tabIndex={0}><table className="table"><caption>All values remain inspectable, including values with passing checks.</caption><thead><tr><th scope="col">Pack value</th><th scope="col" className="number">Original source</th><th scope="col" className="number">Version {pack.version}</th><th scope="col">Evidence</th></tr></thead><tbody>{pack.facts.map(f=><tr key={f.fact_id}><td>{f.metric}<small>{f.entity_id} · {f.period}</small>{f.value_state&&f.value_state!=='PRESENT'&&<small>{humanize(f.value_state)}</small>}</td><td className="number">{f.raw_value==null?<span aria-label="Original source value unavailable">—</span>:String(f.raw_value)}</td><td className="number">{f.value_decimal?formatFactValue(f):<span aria-label="Current value unavailable until checks complete">—</span>}</td><td><Button variant="link" onClick={()=>inspectFact(f.fact_id)}>{locatorText(sourceOf(f).locator)}</Button></td></tr>)}</tbody></table></div><Accordion type="multiple" defaultValue={['checks']} className="accordion"><AccordionItem value="checks"><AccordionTrigger>All {pack.checks.length} check results</AccordionTrigger><AccordionContent className="accordion-body"><CheckList checks={pack.checks}/></AccordionContent></AccordionItem></Accordion><div className="controls"><Button variant="outline" disabled={!canPrepare(session)||pending||processing} onClick={()=>void actions.recompute().catch(()=>undefined)}><RefreshCw size={16} aria-hidden/>Recheck current version</Button><Button onClick={()=>navigate(eligibleForReview(pack)?'review':'correction')}>{eligibleForReview(pack)?'Continue to approval':'Review source and corrections'}<ArrowRight size={16} aria-hidden/></Button></div></>}
 {page==='review'&&<><ReadySample pack={pack} session={session} pending={observing} onSample={actions.observe?id=>inspectFact(id,true):undefined}/><div className="grid"><CandidatePreview pack={pack}/><ReviewDecision key={pack.pack_id+'-'+pack.version+'-'+session.username} pack={pack} session={session} pending={pending} onReview={actions.review} onReject={actions.reject}/></div><ReleasePanel pack={pack} pending={pending} onPublish={actions.publish} synthetic={synthetic}/></>}
 <StatusDetails pack={pack}/><History pack={pack}/><ReviewWorkReport work={reviewWork} error={observationError||reviewWorkError}/></main></div><footer className="footer"><span>{synthetic?'Synthetic Storybook example · fictional data':'CloseGraph · local reporting workspace'}</span><span>Evidence and version history retained</span></footer><div className="sr-only" role="status" aria-live="polite" aria-atomic="true">{announcement??'Version '+pack.version+' · processing '+humanize(pack.execution_status)+' · review '+humanize(pack.review_status)}</div></div>;
}
