import { Accordion,AccordionItem,AccordionTrigger,AccordionContent,Button } from '../../components/ui';
import { canReview,eligibleForReview,type PackSnapshot,type Session } from '../../lib/model';
export interface ReviewEventInput {event_type:'SOURCE_OPENED'|'VALUE_INSPECTED'|'READY_ITEM_SAMPLED';observed_snapshot_version:number;fact_id?:string;document_version_id?:string}
export interface ReviewWork {provenance:'LOCAL_OBSERVED';counts:Record<ReviewEventInput['event_type'],number>;total_events:number;first_event_at:string|null;last_event_at:string|null;elapsed_seconds:number|null;actions:Record<'CORRECTED'|'RESOLVED'|'APPROVED'|'REJECTED',number>;reopened_scope:{at:string;version:number;reason:string;impact:unknown}[]}
export function ReadySample({pack,session,pending,onSample}:{pack:PackSnapshot;session:Session;pending:boolean;onSample?:(fact:string)=>void}){
 if(!canReview(session)||!eligibleForReview(pack)||!onSample)return null;
 return <section className="card separator" aria-label="Ready item audit sample"><h2>Sample a ready value</h2><p className="muted">Passing values remain available for independent inspection. Record the value you sample and inspect its original evidence before approval.</p><div className="source-actions">{pack.facts.filter(f=>!f.derived).map(f=><Button key={f.fact_id} variant="outline" disabled={pending} onClick={()=>onSample(f.fact_id)}>Sample {f.metric}</Button>)}</div></section>;
}
export function ReviewWorkReport({work,error}:{work?:ReviewWork;error?:string}){
 return <Accordion type="multiple" className="accordion"><AccordionItem value="work"><AccordionTrigger>Observed review work</AccordionTrigger><AccordionContent className="accordion-body">{error&&<p role="alert">{error}</p>}{work?<><p>Recorded workspace activity. Elapsed time is the span between first and last recorded interaction; it includes pauses. No customer baseline or time savings have been measured.</p><dl className="status-grid"><div><dt>Source openings</dt><dd>{work.counts.SOURCE_OPENED}</dd></div><div><dt>Values inspected</dt><dd>{work.counts.VALUE_INSPECTED}</dd></div><div><dt>Ready values sampled</dt><dd>{work.counts.READY_ITEM_SAMPLED}</dd></div><div><dt>Recorded action span</dt><dd>{work.elapsed_seconds==null?'Not measured':work.elapsed_seconds+' seconds'}</dd></div><div><dt>Corrections</dt><dd>{work.actions.CORRECTED}</dd></div><div><dt>Resolutions / approvals / rejections</dt><dd>{work.actions.RESOLVED} / {work.actions.APPROVED} / {work.actions.REJECTED}</dd></div></dl><p>First recorded interaction: {work.first_event_at??'None'}<br/>Last recorded interaction: {work.last_event_at??'None'}</p><h3>Scope reopened by recorded changes</h3>{work.reopened_scope.length?work.reopened_scope.map((entry,i)=><div className="record" key={i}><strong>Version {entry.version} · {entry.reason}</strong><time>{entry.at}</time><p>{typeof entry.impact==='string'?entry.impact:JSON.stringify(entry.impact)}</p></div>):<p>No reopened scope is recorded.</p>}</>:<p>Recorded interaction measurements are not available for this view.</p>}</AccordionContent></AccordionItem></Accordion>;
}
