import { useId, useRef, useState } from 'react';
import { Button, Checkbox, Label, Textarea, Alert } from '../../components/ui';
import { Field, fieldDescription } from '../../components/closegraph/Field';
import { snapshotVersion, canReview, eligibleForReview, isApproved, type PackSnapshot, type Session } from '../../lib/model';
import { sourceEntries, sourceName } from './SourceEvidence';
export interface ReviewInput {expected_version:number;note:string;attested:boolean}
export interface ResolutionInput {expected_version:number;reason:string;source_ids:string[]}
export function ResolutionPanel({pack,session,pending,onResolve}:{pack:PackSnapshot;session:Session;pending:boolean;onResolve:(input:ResolutionInput)=>Promise<void>}) {
 const id=useId(),[reason,setReason]=useState(''),[source,setSource]=useState(''),[errors,setErrors]=useState<Record<string,string>>({}),ref=useRef<HTMLTextAreaElement>(null),sourceRef=useRef<HTMLSelectElement>(null);
 const resolved=Boolean(pack.resolution);
 const blocked=pack.checks.some(c=>c.required&&!['PASS','NOT_APPLICABLE'].includes(c.status))||!canReview(session)||pending;
 async function submit(e:React.FormEvent){e.preventDefault();const next:Record<string,string>={};if(!reason.trim())next.reason='Record the reason for accepting this reading.';if(!source)next.source='Choose the original evidence supporting the resolution.';setErrors(next);if(Object.keys(next).length){(next.reason?ref.current:sourceRef.current)?.focus();return;}try{await onResolve({expected_version:pack.version,reason:reason.trim(),source_ids:[source]});}catch{/* keep entered evidence */}}
 return <section><h2>Resolve the different readings</h2><p className="muted">The original observations are retained. Passing financial checks alone does not resolve a reader disagreement. To use another value, an authorised accountant must record an evidenced correction, which creates a new snapshot.</p>{resolved?<Alert title="Evidence-backed resolution recorded"><p>Approval remains a separate decision for version {snapshotVersion(pack)}.</p></Alert>:<form onSubmit={submit} noValidate><Field id={id} label="Evidence and reason for accepting the reading" help="Identify the original source and authorised rule." error={errors.reason}><Textarea id={id} ref={ref} value={reason} onChange={e=>setReason(e.target.value)} required disabled={blocked} aria-invalid={Boolean(errors.reason)} aria-describedby={fieldDescription(id,'help',errors.reason)}/></Field><Field id={id+'-source'} label="Resolution evidence" error={errors.source}><select id={id+'-source'} ref={sourceRef} className="input" aria-invalid={Boolean(errors.source)} aria-describedby={fieldDescription(id+'-source',undefined,errors.source)} value={source} onChange={e=>setSource(e.target.value)} required disabled={blocked}><option value="">Choose evidence</option>{sourceEntries(pack).map(([key,s])=><option key={key} value={key}>{sourceName(key,s)}</option>)}</select></Field><Button type="submit" disabled={blocked}>{pending?'Saving resolution…':'Record review resolution'}</Button>{!canReview(session)&&<p className="caption">An independent account manager must resolve this difference.</p>}</form>}</section>;
}
export function ReviewDecision({pack,session,pending,onReview,onReject}:{pack:PackSnapshot;session:Session;pending:boolean;onReview:(input:ReviewInput)=>Promise<void>;onReject?:(input:{expected_version:number;note:string})=>Promise<void>}) {
 const id=useId(),[note,setNote]=useState(''),[attested,setAttested]=useState(false),[error,setError]=useState(''),ref=useRef<HTMLTextAreaElement>(null);
 const eligible=eligibleForReview(pack), independent=canReview(session), approved=isApproved(pack);
 async function submit(e:React.FormEvent){e.preventDefault();if(!note.trim()){setError('Add a review note explaining your decision.');ref.current?.focus();return;}if(!eligible||!independent||!attested||pending||approved)return;try{await onReview({expected_version:pack.version,note:note.trim(),attested});}catch{/* Preserve note and attestation after a server error. */}}
 async function reject(){if(!note.trim()){setError('Add a review note explaining the requested revision.');ref.current?.focus();return;}try{await onReject?.({expected_version:pack.version,note:note.trim()});}catch{/* parent error */}}
 if(approved)return <Alert title={'Version '+snapshotVersion(pack)+' is approved'}><p>The independent decision applies to this exact snapshot and its supporting sources. Publication is checked separately.</p></Alert>;
 return <section><h2>{independent?'Approve version '+snapshotVersion(pack):'Ready for independent review'}</h2><p className="muted">{independent?'Inspect the candidate workbook, values and linked source evidence before recording your decision.':'A different authorised account manager must approve the exact snapshot. Sign out to use your separately provisioned account-manager account.'}</p>{!eligible&&<Alert tone="warning" title="Approval is blocked"><p>Resolve required checks, source currency and reader disagreements before approval.</p></Alert>}{independent&&<form onSubmit={submit} noValidate><Field id={id} label="Review note" help={'Saved with your decision for version '+snapshotVersion(pack)+'.'} error={error}><Textarea id={id} ref={ref} value={note} onChange={e=>setNote(e.target.value)} required disabled={pending} aria-invalid={Boolean(error)} aria-describedby={fieldDescription(id,'help',error)}/></Field><div className="attestation"><Checkbox id={id+'-attest'} checked={attested} onCheckedChange={value=>setAttested(value===true)} disabled={!eligible||pending} required/><Label htmlFor={id+'-attest'}>I have reviewed version {snapshotVersion(pack)}, the candidate workbook and its supporting evidence.</Label></div><div className="controls"><Button type="submit" disabled={!eligible||!attested||pending}>{pending?'Recording decision…':'Approve version '+snapshotVersion(pack)}</Button>{onReject&&<Button type="button" variant="outline" disabled={pending} onClick={()=>void reject()}>Request revision</Button>}</div><p className="caption">A later source, rule or value change requires a new review. Earlier decisions stay in the history.</p></form>}</section>;
}
