import { useId, useRef, useState } from 'react';
import { Button, Dialog, DialogContent, DialogTrigger, Input } from '../../components/ui';
import { Field } from '../../components/closegraph/Field';
import { fileBase64, type UploadInput } from '../../lib/api';
import type { PackSnapshot } from '../../lib/model';
export function UploadPanel({pack,pending,onUpload,open:controlledOpen,onOpenChange}:{pack:PackSnapshot;pending:boolean;onUpload:(input:UploadInput)=>Promise<void>;open?:boolean;onOpenChange?:(open:boolean)=>void}) {
 const id=useId(),[internalOpen,setInternalOpen]=useState(false),[source,setSource]=useState('capital'),[file,setFile]=useState<File|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),fileRef=useRef<HTMLInputElement>(null);
 const open=controlledOpen??internalOpen,setOpen=onOpenChange??setInternalOpen;
 async function submit(event:React.FormEvent){event.preventDefault();if(!file){setError('Choose the source file to upload.');fileRef.current?.focus();return;}setBusy(true);setError('');try{const extension=file.name.split('.').pop()?.toLowerCase();const media_type=extension==='xlsx'?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':extension==='csv'?'text/csv':extension==='pdf'?'application/pdf':file.type;if(!['csv','xlsx','pdf'].includes(extension??''))throw new Error('Choose a supported CSV, XLSX or PDF source.');await onUpload({expected_version:pack.version,source_id:source,filename:file.name,media_type,content_base64:await fileBase64(file)});setOpen(false);setFile(null);}catch(err){setError((err as Error).message);}finally{setBusy(false);}}
 return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" disabled={pending}>Upload source</Button></DialogTrigger><DialogContent title="Add a source version" description="The original bytes are kept. New evidence triggers checks and makes previous approval historical."><form onSubmit={submit} noValidate><Field id={id+'-role'} label="Source purpose"><select className="input" id={id+'-role'} value={source} onChange={e=>setSource(e.target.value)} disabled={pending||busy}><option value="capital">Opening capital input</option><option value="fee-rule">Authorised fee rule</option><option value="original">Original reporting workbook</option><option value="reporting-evidence">Reporting evidence PDF</option></select></Field><Field id={id+'-file'} label="Source file" help="Supported declared CSV, XLSX or PDF layouts. Required PDF processing must be configured." error={error}><Input id={id+'-file'} ref={fileRef} type="file" accept=".csv,.xlsx,.pdf" onChange={e=>setFile(e.target.files?.[0]??null)} disabled={pending||busy} required aria-invalid={Boolean(error)} aria-describedby={id+'-file-help'+(error?' '+id+'-file-error':'')}/></Field><div className="form-footer"><Button type="submit" disabled={pending||busy}>{busy?'Uploading source…':'Upload and check source'}</Button></div></form></DialogContent></Dialog>;
}
